import {it,expect,vi} from 'vitest';
import {randomUUID} from 'node:crypto';
vi.mock('server-only',()=>({}));
import {localSqlClient} from './fixtures/local-sql-client';
import {projectInquiryContext,type InquiryContext} from '@/lib/inquiries/schemas';
import {readOwnInquiries} from '@/lib/inquiries/server';
it.skipIf(!process.env.MEDBRIDGE_LOCAL_WORKFLOW_DB)('real local PostgreSQL: genuine response, atomic failure, retry, missing evidence and consent withdrawal',async()=>{
  const url=process.env.MEDBRIDGE_LOCAL_WORKFLOW_DB!,root=localSqlClient(url,'postgres'),owner=randomUUID();
  root.sql(`insert into auth.users(id) values('${owner}');insert into public.profiles(id) values('${owner}') on conflict do nothing;select to_json(true)`);
  const fixture=root.sql(`select json_build_object('hospital',h.id,'organization',private.inquiry_connected_org('hospital',h.id),'provider',(select user_id from public.organization_members where organization_id=private.inquiry_connected_org('hospital',h.id) and active limit 1)) from public.hospitals h where private.inquiry_connected_org('hospital',h.id) is not null limit 1`);
  expect(fixture?.provider).toBeTruthy();
  const patient=localSqlClient(url,'authenticated',owner).db,provider=localSqlClient(url,'authenticated',fixture.provider).db;
  const target=await patient.rpc('inquiry_target',{p_kind:'hospital',p_id:fixture.hospital});expect(target.error).toBeNull();
  const created=await patient.rpc('inquiry_command',{p_action:'create',p_input:{operationId:randomUUID(),entityKind:'hospital',entityId:fixture.hospital,expectedPublishedRevision:(target.data as {publishedRevision:number}).publishedRevision,source:'hospital_detail',title:'LOCAL safety rehearsal',objective:'QA administrative coordination only.',consent:true,reviewed:true}});expect(created.error).toBeNull();
  const caseId=(created.data as {id:string}).id;
  expect((await provider.rpc('inquiry_context',{p_case_id:caseId})).error).toBeTruthy();
  expect((await patient.rpc('inquiry_command',{p_action:'share_provider',p_input:{operationId:randomUUID(),caseId,organizationId:fixture.organization,purpose:'QA coordinate the reviewed request.',confirmed:true}})).error).toBeNull();
  const input={operationId:randomUUID(),caseId,status:'accepted_for_coordination',body:'QA authorized representative can continue administrative coordination.',confirmed:true};
  const first=await provider.rpc('inquiry_command',{p_action:'provider_response',p_input:input}),retry=await provider.rpc('inquiry_command',{p_action:'provider_response',p_input:input});
  expect(first.error).toBeNull();expect(retry.data).toEqual(first.data);
  const before=await patient.rpc('inquiry_context',{p_case_id:caseId});expect(before.error).toBeNull();
  expect(projectInquiryContext(before.data as unknown as InquiryContext).case.provider_response_status).toBe('accepted_for_coordination');
  const message=(first.data as {id:string}).id;
  const failedInput={...input,operationId:randomUUID(),body:'QA_PARTIAL_FAILURE_MUST_NOT_COMMIT'};
  root.sql(`set local role authenticated;set local "request.jwt.claim.sub"='${fixture.provider}';do $$begin begin perform public.inquiry_command('provider_response','${JSON.stringify(failedInput)}');raise exception 'QA_INJECTED_AFTER_WRITE';exception when others then if sqlerrm<>'QA_INJECTED_AFTER_WRITE' then raise;end if;end;end$$;select to_json(true)`);
  expect(root.sql(`select to_json(count(*)) from public.support_case_messages where case_id='${caseId}' and sender_role='provider'`)).toBe(1);
  expect(root.sql(`select to_json(count(*)) from public.support_operation_receipts where operation_id='${failedInput.operationId}'`)).toBe(0);
  // Simulate an incomplete legacy projection in loopback QA, never in production.
  root.sql(`update public.support_cases set provider_response_message_id=null where id='${caseId}';select to_json(true)`);
  const incomplete=await patient.rpc('inquiry_context',{p_case_id:caseId});expect(incomplete.error).toBeNull();
  expect((incomplete.data as unknown as InquiryContext).providerCoordination?.latestResponse).toBeNull();
  expect(projectInquiryContext(incomplete.data as unknown as InquiryContext).case.provider_response_status).toBe('unconfirmed_response');
  expect((await readOwnInquiries(patient,owner,caseId)).requests[0].providerStatus).toBe('unconfirmed_response');
  root.sql(`update public.support_cases set provider_response_message_id='${message}' where id='${caseId}';select to_json(true)`);
  expect((await patient.rpc('inquiry_command',{p_action:'revoke_support',p_input:{operationId:randomUUID(),caseId}})).error).toBeNull();
  expect((await provider.rpc('inquiry_context',{p_case_id:caseId})).error).toBeTruthy();
  expect((await provider.rpc('inquiry_command',{p_action:'provider_response',p_input:input})).error).toBeTruthy();
  expect((await patient.rpc('inquiry_context',{p_case_id:caseId})).error).toBeNull();
  expect(root.sql(`select to_json(count(*)) from public.support_case_messages where case_id='${caseId}' and sender_role='provider'`)).toBe(1);
},120000);
