// Generated from the migrated PostgreSQL schema by scripts/generate-db-types.mjs.
// Regenerate after changing migrations; do not edit this file by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      agent_actions: {
        Row: {
          id: string;
          run_id: string;
          task_id: string | null;
          action_name: string;
          tool_name: string | null;
          tool_version: string | null;
          status: string;
          input_hash: string | null;
          output_hash: string | null;
          requires_approval: boolean;
          performed_at: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          run_id: string;
          task_id?: string | null;
          action_name: string;
          tool_name?: string | null;
          tool_version?: string | null;
          status: string;
          input_hash?: string | null;
          output_hash?: string | null;
          requires_approval?: boolean;
          performed_at?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          run_id?: string;
          task_id?: string | null;
          action_name?: string;
          tool_name?: string | null;
          tool_version?: string | null;
          status?: string;
          input_hash?: string | null;
          output_hash?: string | null;
          requires_approval?: boolean;
          performed_at?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      agent_approvals: {
        Row: {
          id: string;
          action_id: string;
          requested_by: string | null;
          reviewer_id: string | null;
          decision: string;
          reason: string | null;
          decided_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          action_id: string;
          requested_by?: string | null;
          reviewer_id?: string | null;
          decision?: string;
          reason?: string | null;
          decided_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          action_id?: string;
          requested_by?: string | null;
          reviewer_id?: string | null;
          decision?: string;
          reason?: string | null;
          decided_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      agent_outputs: {
        Row: {
          id: string;
          run_id: string;
          task_id: string | null;
          output_type: string;
          content: Json;
          source_record_ids: string[];
          review_status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          run_id: string;
          task_id?: string | null;
          output_type: string;
          content: Json;
          source_record_ids?: string[];
          review_status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          run_id?: string;
          task_id?: string | null;
          output_type?: string;
          content?: Json;
          source_record_ids?: string[];
          review_status?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      agent_runs: {
        Row: {
          id: string;
          case_id: string | null;
          agent_name: string;
          agent_version: string;
          initiated_by: string | null;
          purpose: string;
          status: string;
          started_at: string | null;
          finished_at: string | null;
          trace_id: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
          conversation_id: string | null;
          care_plan_id: string | null;
        };
        Insert: {
          id?: string;
          case_id?: string | null;
          agent_name: string;
          agent_version: string;
          initiated_by?: string | null;
          purpose: string;
          status: string;
          started_at?: string | null;
          finished_at?: string | null;
          trace_id?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
          conversation_id?: string | null;
          care_plan_id?: string | null;
        };
        Update: {
          id?: string;
          case_id?: string | null;
          agent_name?: string;
          agent_version?: string;
          initiated_by?: string | null;
          purpose?: string;
          status?: string;
          started_at?: string | null;
          finished_at?: string | null;
          trace_id?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
          conversation_id?: string | null;
          care_plan_id?: string | null;
        };
        Relationships: [];
      };
      agent_tasks: {
        Row: {
          id: string;
          run_id: string;
          case_id: string | null;
          task_type: string;
          status: string;
          objective: string;
          due_at: string | null;
          created_at: string;
          updated_at: string;
          tool_name: string | null;
          input_summary: Json;
          output_summary: Json;
          started_at: string | null;
          completed_at: string | null;
          error_code: string | null;
          care_plan_task_id: string | null;
        };
        Insert: {
          id?: string;
          run_id: string;
          case_id?: string | null;
          task_type: string;
          status: string;
          objective: string;
          due_at?: string | null;
          created_at?: string;
          updated_at?: string;
          tool_name?: string | null;
          input_summary?: Json;
          output_summary?: Json;
          started_at?: string | null;
          completed_at?: string | null;
          error_code?: string | null;
          care_plan_task_id?: string | null;
        };
        Update: {
          id?: string;
          run_id?: string;
          case_id?: string | null;
          task_type?: string;
          status?: string;
          objective?: string;
          due_at?: string | null;
          created_at?: string;
          updated_at?: string;
          tool_name?: string | null;
          input_summary?: Json;
          output_summary?: Json;
          started_at?: string | null;
          completed_at?: string | null;
          error_code?: string | null;
          care_plan_task_id?: string | null;
        };
        Relationships: [];
      };
      audit_events: {
        Row: {
          id: string;
          actor_id: string | null;
          actor_type: string;
          event_name: string;
          entity_type: string;
          entity_id: string | null;
          case_id: string | null;
          occurred_at: string;
          metadata: Json;
          organization_id: string | null;
          actor_role: string | null;
          old_value: Json | null;
          new_value: Json | null;
        };
        Insert: {
          id?: string;
          actor_id?: string | null;
          actor_type: string;
          event_name: string;
          entity_type: string;
          entity_id?: string | null;
          case_id?: string | null;
          occurred_at?: string;
          metadata?: Json;
          organization_id?: string | null;
          actor_role?: string | null;
          old_value?: Json | null;
          new_value?: Json | null;
        };
        Update: {
          id?: string;
          actor_id?: string | null;
          actor_type?: string;
          event_name?: string;
          entity_type?: string;
          entity_id?: string | null;
          case_id?: string | null;
          occurred_at?: string;
          metadata?: Json;
          organization_id?: string | null;
          actor_role?: string | null;
          old_value?: Json | null;
          new_value?: Json | null;
        };
        Relationships: [];
      };
      care_plan_tasks: {
        Row: {
          id: string;
          care_plan_id: string;
          task_key: string;
          title: string;
          description: string;
          task_type: string;
          status: string;
          priority: string;
          requires_user_action: boolean;
          requires_approval: boolean;
          approval_status: string;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          care_plan_id: string;
          task_key: string;
          title: string;
          description?: string;
          task_type: string;
          status?: string;
          priority?: string;
          requires_user_action?: boolean;
          requires_approval?: boolean;
          approval_status?: string;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          care_plan_id?: string;
          task_key?: string;
          title?: string;
          description?: string;
          task_type?: string;
          status?: string;
          priority?: string;
          requires_user_action?: boolean;
          requires_approval?: boolean;
          approval_status?: string;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      care_plans: {
        Row: {
          id: string;
          user_id: string;
          conversation_id: string;
          title: string;
          goal: string;
          status: string;
          destination_country: string | null;
          destination_city: string | null;
          treatment_id: string | null;
          context: Json;
          findings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          conversation_id: string;
          title: string;
          goal: string;
          status?: string;
          destination_country?: string | null;
          destination_city?: string | null;
          treatment_id?: string | null;
          context?: Json;
          findings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          conversation_id?: string;
          title?: string;
          goal?: string;
          status?: string;
          destination_country?: string | null;
          destination_city?: string | null;
          treatment_id?: string | null;
          context?: Json;
          findings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      case_documents: {
        Row: {
          id: string;
          case_id: string;
          uploaded_by: string;
          document_type: string;
          title: string;
          storage_path: string;
          mime_type: string;
          file_size_bytes: number;
          status: string;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          case_id: string;
          uploaded_by: string;
          document_type: string;
          title: string;
          storage_path: string;
          mime_type: string;
          file_size_bytes: number;
          status?: string;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          case_id?: string;
          uploaded_by?: string;
          document_type?: string;
          title?: string;
          storage_path?: string;
          mime_type?: string;
          file_size_bytes?: number;
          status?: string;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      case_members: {
        Row: {
          case_id: string;
          user_id: string;
          role: string;
          granted_by: string;
          granted_at: string;
          revoked_at: string | null;
        };
        Insert: {
          case_id: string;
          user_id: string;
          role: string;
          granted_by: string;
          granted_at?: string;
          revoked_at?: string | null;
        };
        Update: {
          case_id?: string;
          user_id?: string;
          role?: string;
          granted_by?: string;
          granted_at?: string;
          revoked_at?: string | null;
        };
        Relationships: [];
      };
      case_status_history: {
        Row: {
          id: string;
          case_id: string;
          from_status: Database["public"]["Enums"]["case_lifecycle_status"] | null;
          to_status: Database["public"]["Enums"]["case_lifecycle_status"];
          changed_by: string | null;
          changed_at: string;
          note: string | null;
        };
        Insert: {
          id?: string;
          case_id: string;
          from_status?: Database["public"]["Enums"]["case_lifecycle_status"] | null;
          to_status: Database["public"]["Enums"]["case_lifecycle_status"];
          changed_by?: string | null;
          changed_at?: string;
          note?: string | null;
        };
        Update: {
          id?: string;
          case_id?: string;
          from_status?: Database["public"]["Enums"]["case_lifecycle_status"] | null;
          to_status?: Database["public"]["Enums"]["case_lifecycle_status"];
          changed_by?: string | null;
          changed_at?: string;
          note?: string | null;
        };
        Relationships: [];
      };
      cases: {
        Row: {
          id: string;
          owner_id: string;
          status: Database["public"]["Enums"]["case_lifecycle_status"];
          title: string;
          description: string | null;
          preferred_country_id: string | null;
          preferred_city_id: string | null;
          preferred_treatment_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          status?: Database["public"]["Enums"]["case_lifecycle_status"];
          title: string;
          description?: string | null;
          preferred_country_id?: string | null;
          preferred_city_id?: string | null;
          preferred_treatment_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          status?: Database["public"]["Enums"]["case_lifecycle_status"];
          title?: string;
          description?: string | null;
          preferred_country_id?: string | null;
          preferred_city_id?: string | null;
          preferred_treatment_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      catalog_drafts: {
        Row: {
          id: string;
          entity: string;
          target_id: string | null;
          name: string;
          data: Json;
          revision: number;
          expected_updated_at: string | null;
          status: string;
          created_by: string;
          approved_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          entity: string;
          target_id?: string | null;
          name: string;
          data: Json;
          revision?: number;
          expected_updated_at?: string | null;
          status?: string;
          created_by: string;
          approved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          entity?: string;
          target_id?: string | null;
          name?: string;
          data?: Json;
          revision?: number;
          expected_updated_at?: string | null;
          status?: string;
          created_by?: string;
          approved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      cities: {
        Row: {
          id: string;
          country_id: string;
          slug: string;
          name: string;
          aliases: string[];
          created_at: string;
          updated_at: string;
          publication_status: string;
          source_kind: string;
          source_record_id: string | null;
        };
        Insert: {
          id?: string;
          country_id: string;
          slug: string;
          name: string;
          aliases?: string[];
          created_at?: string;
          updated_at?: string;
          publication_status?: string;
          source_kind?: string;
          source_record_id?: string | null;
        };
        Update: {
          id?: string;
          country_id?: string;
          slug?: string;
          name?: string;
          aliases?: string[];
          created_at?: string;
          updated_at?: string;
          publication_status?: string;
          source_kind?: string;
          source_record_id?: string | null;
        };
        Relationships: [];
      };
      conditions: {
        Row: {
          id: string;
          slug: string;
          name: string;
          aliases: string[];
          source_kind: string;
          created_at: string;
          updated_at: string;
          source_record_id: string | null;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          aliases?: string[];
          source_kind: string;
          created_at?: string;
          updated_at?: string;
          source_record_id?: string | null;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          aliases?: string[];
          source_kind?: string;
          created_at?: string;
          updated_at?: string;
          source_record_id?: string | null;
        };
        Relationships: [];
      };
      consents: {
        Row: {
          id: string;
          subject_id: string;
          case_id: string | null;
          consent_type: string;
          purpose: string;
          decision: string;
          granted_at: string | null;
          revoked_at: string | null;
          version: string;
          source: string;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          subject_id: string;
          case_id?: string | null;
          consent_type: string;
          purpose: string;
          decision: string;
          granted_at?: string | null;
          revoked_at?: string | null;
          version: string;
          source: string;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          subject_id?: string;
          case_id?: string | null;
          consent_type?: string;
          purpose?: string;
          decision?: string;
          granted_at?: string | null;
          revoked_at?: string | null;
          version?: string;
          source?: string;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      conversation_messages: {
        Row: {
          id: string;
          conversation_id: string;
          run_id: string | null;
          role: string;
          visibility: string;
          content: string;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          run_id?: string | null;
          role: string;
          visibility?: string;
          content: string;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          run_id?: string | null;
          role?: string;
          visibility?: string;
          content?: string;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      conversations: {
        Row: {
          id: string;
          owner_id: string;
          case_id: string | null;
          title: string;
          status: string;
          created_at: string;
          updated_at: string;
          execution_token: string | null;
          execution_expires_at: string | null;
        };
        Insert: {
          id?: string;
          owner_id: string;
          case_id?: string | null;
          title?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
          execution_token?: string | null;
          execution_expires_at?: string | null;
        };
        Update: {
          id?: string;
          owner_id?: string;
          case_id?: string | null;
          title?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
          execution_token?: string | null;
          execution_expires_at?: string | null;
        };
        Relationships: [];
      };
      countries: {
        Row: {
          id: string;
          slug: string;
          iso_code: string;
          name: string;
          description: string;
          aliases: string[];
          travel_note: string;
          source_kind: string;
          publication_status: string;
          created_at: string;
          updated_at: string;
          source_record_id: string | null;
        };
        Insert: {
          id?: string;
          slug: string;
          iso_code: string;
          name: string;
          description?: string;
          aliases?: string[];
          travel_note?: string;
          source_kind: string;
          publication_status?: string;
          created_at?: string;
          updated_at?: string;
          source_record_id?: string | null;
        };
        Update: {
          id?: string;
          slug?: string;
          iso_code?: string;
          name?: string;
          description?: string;
          aliases?: string[];
          travel_note?: string;
          source_kind?: string;
          publication_status?: string;
          created_at?: string;
          updated_at?: string;
          source_record_id?: string | null;
        };
        Relationships: [];
      };
      doctor_specialties: {
        Row: {
          doctor_id: string;
          specialty_id: string;
          is_primary: boolean;
        };
        Insert: {
          doctor_id: string;
          specialty_id: string;
          is_primary?: boolean;
        };
        Update: {
          doctor_id?: string;
          specialty_id?: string;
          is_primary?: boolean;
        };
        Relationships: [];
      };
      doctor_treatments: {
        Row: {
          doctor_id: string;
          treatment_id: string;
        };
        Insert: {
          doctor_id: string;
          treatment_id: string;
        };
        Update: {
          doctor_id?: string;
          treatment_id?: string;
        };
        Relationships: [];
      };
      doctors: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string;
          aliases: string[];
          home_city_id: string | null;
          experience_years: number | null;
          languages: string[];
          consultation_mode: string | null;
          qualifications_note: string;
          verification_status: Database["public"]["Enums"]["provider_verification_status"];
          verification_source: string | null;
          verification_date: string | null;
          last_verified_at: string | null;
          verified_by: string | null;
          source_kind: string;
          publication_status: string;
          source_record_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description: string;
          aliases?: string[];
          home_city_id?: string | null;
          experience_years?: number | null;
          languages?: string[];
          consultation_mode?: string | null;
          qualifications_note?: string;
          verification_status?: Database["public"]["Enums"]["provider_verification_status"];
          verification_source?: string | null;
          verification_date?: string | null;
          last_verified_at?: string | null;
          verified_by?: string | null;
          source_kind: string;
          publication_status?: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string;
          aliases?: string[];
          home_city_id?: string | null;
          experience_years?: number | null;
          languages?: string[];
          consultation_mode?: string | null;
          qualifications_note?: string;
          verification_status?: Database["public"]["Enums"]["provider_verification_status"];
          verification_source?: string | null;
          verification_date?: string | null;
          last_verified_at?: string | null;
          verified_by?: string | null;
          source_kind?: string;
          publication_status?: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      document_checklists: {
        Row: {
          id: string;
          hospital_id: string;
          service_id: string | null;
          service_label: string | null;
          source_kind: string;
          source_label: string;
          source_reference: string | null;
          requirements: Json;
          published: boolean;
          updated_at: string;
        };
        Insert: {
          id?: string;
          hospital_id: string;
          service_id?: string | null;
          service_label?: string | null;
          source_kind: string;
          source_label: string;
          source_reference?: string | null;
          requirements: Json;
          published?: boolean;
          updated_at?: string;
        };
        Update: {
          id?: string;
          hospital_id?: string;
          service_id?: string | null;
          service_label?: string | null;
          source_kind?: string;
          source_label?: string;
          source_reference?: string | null;
          requirements?: Json;
          published?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      document_coordination_audit: {
        Row: {
          id: string;
          workspace_id: string;
          owner_id: string;
          revision: number;
          action: string;
          snapshot: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          owner_id: string;
          revision: number;
          action: string;
          snapshot: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          owner_id?: string;
          revision?: number;
          action?: string;
          snapshot?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      document_workspaces: {
        Row: {
          id: string;
          owner_id: string;
          conversation_id: string;
          hospital_id: string;
          service_id: string | null;
          service_label: string;
          revision: number;
          data: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          owner_id: string;
          conversation_id: string;
          hospital_id: string;
          service_id?: string | null;
          service_label: string;
          revision: number;
          data: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          conversation_id?: string;
          hospital_id?: string;
          service_id?: string | null;
          service_label?: string;
          revision?: number;
          data?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      healthcare_services: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string;
          aliases: string[];
          href: string;
          category: string;
          steps: string[];
          status: string;
          source_kind: string;
          created_at: string;
          updated_at: string;
          source_record_id: string | null;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description: string;
          aliases?: string[];
          href: string;
          category: string;
          steps?: string[];
          status?: string;
          source_kind: string;
          created_at?: string;
          updated_at?: string;
          source_record_id?: string | null;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string;
          aliases?: string[];
          href?: string;
          category?: string;
          steps?: string[];
          status?: string;
          source_kind?: string;
          created_at?: string;
          updated_at?: string;
          source_record_id?: string | null;
        };
        Relationships: [];
      };
      hospital_doctors: {
        Row: {
          hospital_id: string;
          doctor_id: string;
          is_primary: boolean;
          starts_on: string | null;
          ends_on: string | null;
          source_record_id: string;
        };
        Insert: {
          hospital_id: string;
          doctor_id: string;
          is_primary?: boolean;
          starts_on?: string | null;
          ends_on?: string | null;
          source_record_id: string;
        };
        Update: {
          hospital_id?: string;
          doctor_id?: string;
          is_primary?: boolean;
          starts_on?: string | null;
          ends_on?: string | null;
          source_record_id?: string;
        };
        Relationships: [];
      };
      hospital_specialties: {
        Row: {
          hospital_id: string;
          specialty_id: string;
        };
        Insert: {
          hospital_id: string;
          specialty_id: string;
        };
        Update: {
          hospital_id?: string;
          specialty_id?: string;
        };
        Relationships: [];
      };
      hospital_treatments: {
        Row: {
          hospital_id: string;
          treatment_id: string;
          source_record_id: string;
        };
        Insert: {
          hospital_id: string;
          treatment_id: string;
          source_record_id: string;
        };
        Update: {
          hospital_id?: string;
          treatment_id?: string;
          source_record_id?: string;
        };
        Relationships: [];
      };
      hospitals: {
        Row: {
          id: string;
          slug: string;
          name: string;
          city_id: string;
          description: string;
          aliases: string[];
          bed_count: number | null;
          accreditation_note: string | null;
          infrastructure: string[];
          verification_status: Database["public"]["Enums"]["provider_verification_status"];
          verification_source: string | null;
          verification_date: string | null;
          last_verified_at: string | null;
          verified_by: string | null;
          source_kind: string;
          publication_status: string;
          source_record_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          city_id: string;
          description: string;
          aliases?: string[];
          bed_count?: number | null;
          accreditation_note?: string | null;
          infrastructure?: string[];
          verification_status?: Database["public"]["Enums"]["provider_verification_status"];
          verification_source?: string | null;
          verification_date?: string | null;
          last_verified_at?: string | null;
          verified_by?: string | null;
          source_kind: string;
          publication_status?: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          city_id?: string;
          description?: string;
          aliases?: string[];
          bed_count?: number | null;
          accreditation_note?: string | null;
          infrastructure?: string[];
          verification_status?: Database["public"]["Enums"]["provider_verification_status"];
          verification_source?: string | null;
          verification_date?: string | null;
          last_verified_at?: string | null;
          verified_by?: string | null;
          source_kind?: string;
          publication_status?: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      operational_incidents: {
        Row: {
          id: string;
          category: string;
          severity: string;
          status: string;
          owner_id: string | null;
          created_by: string;
          correlation_id: string | null;
          revision: number;
          created_at: string;
          updated_at: string;
          resolved_at: string | null;
          resolution_note: string | null;
        };
        Insert: {
          id?: string;
          category: string;
          severity: string;
          status?: string;
          owner_id?: string | null;
          created_by: string;
          correlation_id?: string | null;
          revision?: number;
          created_at?: string;
          updated_at?: string;
          resolved_at?: string | null;
          resolution_note?: string | null;
        };
        Update: {
          id?: string;
          category?: string;
          severity?: string;
          status?: string;
          owner_id?: string | null;
          created_by?: string;
          correlation_id?: string | null;
          revision?: number;
          created_at?: string;
          updated_at?: string;
          resolved_at?: string | null;
          resolution_note?: string | null;
        };
        Relationships: [];
      };
      operational_recovery_attempts: {
        Row: {
          id: string;
          source_event_id: string;
          kind: string;
          status: string;
          attempt_count: number;
          last_attempt_at: string;
          next_attempt_at: string | null;
          result_code: string;
          last_actor_id: string;
        };
        Insert: {
          id?: string;
          source_event_id: string;
          kind?: string;
          status: string;
          attempt_count: number;
          last_attempt_at?: string;
          next_attempt_at?: string | null;
          result_code: string;
          last_actor_id: string;
        };
        Update: {
          id?: string;
          source_event_id?: string;
          kind?: string;
          status?: string;
          attempt_count?: number;
          last_attempt_at?: string;
          next_attempt_at?: string | null;
          result_code?: string;
          last_actor_id?: string;
        };
        Relationships: [];
      };
      organization_invites: {
        Row: {
          id: string;
          organization_id: string;
          email: string;
          role: string;
          invited_by: string;
          accepted_by: string | null;
          expires_at: string;
          revoked_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          email: string;
          role: string;
          invited_by: string;
          accepted_by?: string | null;
          expires_at?: string;
          revoked_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          email?: string;
          role?: string;
          invited_by?: string;
          accepted_by?: string | null;
          expires_at?: string;
          revoked_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      organization_members: {
        Row: {
          organization_id: string;
          user_id: string;
          role: string;
          active: boolean;
          joined_at: string;
          last_active_at: string | null;
        };
        Insert: {
          organization_id: string;
          user_id: string;
          role: string;
          active?: boolean;
          joined_at?: string;
          last_active_at?: string | null;
        };
        Update: {
          organization_id?: string;
          user_id?: string;
          role?: string;
          active?: boolean;
          joined_at?: string;
          last_active_at?: string | null;
        };
        Relationships: [];
      };
      organization_messages: {
        Row: {
          id: string;
          organization_id: string;
          actor_id: string;
          body: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          actor_id: string;
          body: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          actor_id?: string;
          body?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      organization_verification_requests: {
        Row: {
          id: string;
          organization_id: string;
          document_id: string;
          requested_hospital_id: string | null;
          legal_name: string;
          contact_name: string;
          contact_email: string;
          contact_phone: string;
          declaration: string;
          status: string;
          submitted_by: string;
          submitted_at: string;
          reviewed_by: string | null;
          reviewed_at: string | null;
          reason: string | null;
          contact_confirmation: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          document_id: string;
          requested_hospital_id?: string | null;
          legal_name: string;
          contact_name: string;
          contact_email: string;
          contact_phone: string;
          declaration: string;
          status?: string;
          submitted_by: string;
          submitted_at?: string;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          reason?: string | null;
          contact_confirmation?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          document_id?: string;
          requested_hospital_id?: string | null;
          legal_name?: string;
          contact_name?: string;
          contact_email?: string;
          contact_phone?: string;
          declaration?: string;
          status?: string;
          submitted_by?: string;
          submitted_at?: string;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          reason?: string | null;
          contact_confirmation?: string | null;
        };
        Relationships: [];
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          legal_name: string;
          provider_type: string;
          source_kind: string;
          status: string;
          hospital_id: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
          onboarding_origin: string;
          verification_status: string;
          verification_request_id: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          legal_name?: string;
          provider_type: string;
          source_kind: string;
          status?: string;
          hospital_id?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
          onboarding_origin?: string;
          verification_status?: string;
          verification_request_id?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          legal_name?: string;
          provider_type?: string;
          source_kind?: string;
          status?: string;
          hospital_id?: string | null;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
          onboarding_origin?: string;
          verification_status?: string;
          verification_request_id?: string | null;
        };
        Relationships: [];
      };
      package_exclusions: {
        Row: {
          package_id: string;
          position: number;
          description: string;
        };
        Insert: {
          package_id: string;
          position: number;
          description: string;
        };
        Update: {
          package_id?: string;
          position?: number;
          description?: string;
        };
        Relationships: [];
      };
      package_inclusions: {
        Row: {
          package_id: string;
          position: number;
          description: string;
        };
        Insert: {
          package_id: string;
          position: number;
          description: string;
        };
        Update: {
          package_id?: string;
          position?: number;
          description?: string;
        };
        Relationships: [];
      };
      packages: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string;
          aliases: string[];
          treatment_id: string;
          hospital_id: string | null;
          country_id: string;
          duration_days: number | null;
          currency: string | null;
          estimated_min: number | null;
          estimated_max: number | null;
          price_type: string;
          benefits: string[];
          status: string;
          valid_from: string | null;
          valid_until: string | null;
          source_kind: string;
          source_record_id: string | null;
          created_at: string;
          updated_at: string;
          publication_status: string;
          city_id: string | null;
          price_valid_from: string | null;
          price_valid_until: string | null;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description: string;
          aliases?: string[];
          treatment_id: string;
          hospital_id?: string | null;
          country_id: string;
          duration_days?: number | null;
          currency?: string | null;
          estimated_min?: number | null;
          estimated_max?: number | null;
          price_type: string;
          benefits?: string[];
          status?: string;
          valid_from?: string | null;
          valid_until?: string | null;
          source_kind: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
          publication_status?: string;
          city_id?: string | null;
          price_valid_from?: string | null;
          price_valid_until?: string | null;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string;
          aliases?: string[];
          treatment_id?: string;
          hospital_id?: string | null;
          country_id?: string;
          duration_days?: number | null;
          currency?: string | null;
          estimated_min?: number | null;
          estimated_max?: number | null;
          price_type?: string;
          benefits?: string[];
          status?: string;
          valid_from?: string | null;
          valid_until?: string | null;
          source_kind?: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
          publication_status?: string;
          city_id?: string | null;
          price_valid_from?: string | null;
          price_valid_until?: string | null;
        };
        Relationships: [];
      };
      portal_accounts: {
        Row: {
          user_id: string;
          active: boolean;
          notification_preferences: Json;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          active?: boolean;
          notification_preferences?: Json;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          active?: boolean;
          notification_preferences?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      portal_network_operations: {
        Row: {
          actor_id: string;
          operation_id: string;
          action: string;
          input_hash: string;
          organization_id: string;
          result: Json;
          created_at: string;
        };
        Insert: {
          actor_id: string;
          operation_id: string;
          action: string;
          input_hash: string;
          organization_id: string;
          result: Json;
          created_at?: string;
        };
        Update: {
          actor_id?: string;
          operation_id?: string;
          action?: string;
          input_hash?: string;
          organization_id?: string;
          result?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      portal_notifications: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          body: string;
          resource_type: string;
          resource_id: string | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          body?: string;
          resource_type: string;
          resource_id?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          body?: string;
          resource_type?: string;
          resource_id?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      portal_settings: {
        Row: {
          key: string;
          value: Json;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          key: string;
          value: Json;
          updated_by?: string | null;
          updated_at?: string;
        };
        Update: {
          key?: string;
          value?: Json;
          updated_by?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      portal_verification_checks: {
        Row: {
          id: string;
          organization_id: string;
          initiated_by: string;
          provider_id: string;
          report: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          initiated_by: string;
          provider_id: string;
          report: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          initiated_by?: string;
          provider_id?: string;
          report?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      price_estimates: {
        Row: {
          id: string;
          treatment_id: string;
          country_id: string;
          hospital_id: string | null;
          package_id: string | null;
          currency: string;
          estimated_min: number;
          estimated_max: number;
          pricing_type: string;
          effective_from: string | null;
          expires_on: string | null;
          verification_status: string;
          publication_status: string;
          source_kind: string;
          source_record_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          treatment_id: string;
          country_id: string;
          hospital_id?: string | null;
          package_id?: string | null;
          currency: string;
          estimated_min: number;
          estimated_max: number;
          pricing_type: string;
          effective_from?: string | null;
          expires_on?: string | null;
          verification_status?: string;
          publication_status?: string;
          source_kind: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          treatment_id?: string;
          country_id?: string;
          hospital_id?: string | null;
          package_id?: string | null;
          currency?: string;
          estimated_min?: number;
          estimated_max?: number;
          pricing_type?: string;
          effective_from?: string | null;
          expires_on?: string | null;
          verification_status?: string;
          publication_status?: string;
          source_kind?: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          locale: string;
          timezone: string | null;
          created_at: string;
          updated_at: string;
          currency: string;
          phone: string;
          country: string;
          city: string;
          preferences_updated_at: string | null;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          locale?: string;
          timezone?: string | null;
          created_at?: string;
          updated_at?: string;
          currency?: string;
          phone?: string;
          country?: string;
          city?: string;
          preferences_updated_at?: string | null;
        };
        Update: {
          id?: string;
          display_name?: string | null;
          locale?: string;
          timezone?: string | null;
          created_at?: string;
          updated_at?: string;
          currency?: string;
          phone?: string;
          country?: string;
          city?: string;
          preferences_updated_at?: string | null;
        };
        Relationships: [];
      };
      provider_documents: {
        Row: {
          id: string;
          organization_id: string;
          record_id: string | null;
          name: string;
          document_type: string;
          storage_path: string;
          mime_type: string;
          size_bytes: number;
          expires_on: string | null;
          status: string;
          review_message: string;
          uploaded_by: string;
          reviewed_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          record_id?: string | null;
          name: string;
          document_type: string;
          storage_path: string;
          mime_type: string;
          size_bytes: number;
          expires_on?: string | null;
          status?: string;
          review_message?: string;
          uploaded_by: string;
          reviewed_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          record_id?: string | null;
          name?: string;
          document_type?: string;
          storage_path?: string;
          mime_type?: string;
          size_bytes?: number;
          expires_on?: string | null;
          status?: string;
          review_message?: string;
          uploaded_by?: string;
          reviewed_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      provider_field_reviews: {
        Row: {
          sequence: number;
          id: string;
          record_id: string;
          revision: number;
          organization_id: string;
          field: string;
          status: string;
          evidence: string;
          source_url: string | null;
          document_id: string | null;
          expires_on: string | null;
          reviewed_by: string;
          created_at: string;
        };
        Insert: {
          sequence: number;
          id?: string;
          record_id: string;
          revision: number;
          organization_id: string;
          field: string;
          status: string;
          evidence?: string;
          source_url?: string | null;
          document_id?: string | null;
          expires_on?: string | null;
          reviewed_by: string;
          created_at?: string;
        };
        Update: {
          sequence?: number;
          id?: string;
          record_id?: string;
          revision?: number;
          organization_id?: string;
          field?: string;
          status?: string;
          evidence?: string;
          source_url?: string | null;
          document_id?: string | null;
          expires_on?: string | null;
          reviewed_by?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      provider_listing_ownership: {
        Row: {
          entity_kind: string;
          entity_id: string;
          organization_id: string;
          request_id: string;
          assigned_by: string;
          assigned_at: string;
          revoked_at: string | null;
        };
        Insert: {
          entity_kind: string;
          entity_id: string;
          organization_id: string;
          request_id: string;
          assigned_by: string;
          assigned_at?: string;
          revoked_at?: string | null;
        };
        Update: {
          entity_kind?: string;
          entity_id?: string;
          organization_id?: string;
          request_id?: string;
          assigned_by?: string;
          assigned_at?: string;
          revoked_at?: string | null;
        };
        Relationships: [];
      };
      provider_records: {
        Row: {
          id: string;
          organization_id: string;
          kind: string;
          name: string;
          data: Json;
          revision: number;
          published_revision: number | null;
          status: string;
          canonical_id: string | null;
          created_by: string;
          updated_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          kind: string;
          name: string;
          data: Json;
          revision?: number;
          published_revision?: number | null;
          status?: string;
          canonical_id?: string | null;
          created_by: string;
          updated_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          kind?: string;
          name?: string;
          data?: Json;
          revision?: number;
          published_revision?: number | null;
          status?: string;
          canonical_id?: string | null;
          created_by?: string;
          updated_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      provider_reference_claims: {
        Row: {
          id: string;
          record_id: string;
          revision: number;
          organization_id: string;
          field: string;
          supported_value: Json;
          source_record_id: string;
          evidence_summary: string;
          created_by: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          record_id: string;
          revision: number;
          organization_id: string;
          field: string;
          supported_value: Json;
          source_record_id: string;
          evidence_summary: string;
          created_by: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          record_id?: string;
          revision?: number;
          organization_id?: string;
          field?: string;
          supported_value?: Json;
          source_record_id?: string;
          evidence_summary?: string;
          created_by?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      provider_revisions: {
        Row: {
          record_id: string;
          revision: number;
          organization_id: string;
          name: string;
          data: Json;
          created_by: string;
          created_at: string;
        };
        Insert: {
          record_id: string;
          revision: number;
          organization_id: string;
          name: string;
          data: Json;
          created_by: string;
          created_at?: string;
        };
        Update: {
          record_id?: string;
          revision?: number;
          organization_id?: string;
          name?: string;
          data?: Json;
          created_by?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      provider_section_reviews: {
        Row: {
          id: string;
          sequence: number;
          submission_id: string;
          record_id: string;
          revision: number;
          organization_id: string;
          status: string;
          comment: string;
          reason: string;
          document_id: string | null;
          reviewed_by: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          sequence: number;
          submission_id: string;
          record_id: string;
          revision: number;
          organization_id: string;
          status: string;
          comment?: string;
          reason?: string;
          document_id?: string | null;
          reviewed_by: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          sequence?: number;
          submission_id?: string;
          record_id?: string;
          revision?: number;
          organization_id?: string;
          status?: string;
          comment?: string;
          reason?: string;
          document_id?: string | null;
          reviewed_by?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      provider_submission_items: {
        Row: {
          submission_id: string;
          record_id: string;
          revision: number;
        };
        Insert: {
          submission_id: string;
          record_id: string;
          revision: number;
        };
        Update: {
          submission_id?: string;
          record_id?: string;
          revision?: number;
        };
        Relationships: [];
      };
      provider_submissions: {
        Row: {
          id: string;
          organization_id: string;
          status: string;
          submitted_by: string;
          reviewer_id: string | null;
          message: string;
          review_message: string;
          submitted_at: string;
          updated_at: string;
          requires_section_review: boolean;
        };
        Insert: {
          id?: string;
          organization_id: string;
          status?: string;
          submitted_by: string;
          reviewer_id?: string | null;
          message?: string;
          review_message?: string;
          submitted_at?: string;
          updated_at?: string;
          requires_section_review?: boolean;
        };
        Update: {
          id?: string;
          organization_id?: string;
          status?: string;
          submitted_by?: string;
          reviewer_id?: string | null;
          message?: string;
          review_message?: string;
          submitted_at?: string;
          updated_at?: string;
          requires_section_review?: boolean;
        };
        Relationships: [];
      };
      provider_verification_runs: {
        Row: {
          id: string;
          owner_id: string;
          conversation_id: string;
          provider_id: string;
          provider_type: string;
          completed_at: string;
          report: Json;
        };
        Insert: {
          id: string;
          owner_id: string;
          conversation_id: string;
          provider_id: string;
          provider_type: string;
          completed_at: string;
          report: Json;
        };
        Update: {
          id?: string;
          owner_id?: string;
          conversation_id?: string;
          provider_id?: string;
          provider_type?: string;
          completed_at?: string;
          report?: Json;
        };
        Relationships: [];
      };
      recent_searches: {
        Row: {
          id: string;
          owner_id: string;
          query: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          query: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          query?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      recovery_documents: {
        Row: {
          id: string;
          journey_id: string;
          owner_id: string;
          document_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          journey_id: string;
          owner_id: string;
          document_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          journey_id?: string;
          owner_id?: string;
          document_id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      recovery_events: {
        Row: {
          id: string;
          journey_id: string;
          owner_id: string;
          title: string;
          event_type: string;
          occurred_at: string;
          source: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          journey_id: string;
          owner_id: string;
          title: string;
          event_type: string;
          occurred_at?: string;
          source?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          journey_id?: string;
          owner_id?: string;
          title?: string;
          event_type?: string;
          occurred_at?: string;
          source?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      recovery_journeys: {
        Row: {
          id: string;
          owner_id: string;
          title: string;
          hospital_id: string | null;
          case_id: string | null;
          stage: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          title: string;
          hospital_id?: string | null;
          case_id?: string | null;
          stage?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          title?: string;
          hospital_id?: string | null;
          case_id?: string | null;
          stage?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      recovery_support_links: {
        Row: {
          id: string;
          journey_id: string;
          owner_id: string;
          support_case_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          journey_id: string;
          owner_id: string;
          support_case_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          journey_id?: string;
          owner_id?: string;
          support_case_id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      recovery_tasks: {
        Row: {
          id: string;
          journey_id: string;
          owner_id: string;
          title: string;
          status: string;
          due_at: string | null;
          source: string;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
          support_case_id: string | null;
          support_event_id: string | null;
        };
        Insert: {
          id?: string;
          journey_id: string;
          owner_id: string;
          title: string;
          status?: string;
          due_at?: string | null;
          source?: string;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
          support_case_id?: string | null;
          support_event_id?: string | null;
        };
        Update: {
          id?: string;
          journey_id?: string;
          owner_id?: string;
          title?: string;
          status?: string;
          due_at?: string | null;
          source?: string;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
          support_case_id?: string | null;
          support_event_id?: string | null;
        };
        Relationships: [];
      };
      saved_items: {
        Row: {
          id: string;
          owner_id: string;
          kind: string;
          hospital_id: string | null;
          doctor_id: string | null;
          package_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          kind: string;
          hospital_id?: string | null;
          doctor_id?: string | null;
          package_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          kind?: string;
          hospital_id?: string | null;
          doctor_id?: string | null;
          package_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      source_records: {
        Row: {
          id: string;
          source_kind: string;
          source_name: string;
          source_url: string | null;
          source_identifier: string | null;
          retrieved_at: string | null;
          effective_from: string | null;
          effective_until: string | null;
          extraction_method: string | null;
          verification_status: string;
          verified_at: string | null;
          verified_by: string | null;
          notes: string | null;
          created_at: string;
          source_type: string | null;
          review_after: string | null;
        };
        Insert: {
          id?: string;
          source_kind: string;
          source_name: string;
          source_url?: string | null;
          source_identifier?: string | null;
          retrieved_at?: string | null;
          effective_from?: string | null;
          effective_until?: string | null;
          extraction_method?: string | null;
          verification_status?: string;
          verified_at?: string | null;
          verified_by?: string | null;
          notes?: string | null;
          created_at?: string;
          source_type?: string | null;
          review_after?: string | null;
        };
        Update: {
          id?: string;
          source_kind?: string;
          source_name?: string;
          source_url?: string | null;
          source_identifier?: string | null;
          retrieved_at?: string | null;
          effective_from?: string | null;
          effective_until?: string | null;
          extraction_method?: string | null;
          verification_status?: string;
          verified_at?: string | null;
          verified_by?: string | null;
          notes?: string | null;
          created_at?: string;
          source_type?: string | null;
          review_after?: string | null;
        };
        Relationships: [];
      };
      specialties: {
        Row: {
          id: string;
          slug: string;
          name: string;
          aliases: string[];
          source_kind: string;
          created_at: string;
          updated_at: string;
          source_record_id: string | null;
          publication_status: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          aliases?: string[];
          source_kind?: string;
          created_at?: string;
          updated_at?: string;
          source_record_id?: string | null;
          publication_status?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          aliases?: string[];
          source_kind?: string;
          created_at?: string;
          updated_at?: string;
          source_record_id?: string | null;
          publication_status?: string;
        };
        Relationships: [];
      };
      staff_roles: {
        Row: {
          user_id: string;
          role: string;
          active: boolean;
          granted_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          role: string;
          active?: boolean;
          granted_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          role?: string;
          active?: boolean;
          granted_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      support_case_documents: {
        Row: {
          id: string;
          case_id: string;
          owner_id: string;
          request_id: string | null;
          replaces_id: string | null;
          filename: string;
          mime_type: string;
          size_bytes: number;
          checksum: string;
          status: string;
          uploaded_at: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          review_note: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          case_id: string;
          owner_id: string;
          request_id?: string | null;
          replaces_id?: string | null;
          filename: string;
          mime_type: string;
          size_bytes: number;
          checksum: string;
          status?: string;
          uploaded_at?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          review_note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          case_id?: string;
          owner_id?: string;
          request_id?: string | null;
          replaces_id?: string | null;
          filename?: string;
          mime_type?: string;
          size_bytes?: number;
          checksum?: string;
          status?: string;
          uploaded_at?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          review_note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      support_case_events: {
        Row: {
          id: string;
          case_id: string;
          actor_id: string;
          action: string;
          summary: string;
          visibility: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          case_id: string;
          actor_id: string;
          action: string;
          summary: string;
          visibility: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          case_id?: string;
          actor_id?: string;
          action?: string;
          summary?: string;
          visibility?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      support_case_messages: {
        Row: {
          id: string;
          case_id: string;
          actor_id: string;
          body: string;
          visibility: string;
          created_at: string;
          sender_role: string | null;
          sender_organization_id: string | null;
        };
        Insert: {
          id?: string;
          case_id: string;
          actor_id: string;
          body: string;
          visibility: string;
          created_at?: string;
          sender_role?: string | null;
          sender_organization_id?: string | null;
        };
        Update: {
          id?: string;
          case_id?: string;
          actor_id?: string;
          body?: string;
          visibility?: string;
          created_at?: string;
          sender_role?: string | null;
          sender_organization_id?: string | null;
        };
        Relationships: [];
      };
      support_case_provider_consents: {
        Row: {
          id: string;
          case_id: string;
          owner_id: string;
          organization_id: string;
          purpose: string;
          granted_at: string;
          revoked_at: string | null;
        };
        Insert: {
          id?: string;
          case_id: string;
          owner_id: string;
          organization_id: string;
          purpose: string;
          granted_at?: string;
          revoked_at?: string | null;
        };
        Update: {
          id?: string;
          case_id?: string;
          owner_id?: string;
          organization_id?: string;
          purpose?: string;
          granted_at?: string;
          revoked_at?: string | null;
        };
        Relationships: [];
      };
      support_cases: {
        Row: {
          id: string;
          patient_id: string;
          organization_id: string | null;
          source_case_id: string | null;
          conversation_id: string | null;
          document_workspace_id: string | null;
          title: string;
          description: string;
          case_type: string;
          status: string;
          priority: string;
          assigned_to: string | null;
          due_at: string | null;
          escalation_reason: string | null;
          share_conversation: boolean;
          share_documents: boolean;
          share_with_provider: boolean;
          consent_granted_at: string;
          consent_revoked_at: string | null;
          revision: number;
          created_at: string;
          updated_at: string;
          hospital_id: string | null;
          doctor_id: string | null;
          package_id: string | null;
          inquiry_source: string;
          entity_snapshot: Json;
          resolution_summary: string | null;
          provider_response_status: string;
          provider_responded_by: string | null;
          provider_responded_at: string | null;
          recovery_journey_id: string | null;
          provider_response_message_id: string | null;
          provider_information_requested_at: string | null;
          provider_information_answered_at: string | null;
        };
        Insert: {
          id?: string;
          patient_id: string;
          organization_id?: string | null;
          source_case_id?: string | null;
          conversation_id?: string | null;
          document_workspace_id?: string | null;
          title: string;
          description?: string;
          case_type?: string;
          status?: string;
          priority?: string;
          assigned_to?: string | null;
          due_at?: string | null;
          escalation_reason?: string | null;
          share_conversation?: boolean;
          share_documents?: boolean;
          share_with_provider?: boolean;
          consent_granted_at: string;
          consent_revoked_at?: string | null;
          revision?: number;
          created_at?: string;
          updated_at?: string;
          hospital_id?: string | null;
          doctor_id?: string | null;
          package_id?: string | null;
          inquiry_source?: string;
          entity_snapshot?: Json;
          resolution_summary?: string | null;
          provider_response_status?: string;
          provider_responded_by?: string | null;
          provider_responded_at?: string | null;
          recovery_journey_id?: string | null;
          provider_response_message_id?: string | null;
          provider_information_requested_at?: string | null;
          provider_information_answered_at?: string | null;
        };
        Update: {
          id?: string;
          patient_id?: string;
          organization_id?: string | null;
          source_case_id?: string | null;
          conversation_id?: string | null;
          document_workspace_id?: string | null;
          title?: string;
          description?: string;
          case_type?: string;
          status?: string;
          priority?: string;
          assigned_to?: string | null;
          due_at?: string | null;
          escalation_reason?: string | null;
          share_conversation?: boolean;
          share_documents?: boolean;
          share_with_provider?: boolean;
          consent_granted_at?: string;
          consent_revoked_at?: string | null;
          revision?: number;
          created_at?: string;
          updated_at?: string;
          hospital_id?: string | null;
          doctor_id?: string | null;
          package_id?: string | null;
          inquiry_source?: string;
          entity_snapshot?: Json;
          resolution_summary?: string | null;
          provider_response_status?: string;
          provider_responded_by?: string | null;
          provider_responded_at?: string | null;
          recovery_journey_id?: string | null;
          provider_response_message_id?: string | null;
          provider_information_requested_at?: string | null;
          provider_information_answered_at?: string | null;
        };
        Relationships: [];
      };
      support_document_grants: {
        Row: {
          id: string;
          document_id: string;
          case_id: string;
          owner_id: string;
          recipient: string;
          organization_id: string | null;
          purpose: string;
          granted_at: string;
          revoked_at: string | null;
        };
        Insert: {
          id?: string;
          document_id: string;
          case_id: string;
          owner_id: string;
          recipient: string;
          organization_id?: string | null;
          purpose: string;
          granted_at?: string;
          revoked_at?: string | null;
        };
        Update: {
          id?: string;
          document_id?: string;
          case_id?: string;
          owner_id?: string;
          recipient?: string;
          organization_id?: string | null;
          purpose?: string;
          granted_at?: string;
          revoked_at?: string | null;
        };
        Relationships: [];
      };
      support_document_requests: {
        Row: {
          id: string;
          case_id: string;
          requested_by: string;
          requesting_party: string;
          title: string;
          purpose: string;
          visibility: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          case_id: string;
          requested_by: string;
          requesting_party: string;
          title: string;
          purpose: string;
          visibility: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          case_id?: string;
          requested_by?: string;
          requesting_party?: string;
          title?: string;
          purpose?: string;
          visibility?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      support_message_reads: {
        Row: {
          case_id: string;
          user_id: string;
          read_at: string;
        };
        Insert: {
          case_id: string;
          user_id: string;
          read_at?: string;
        };
        Update: {
          case_id?: string;
          user_id?: string;
          read_at?: string;
        };
        Relationships: [];
      };
      support_operation_receipts: {
        Row: {
          actor_id: string;
          operation_id: string;
          action: string;
          input_hash: string;
          case_id: string;
          result: Json;
          created_at: string;
        };
        Insert: {
          actor_id: string;
          operation_id: string;
          action: string;
          input_hash: string;
          case_id: string;
          result: Json;
          created_at?: string;
        };
        Update: {
          actor_id?: string;
          operation_id?: string;
          action?: string;
          input_hash?: string;
          case_id?: string;
          result?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      support_tasks: {
        Row: {
          id: string;
          case_id: string;
          title: string;
          assigned_to: string | null;
          due_at: string | null;
          priority: string;
          status: string;
          created_by: string;
          revision: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          case_id: string;
          title: string;
          assigned_to?: string | null;
          due_at?: string | null;
          priority?: string;
          status?: string;
          created_by: string;
          revision?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          case_id?: string;
          title?: string;
          assigned_to?: string | null;
          due_at?: string | null;
          priority?: string;
          status?: string;
          created_by?: string;
          revision?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      treatment_conditions: {
        Row: {
          treatment_id: string;
          condition_id: string;
        };
        Insert: {
          treatment_id: string;
          condition_id: string;
        };
        Update: {
          treatment_id?: string;
          condition_id?: string;
        };
        Relationships: [];
      };
      treatment_countries: {
        Row: {
          treatment_id: string;
          country_id: string;
          source_record_id: string;
        };
        Insert: {
          treatment_id: string;
          country_id: string;
          source_record_id: string;
        };
        Update: {
          treatment_id?: string;
          country_id?: string;
          source_record_id?: string;
        };
        Relationships: [];
      };
      treatments: {
        Row: {
          id: string;
          slug: string;
          name: string;
          specialty_id: string;
          category: string;
          description: string;
          aliases: string[];
          overview: string;
          procedure_summary: string;
          indications: string;
          diagnostics: string;
          recovery: string;
          typical_stay_days: number | null;
          faqs: Json;
          source_kind: string;
          publication_status: string;
          source_record_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          specialty_id: string;
          category: string;
          description: string;
          aliases?: string[];
          overview: string;
          procedure_summary: string;
          indications: string;
          diagnostics: string;
          recovery: string;
          typical_stay_days?: number | null;
          faqs?: Json;
          source_kind: string;
          publication_status?: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          specialty_id?: string;
          category?: string;
          description?: string;
          aliases?: string[];
          overview?: string;
          procedure_summary?: string;
          indications?: string;
          diagnostics?: string;
          recovery?: string;
          typical_stay_days?: number | null;
          faqs?: Json;
          source_kind?: string;
          publication_status?: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      workflow_runs: {
        Row: {
          id: string;
          workflow_id: string;
          case_id: string | null;
          status: string;
          idempotency_key: string | null;
          started_at: string | null;
          finished_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workflow_id: string;
          case_id?: string | null;
          status: string;
          idempotency_key?: string | null;
          started_at?: string | null;
          finished_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workflow_id?: string;
          case_id?: string | null;
          status?: string;
          idempotency_key?: string | null;
          started_at?: string | null;
          finished_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      workflow_steps: {
        Row: {
          id: string;
          workflow_run_id: string;
          step_key: string;
          position: number;
          status: string;
          owner_id: string | null;
          due_at: string | null;
          started_at: string | null;
          finished_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workflow_run_id: string;
          step_key: string;
          position: number;
          status: string;
          owner_id?: string | null;
          due_at?: string | null;
          started_at?: string | null;
          finished_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workflow_run_id?: string;
          step_key?: string;
          position?: number;
          status?: string;
          owner_id?: string | null;
          due_at?: string | null;
          started_at?: string | null;
          finished_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      workflows: {
        Row: {
          id: string;
          slug: string;
          name: string;
          version: number;
          status: string;
          definition: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          version?: number;
          status?: string;
          definition?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          version?: number;
          status?: string;
          definition?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      operations_overview: { Args: Record<string, never>; Returns: Json };
      operations_inquiries: { Args: { p_filter?: string }; Returns: Json };
      operations_probe: { Args: Record<string, never>; Returns: Json };
      operations_command: { Args: { p_action: string; p_input: Json }; Returns: Json };
      operations_record_health: { Args: { p_actor: string; p_operation: string; p_result: Json }; Returns: Json };
      operations_record_request: { Args: { p_actor: string; p_metadata: Json }; Returns: undefined };
      inquiry_command: { Args: { p_action: string; p_input: Json }; Returns: Json };
      public_catalog_snapshot: { Args: Record<string, never>; Returns: Json };
      inquiry_context: { Args: { p_case_id: string }; Returns: Json };
      inquiry_target: { Args: { p_kind: string; p_id: string }; Returns: Json };
      inquiry_document_delivery: { Args: { p_document_id: string }; Returns: Json };
      inquiry_commit_upload: { Args: { p_actor: string; p_document: string }; Returns: Json };
      experience_command: { Args: { p_action: string; p_input?: Json }; Returns: Json };
      experience_guest_session: { Args: { p_action: string; p_hash: string; p_ip_hash?: string | null; p_lease?: string | null; p_state?: Json | null }; Returns: Json };
      experience_import_visitor: { Args: { p_hash: string; p_lease: string; p_user: string }; Returns: string };
      experience_rate_cache: { Args: { p_snapshot?: Json | null }; Returns: Json };
      search_catalog_candidates: {
        Args: { p_terms: string; p_treatment_slug?: string | null; p_specialty?: string | null; p_countries?: string[]; p_city?: string | null };
        Returns: { kind: string; slug: string }[];
      };
      acquire_assistant_turn: { Args: { p_conversation_id: string; p_user_id: string; p_token: string }; Returns: boolean };
      release_assistant_turn: { Args: { p_conversation_id: string; p_token: string }; Returns: undefined };
      save_care_plan: { Args: { p_plan: Json; p_token: string }; Returns: undefined };
      save_document_workspace: { Args: { p_workspace: Json; p_expected_revision: number; p_action: string }; Returns: undefined };
      portal_network_readiness: { Args: { p_organization_id?: string | null }; Returns: Json };
      portal_network_command: { Args: { p_action: string; p_input: Json }; Returns: Json };
      portal_context: { Args: Record<string, never>; Returns: Json };
      portal_touch_activity: { Args: Record<string, never>; Returns: undefined };
      portal_account_active: { Args: Record<string, never>; Returns: boolean };
      portal_command: { Args: { p_action: string; p_input?: Json }; Returns: Json };
      portal_review_command: { Args: { p_action: string; p_input: Json }; Returns: Json };
      portal_listing_status: { Args: { p_organization_id: string }; Returns: Json };
      portal_submission_summary: { Args: { p_submission_id: string }; Returns: Json };
      public_provider_hospital_details: { Args: Record<string, never>; Returns: Json };
      support_command: { Args: { p_action: string; p_input?: Json }; Returns: Json };
      portal_publication_command: { Args: { p_action: string; p_input: Json }; Returns: Json };
      portal_catalog_command: { Args: { p_action: string; p_input: Json }; Returns: Json };
      portal_reference_command: { Args: { p_action: string; p_input: Json }; Returns: Json };
      public_reference_claims: { Args: { p_kind: string; p_id: string }; Returns: Json };
      public_reference_locations: { Args: Record<string, never>; Returns: Json };
      portal_case_context: { Args: { p_case_id: string }; Returns: Json };
      portal_users: { Args: { p_search?: string }; Returns: Json };
      portal_analytics: { Args: Record<string, never>; Returns: Json };
      public_provider_profile: { Args: { p_hospital_id: string }; Returns: Json };
      public_provider_image: { Args: { p_doctor_id: string }; Returns: Json };
      public_provider_record: { Args: { p_kind: string; p_id: string }; Returns: Json };
      public_provider_package_details: { Args: Record<string, never>; Returns: Json };
      public_package_evidence: { Args: { p_id: string }; Returns: Json };
      public_catalog_provenance: { Args: Record<string, never>; Returns: Json };
      portal_team: { Args: { p_organization_id: string }; Returns: Json };
      portal_staff_directory: { Args: Record<string, never>; Returns: Json };
      record_portal_verification: { Args: { p_actor: string; p_organization_id: string; p_provider_id: string; p_report: Json }; Returns: string };
      bootstrap_portal_super_admin: { Args: { p_email: string }; Returns: string };
    };
    Enums: {
      case_lifecycle_status: "draft" | "intake" | "planning" | "awaiting_patient" | "awaiting_provider" | "in_progress" | "completed" | "cancelled";
      provider_verification_status: "draft" | "pending_verification" | "verified" | "suspended" | "archived";
    };
    CompositeTypes: Record<string, never>;
  };
};
