// Generated from the migrated PostgreSQL schema by scripts/generate-db-types.mjs.
// Regenerate after changing migrations; do not edit this file by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      agent_actions: {
        Row: {
          id: string;
          run_id: string;
          task_id: string | null;
          action_name: string;
          tool_name: string | null;
          tool_version: string | null;
          status: string;
          input_hash: string | null;
          output_hash: string | null;
          requires_approval: boolean;
          performed_at: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          run_id: string;
          task_id?: string | null;
          action_name: string;
          tool_name?: string | null;
          tool_version?: string | null;
          status: string;
          input_hash?: string | null;
          output_hash?: string | null;
          requires_approval?: boolean;
          performed_at?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          run_id?: string;
          task_id?: string | null;
          action_name?: string;
          tool_name?: string | null;
          tool_version?: string | null;
          status?: string;
          input_hash?: string | null;
          output_hash?: string | null;
          requires_approval?: boolean;
          performed_at?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      agent_approvals: {
        Row: {
          id: string;
          action_id: string;
          requested_by: string | null;
          reviewer_id: string | null;
          decision: string;
          reason: string | null;
          decided_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          action_id: string;
          requested_by?: string | null;
          reviewer_id?: string | null;
          decision?: string;
          reason?: string | null;
          decided_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          action_id?: string;
          requested_by?: string | null;
          reviewer_id?: string | null;
          decision?: string;
          reason?: string | null;
          decided_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      agent_outputs: {
        Row: {
          id: string;
          run_id: string;
          task_id: string | null;
          output_type: string;
          content: Json;
          source_record_ids: string[];
          review_status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          run_id: string;
          task_id?: string | null;
          output_type: string;
          content: Json;
          source_record_ids?: string[];
          review_status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          run_id?: string;
          task_id?: string | null;
          output_type?: string;
          content?: Json;
          source_record_ids?: string[];
          review_status?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      agent_runs: {
        Row: {
          id: string;
          case_id: string | null;
          agent_name: string;
          agent_version: string;
          initiated_by: string | null;
          purpose: string;
          status: string;
          started_at: string | null;
          finished_at: string | null;
          trace_id: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
          conversation_id: string | null;
          care_plan_id: string | null;
        };
        Insert: {
          id?: string;
          case_id?: string | null;
          agent_name: string;
          agent_version: string;
          initiated_by?: string | null;
          purpose: string;
          status: string;
          started_at?: string | null;
          finished_at?: string | null;
          trace_id?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
          conversation_id?: string | null;
          care_plan_id?: string | null;
        };
        Update: {
          id?: string;
          case_id?: string | null;
          agent_name?: string;
          agent_version?: string;
          initiated_by?: string | null;
          purpose?: string;
          status?: string;
          started_at?: string | null;
          finished_at?: string | null;
          trace_id?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
          conversation_id?: string | null;
          care_plan_id?: string | null;
        };
        Relationships: [];
      };
      agent_tasks: {
        Row: {
          id: string;
          run_id: string;
          case_id: string | null;
          task_type: string;
          status: string;
          objective: string;
          due_at: string | null;
          created_at: string;
          updated_at: string;
          tool_name: string | null;
          input_summary: Json;
          output_summary: Json;
          started_at: string | null;
          completed_at: string | null;
          error_code: string | null;
          care_plan_task_id: string | null;
        };
        Insert: {
          id?: string;
          run_id: string;
          case_id?: string | null;
          task_type: string;
          status: string;
          objective: string;
          due_at?: string | null;
          created_at?: string;
          updated_at?: string;
          tool_name?: string | null;
          input_summary?: Json;
          output_summary?: Json;
          started_at?: string | null;
          completed_at?: string | null;
          error_code?: string | null;
          care_plan_task_id?: string | null;
        };
        Update: {
          id?: string;
          run_id?: string;
          case_id?: string | null;
          task_type?: string;
          status?: string;
          objective?: string;
          due_at?: string | null;
          created_at?: string;
          updated_at?: string;
          tool_name?: string | null;
          input_summary?: Json;
          output_summary?: Json;
          started_at?: string | null;
          completed_at?: string | null;
          error_code?: string | null;
          care_plan_task_id?: string | null;
        };
        Relationships: [];
      };
      audit_events: {
        Row: {
          id: string;
          actor_id: string | null;
          actor_type: string;
          event_name: string;
          entity_type: string;
          entity_id: string | null;
          case_id: string | null;
          occurred_at: string;
          metadata: Json;
        };
        Insert: {
          id?: string;
          actor_id?: string | null;
          actor_type: string;
          event_name: string;
          entity_type: string;
          entity_id?: string | null;
          case_id?: string | null;
          occurred_at?: string;
          metadata?: Json;
        };
        Update: {
          id?: string;
          actor_id?: string | null;
          actor_type?: string;
          event_name?: string;
          entity_type?: string;
          entity_id?: string | null;
          case_id?: string | null;
          occurred_at?: string;
          metadata?: Json;
        };
        Relationships: [];
      };
      care_plan_tasks: {
        Row: {
          id: string;
          care_plan_id: string;
          task_key: string;
          title: string;
          description: string;
          task_type: string;
          status: string;
          priority: string;
          requires_user_action: boolean;
          requires_approval: boolean;
          approval_status: string;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          care_plan_id: string;
          task_key: string;
          title: string;
          description?: string;
          task_type: string;
          status?: string;
          priority?: string;
          requires_user_action?: boolean;
          requires_approval?: boolean;
          approval_status?: string;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          care_plan_id?: string;
          task_key?: string;
          title?: string;
          description?: string;
          task_type?: string;
          status?: string;
          priority?: string;
          requires_user_action?: boolean;
          requires_approval?: boolean;
          approval_status?: string;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      care_plans: {
        Row: {
          id: string;
          user_id: string;
          conversation_id: string;
          title: string;
          goal: string;
          status: string;
          destination_country: string | null;
          destination_city: string | null;
          treatment_id: string | null;
          context: Json;
          findings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          conversation_id: string;
          title: string;
          goal: string;
          status?: string;
          destination_country?: string | null;
          destination_city?: string | null;
          treatment_id?: string | null;
          context?: Json;
          findings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          conversation_id?: string;
          title?: string;
          goal?: string;
          status?: string;
          destination_country?: string | null;
          destination_city?: string | null;
          treatment_id?: string | null;
          context?: Json;
          findings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      case_documents: {
        Row: {
          id: string;
          case_id: string;
          uploaded_by: string;
          document_type: string;
          title: string;
          storage_path: string;
          mime_type: string;
          file_size_bytes: number;
          status: string;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          case_id: string;
          uploaded_by: string;
          document_type: string;
          title: string;
          storage_path: string;
          mime_type: string;
          file_size_bytes: number;
          status?: string;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          case_id?: string;
          uploaded_by?: string;
          document_type?: string;
          title?: string;
          storage_path?: string;
          mime_type?: string;
          file_size_bytes?: number;
          status?: string;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      case_members: {
        Row: {
          case_id: string;
          user_id: string;
          role: string;
          granted_by: string;
          granted_at: string;
          revoked_at: string | null;
        };
        Insert: {
          case_id: string;
          user_id: string;
          role: string;
          granted_by: string;
          granted_at?: string;
          revoked_at?: string | null;
        };
        Update: {
          case_id?: string;
          user_id?: string;
          role?: string;
          granted_by?: string;
          granted_at?: string;
          revoked_at?: string | null;
        };
        Relationships: [];
      };
      case_status_history: {
        Row: {
          id: string;
          case_id: string;
          from_status: Database["public"]["Enums"]["case_lifecycle_status"] | null;
          to_status: Database["public"]["Enums"]["case_lifecycle_status"];
          changed_by: string | null;
          changed_at: string;
          note: string | null;
        };
        Insert: {
          id?: string;
          case_id: string;
          from_status?: Database["public"]["Enums"]["case_lifecycle_status"] | null;
          to_status: Database["public"]["Enums"]["case_lifecycle_status"];
          changed_by?: string | null;
          changed_at?: string;
          note?: string | null;
        };
        Update: {
          id?: string;
          case_id?: string;
          from_status?: Database["public"]["Enums"]["case_lifecycle_status"] | null;
          to_status?: Database["public"]["Enums"]["case_lifecycle_status"];
          changed_by?: string | null;
          changed_at?: string;
          note?: string | null;
        };
        Relationships: [];
      };
      cases: {
        Row: {
          id: string;
          owner_id: string;
          status: Database["public"]["Enums"]["case_lifecycle_status"];
          title: string;
          description: string | null;
          preferred_country_id: string | null;
          preferred_city_id: string | null;
          preferred_treatment_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          status?: Database["public"]["Enums"]["case_lifecycle_status"];
          title: string;
          description?: string | null;
          preferred_country_id?: string | null;
          preferred_city_id?: string | null;
          preferred_treatment_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          status?: Database["public"]["Enums"]["case_lifecycle_status"];
          title?: string;
          description?: string | null;
          preferred_country_id?: string | null;
          preferred_city_id?: string | null;
          preferred_treatment_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      cities: {
        Row: {
          id: string;
          country_id: string;
          slug: string;
          name: string;
          aliases: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          country_id: string;
          slug: string;
          name: string;
          aliases?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          country_id?: string;
          slug?: string;
          name?: string;
          aliases?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      conditions: {
        Row: {
          id: string;
          slug: string;
          name: string;
          aliases: string[];
          source_kind: string;
          created_at: string;
          updated_at: string;
          source_record_id: string | null;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          aliases?: string[];
          source_kind: string;
          created_at?: string;
          updated_at?: string;
          source_record_id?: string | null;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          aliases?: string[];
          source_kind?: string;
          created_at?: string;
          updated_at?: string;
          source_record_id?: string | null;
        };
        Relationships: [];
      };
      consents: {
        Row: {
          id: string;
          subject_id: string;
          case_id: string | null;
          consent_type: string;
          purpose: string;
          decision: string;
          granted_at: string | null;
          revoked_at: string | null;
          version: string;
          source: string;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          subject_id: string;
          case_id?: string | null;
          consent_type: string;
          purpose: string;
          decision: string;
          granted_at?: string | null;
          revoked_at?: string | null;
          version: string;
          source: string;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          subject_id?: string;
          case_id?: string | null;
          consent_type?: string;
          purpose?: string;
          decision?: string;
          granted_at?: string | null;
          revoked_at?: string | null;
          version?: string;
          source?: string;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      conversation_messages: {
        Row: {
          id: string;
          conversation_id: string;
          run_id: string | null;
          role: string;
          visibility: string;
          content: string;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          run_id?: string | null;
          role: string;
          visibility?: string;
          content: string;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          run_id?: string | null;
          role?: string;
          visibility?: string;
          content?: string;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      conversations: {
        Row: {
          id: string;
          owner_id: string;
          case_id: string | null;
          title: string;
          status: string;
          created_at: string;
          updated_at: string;
          execution_token: string | null;
          execution_expires_at: string | null;
        };
        Insert: {
          id?: string;
          owner_id: string;
          case_id?: string | null;
          title?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
          execution_token?: string | null;
          execution_expires_at?: string | null;
        };
        Update: {
          id?: string;
          owner_id?: string;
          case_id?: string | null;
          title?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
          execution_token?: string | null;
          execution_expires_at?: string | null;
        };
        Relationships: [];
      };
      countries: {
        Row: {
          id: string;
          slug: string;
          iso_code: string;
          name: string;
          description: string;
          aliases: string[];
          travel_note: string;
          source_kind: string;
          publication_status: string;
          created_at: string;
          updated_at: string;
          source_record_id: string | null;
        };
        Insert: {
          id?: string;
          slug: string;
          iso_code: string;
          name: string;
          description?: string;
          aliases?: string[];
          travel_note?: string;
          source_kind: string;
          publication_status?: string;
          created_at?: string;
          updated_at?: string;
          source_record_id?: string | null;
        };
        Update: {
          id?: string;
          slug?: string;
          iso_code?: string;
          name?: string;
          description?: string;
          aliases?: string[];
          travel_note?: string;
          source_kind?: string;
          publication_status?: string;
          created_at?: string;
          updated_at?: string;
          source_record_id?: string | null;
        };
        Relationships: [];
      };
      doctor_specialties: {
        Row: {
          doctor_id: string;
          specialty_id: string;
          is_primary: boolean;
        };
        Insert: {
          doctor_id: string;
          specialty_id: string;
          is_primary?: boolean;
        };
        Update: {
          doctor_id?: string;
          specialty_id?: string;
          is_primary?: boolean;
        };
        Relationships: [];
      };
      doctor_treatments: {
        Row: {
          doctor_id: string;
          treatment_id: string;
        };
        Insert: {
          doctor_id: string;
          treatment_id: string;
        };
        Update: {
          doctor_id?: string;
          treatment_id?: string;
        };
        Relationships: [];
      };
      doctors: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string;
          aliases: string[];
          home_city_id: string | null;
          experience_years: number | null;
          languages: string[];
          consultation_mode: string;
          qualifications_note: string;
          verification_status: Database["public"]["Enums"]["provider_verification_status"];
          verification_source: string | null;
          verification_date: string | null;
          last_verified_at: string | null;
          verified_by: string | null;
          source_kind: string;
          publication_status: string;
          source_record_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description: string;
          aliases?: string[];
          home_city_id?: string | null;
          experience_years?: number | null;
          languages?: string[];
          consultation_mode: string;
          qualifications_note?: string;
          verification_status?: Database["public"]["Enums"]["provider_verification_status"];
          verification_source?: string | null;
          verification_date?: string | null;
          last_verified_at?: string | null;
          verified_by?: string | null;
          source_kind: string;
          publication_status?: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string;
          aliases?: string[];
          home_city_id?: string | null;
          experience_years?: number | null;
          languages?: string[];
          consultation_mode?: string;
          qualifications_note?: string;
          verification_status?: Database["public"]["Enums"]["provider_verification_status"];
          verification_source?: string | null;
          verification_date?: string | null;
          last_verified_at?: string | null;
          verified_by?: string | null;
          source_kind?: string;
          publication_status?: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      document_checklists: {
        Row: {
          id: string;
          hospital_id: string;
          service_id: string | null;
          service_label: string | null;
          source_kind: string;
          source_label: string;
          source_reference: string | null;
          requirements: Json;
          published: boolean;
          updated_at: string;
        };
        Insert: {
          id?: string;
          hospital_id: string;
          service_id?: string | null;
          service_label?: string | null;
          source_kind: string;
          source_label: string;
          source_reference?: string | null;
          requirements: Json;
          published?: boolean;
          updated_at?: string;
        };
        Update: {
          id?: string;
          hospital_id?: string;
          service_id?: string | null;
          service_label?: string | null;
          source_kind?: string;
          source_label?: string;
          source_reference?: string | null;
          requirements?: Json;
          published?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      document_coordination_audit: {
        Row: {
          id: string;
          workspace_id: string;
          owner_id: string;
          revision: number;
          action: string;
          snapshot: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          owner_id: string;
          revision: number;
          action: string;
          snapshot: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          owner_id?: string;
          revision?: number;
          action?: string;
          snapshot?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      document_workspaces: {
        Row: {
          id: string;
          owner_id: string;
          conversation_id: string;
          hospital_id: string;
          service_id: string | null;
          service_label: string;
          revision: number;
          data: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          owner_id: string;
          conversation_id: string;
          hospital_id: string;
          service_id?: string | null;
          service_label: string;
          revision: number;
          data: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          conversation_id?: string;
          hospital_id?: string;
          service_id?: string | null;
          service_label?: string;
          revision?: number;
          data?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      healthcare_services: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string;
          aliases: string[];
          href: string;
          category: string;
          steps: string[];
          status: string;
          source_kind: string;
          created_at: string;
          updated_at: string;
          source_record_id: string | null;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description: string;
          aliases?: string[];
          href: string;
          category: string;
          steps?: string[];
          status?: string;
          source_kind: string;
          created_at?: string;
          updated_at?: string;
          source_record_id?: string | null;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string;
          aliases?: string[];
          href?: string;
          category?: string;
          steps?: string[];
          status?: string;
          source_kind?: string;
          created_at?: string;
          updated_at?: string;
          source_record_id?: string | null;
        };
        Relationships: [];
      };
      hospital_doctors: {
        Row: {
          hospital_id: string;
          doctor_id: string;
          is_primary: boolean;
          starts_on: string | null;
          ends_on: string | null;
          source_record_id: string;
        };
        Insert: {
          hospital_id: string;
          doctor_id: string;
          is_primary?: boolean;
          starts_on?: string | null;
          ends_on?: string | null;
          source_record_id: string;
        };
        Update: {
          hospital_id?: string;
          doctor_id?: string;
          is_primary?: boolean;
          starts_on?: string | null;
          ends_on?: string | null;
          source_record_id?: string;
        };
        Relationships: [];
      };
      hospital_specialties: {
        Row: {
          hospital_id: string;
          specialty_id: string;
        };
        Insert: {
          hospital_id: string;
          specialty_id: string;
        };
        Update: {
          hospital_id?: string;
          specialty_id?: string;
        };
        Relationships: [];
      };
      hospital_treatments: {
        Row: {
          hospital_id: string;
          treatment_id: string;
          source_record_id: string;
        };
        Insert: {
          hospital_id: string;
          treatment_id: string;
          source_record_id: string;
        };
        Update: {
          hospital_id?: string;
          treatment_id?: string;
          source_record_id?: string;
        };
        Relationships: [];
      };
      hospitals: {
        Row: {
          id: string;
          slug: string;
          name: string;
          city_id: string;
          description: string;
          aliases: string[];
          bed_count: number | null;
          accreditation_note: string | null;
          infrastructure: string[];
          verification_status: Database["public"]["Enums"]["provider_verification_status"];
          verification_source: string | null;
          verification_date: string | null;
          last_verified_at: string | null;
          verified_by: string | null;
          source_kind: string;
          publication_status: string;
          source_record_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          city_id: string;
          description: string;
          aliases?: string[];
          bed_count?: number | null;
          accreditation_note?: string | null;
          infrastructure?: string[];
          verification_status?: Database["public"]["Enums"]["provider_verification_status"];
          verification_source?: string | null;
          verification_date?: string | null;
          last_verified_at?: string | null;
          verified_by?: string | null;
          source_kind: string;
          publication_status?: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          city_id?: string;
          description?: string;
          aliases?: string[];
          bed_count?: number | null;
          accreditation_note?: string | null;
          infrastructure?: string[];
          verification_status?: Database["public"]["Enums"]["provider_verification_status"];
          verification_source?: string | null;
          verification_date?: string | null;
          last_verified_at?: string | null;
          verified_by?: string | null;
          source_kind?: string;
          publication_status?: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      package_exclusions: {
        Row: {
          package_id: string;
          position: number;
          description: string;
        };
        Insert: {
          package_id: string;
          position: number;
          description: string;
        };
        Update: {
          package_id?: string;
          position?: number;
          description?: string;
        };
        Relationships: [];
      };
      package_inclusions: {
        Row: {
          package_id: string;
          position: number;
          description: string;
        };
        Insert: {
          package_id: string;
          position: number;
          description: string;
        };
        Update: {
          package_id?: string;
          position?: number;
          description?: string;
        };
        Relationships: [];
      };
      packages: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string;
          aliases: string[];
          treatment_id: string;
          hospital_id: string | null;
          country_id: string;
          duration_days: number;
          currency: string;
          estimated_min: number;
          estimated_max: number;
          price_type: string;
          benefits: string[];
          status: string;
          valid_from: string | null;
          valid_until: string | null;
          source_kind: string;
          source_record_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description: string;
          aliases?: string[];
          treatment_id: string;
          hospital_id?: string | null;
          country_id: string;
          duration_days: number;
          currency: string;
          estimated_min: number;
          estimated_max: number;
          price_type: string;
          benefits?: string[];
          status?: string;
          valid_from?: string | null;
          valid_until?: string | null;
          source_kind: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string;
          aliases?: string[];
          treatment_id?: string;
          hospital_id?: string | null;
          country_id?: string;
          duration_days?: number;
          currency?: string;
          estimated_min?: number;
          estimated_max?: number;
          price_type?: string;
          benefits?: string[];
          status?: string;
          valid_from?: string | null;
          valid_until?: string | null;
          source_kind?: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      price_estimates: {
        Row: {
          id: string;
          treatment_id: string;
          country_id: string;
          hospital_id: string | null;
          package_id: string | null;
          currency: string;
          estimated_min: number;
          estimated_max: number;
          pricing_type: string;
          effective_from: string | null;
          expires_on: string | null;
          verification_status: string;
          publication_status: string;
          source_kind: string;
          source_record_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          treatment_id: string;
          country_id: string;
          hospital_id?: string | null;
          package_id?: string | null;
          currency: string;
          estimated_min: number;
          estimated_max: number;
          pricing_type: string;
          effective_from?: string | null;
          expires_on?: string | null;
          verification_status?: string;
          publication_status?: string;
          source_kind: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          treatment_id?: string;
          country_id?: string;
          hospital_id?: string | null;
          package_id?: string | null;
          currency?: string;
          estimated_min?: number;
          estimated_max?: number;
          pricing_type?: string;
          effective_from?: string | null;
          expires_on?: string | null;
          verification_status?: string;
          publication_status?: string;
          source_kind?: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          locale: string | null;
          timezone: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          locale?: string | null;
          timezone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string | null;
          locale?: string | null;
          timezone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      source_records: {
        Row: {
          id: string;
          source_kind: string;
          source_name: string;
          source_url: string | null;
          source_identifier: string | null;
          retrieved_at: string | null;
          effective_from: string | null;
          effective_until: string | null;
          extraction_method: string | null;
          verification_status: string;
          verified_at: string | null;
          verified_by: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          source_kind: string;
          source_name: string;
          source_url?: string | null;
          source_identifier?: string | null;
          retrieved_at?: string | null;
          effective_from?: string | null;
          effective_until?: string | null;
          extraction_method?: string | null;
          verification_status?: string;
          verified_at?: string | null;
          verified_by?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          source_kind?: string;
          source_name?: string;
          source_url?: string | null;
          source_identifier?: string | null;
          retrieved_at?: string | null;
          effective_from?: string | null;
          effective_until?: string | null;
          extraction_method?: string | null;
          verification_status?: string;
          verified_at?: string | null;
          verified_by?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      specialties: {
        Row: {
          id: string;
          slug: string;
          name: string;
          aliases: string[];
          source_kind: string;
          created_at: string;
          updated_at: string;
          source_record_id: string | null;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          aliases?: string[];
          source_kind?: string;
          created_at?: string;
          updated_at?: string;
          source_record_id?: string | null;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          aliases?: string[];
          source_kind?: string;
          created_at?: string;
          updated_at?: string;
          source_record_id?: string | null;
        };
        Relationships: [];
      };
      treatment_conditions: {
        Row: {
          treatment_id: string;
          condition_id: string;
        };
        Insert: {
          treatment_id: string;
          condition_id: string;
        };
        Update: {
          treatment_id?: string;
          condition_id?: string;
        };
        Relationships: [];
      };
      treatment_countries: {
        Row: {
          treatment_id: string;
          country_id: string;
          source_record_id: string;
        };
        Insert: {
          treatment_id: string;
          country_id: string;
          source_record_id: string;
        };
        Update: {
          treatment_id?: string;
          country_id?: string;
          source_record_id?: string;
        };
        Relationships: [];
      };
      treatments: {
        Row: {
          id: string;
          slug: string;
          name: string;
          specialty_id: string;
          category: string;
          description: string;
          aliases: string[];
          overview: string;
          procedure_summary: string;
          indications: string;
          diagnostics: string;
          recovery: string;
          typical_stay_days: number | null;
          faqs: Json;
          source_kind: string;
          publication_status: string;
          source_record_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          specialty_id: string;
          category: string;
          description: string;
          aliases?: string[];
          overview: string;
          procedure_summary: string;
          indications: string;
          diagnostics: string;
          recovery: string;
          typical_stay_days?: number | null;
          faqs?: Json;
          source_kind: string;
          publication_status?: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          specialty_id?: string;
          category?: string;
          description?: string;
          aliases?: string[];
          overview?: string;
          procedure_summary?: string;
          indications?: string;
          diagnostics?: string;
          recovery?: string;
          typical_stay_days?: number | null;
          faqs?: Json;
          source_kind?: string;
          publication_status?: string;
          source_record_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      workflow_runs: {
        Row: {
          id: string;
          workflow_id: string;
          case_id: string | null;
          status: string;
          idempotency_key: string | null;
          started_at: string | null;
          finished_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workflow_id: string;
          case_id?: string | null;
          status: string;
          idempotency_key?: string | null;
          started_at?: string | null;
          finished_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workflow_id?: string;
          case_id?: string | null;
          status?: string;
          idempotency_key?: string | null;
          started_at?: string | null;
          finished_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      workflow_steps: {
        Row: {
          id: string;
          workflow_run_id: string;
          step_key: string;
          position: number;
          status: string;
          owner_id: string | null;
          due_at: string | null;
          started_at: string | null;
          finished_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workflow_run_id: string;
          step_key: string;
          position: number;
          status: string;
          owner_id?: string | null;
          due_at?: string | null;
          started_at?: string | null;
          finished_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workflow_run_id?: string;
          step_key?: string;
          position?: number;
          status?: string;
          owner_id?: string | null;
          due_at?: string | null;
          started_at?: string | null;
          finished_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      workflows: {
        Row: {
          id: string;
          slug: string;
          name: string;
          version: number;
          status: string;
          definition: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          version?: number;
          status?: string;
          definition?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          version?: number;
          status?: string;
          definition?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      search_catalog_candidates: {
        Args: { p_terms: string; p_treatment_slug?: string | null; p_specialty?: string | null; p_countries?: string[]; p_city?: string | null };
        Returns: { kind: string; slug: string }[];
      };
      acquire_assistant_turn: { Args: { p_conversation_id: string; p_user_id: string; p_token: string }; Returns: boolean };
      release_assistant_turn: { Args: { p_conversation_id: string; p_token: string }; Returns: undefined };
      save_care_plan: { Args: { p_plan: Json; p_token: string }; Returns: undefined };
      save_document_workspace: { Args: { p_workspace: Json; p_expected_revision: number; p_action: string }; Returns: undefined };
    };
    Enums: {
      case_lifecycle_status: "draft" | "intake" | "planning" | "awaiting_patient" | "awaiting_provider" | "in_progress" | "completed" | "cancelled";
      provider_verification_status: "draft" | "pending_verification" | "verified" | "suspended" | "archived";
    };
    CompositeTypes: Record<string, never>;
  };
};
