// Bounded official-source collection. Preparation creates private admin_reference
// drafts only. Each frozen claim still requires review and explicit publication.
export const packageCollectedAt = '2026-10-05T05:56:03Z';
export const packageReviewAfter = '2026-11-04';
export const packageSources = {
  deenHealth: {name:'Deenanath Mangeshkar Hospital — Health Packages (tariff effective 15 July 2026)',url:'https://www.dmhospital.org/health-packages',sourceType:'provider_website' as const},
  kokilabenHealth: {name:'Kokilaben Hospital — Air Tanzania health check tariffs',url:'https://www.kokilabenhospital.com/patients/internationalpatients/travel_partners.html',sourceType:'provider_website' as const},
  generalMedicine: {name:'Manipal Old Airport Road — General Medicine',url:'https://www.manipalhospitals.com/oldairportroad/specialities/general-medicine/',sourceType:'provider_website' as const},
};
export type PackageSource = keyof typeof packageSources;
export const packageTaxonomy = [
  {entity:'specialties' as const,slug:'general-medicine',name:'General Medicine',source:'generalMedicine' as PackageSource,data:{aliases:[]}},
  {entity:'treatments' as const,slug:'health-checkup',name:'Health Checkup',source:'deenHealth' as PackageSource,data:{specialty_id:'$specialties:general-medicine',category:'Health screening',description:'Provider-listed health check packages. Individual tests and consultations vary by package; suitability and preparation require provider advice.',overview:'',procedure_summary:'',indications:'',diagnostics:'',recovery:'',typical_stay_days:null,faqs:[],aliases:['health check','health check-up','health screening','executive health check']}},
];
export type SourcedPackage = {key:string;providerKey:string;name:string;source:PackageSource;data:Record<string,string|number|string[]>;evidence:string};
const diagnostics = ['Haemogram','Fasting and postprandial blood sugar','Lipid profile','Serum creatinine','Urine routine/microscopy','ECG','Chest X-ray'];
const deen = (key:string,name:string,price:number,consultations:string[],tests:string[]):SourcedPackage => ({key,providerKey:'deenanath-erandwane',name,source:'deenHealth',evidence:'The exact named package table establishes payable cost in Indian rupees, listed consultations and tests; the page states tariff effective 15 July 2026, prior appointment and extra charges for additional tests. Its address is the published Erandwane branch. Duration and travel services are not established.',data:{treatmentId:'$treatments:health-checkup',locationId:'$record:location',description:`${name}: provider-listed health check consultations and investigations at Deenanath Mangeshkar Hospital, Erandwane, Pune.`,price,priceType:'package_price',currency:'INR',priceSourceUrl:packageSources.deenHealth.url,priceSourceName:packageSources.deenHealth.name,priceCheckedAt:packageCollectedAt.slice(0,10),priceValidFrom:'2026-07-15',consultationStatus:'included',consultationInfo:consultations.join('; '),diagnosticsStatus:'included',diagnosticsInfo:tests.join('; '),inclusions:[...consultations,...tests],exclusions:['Additional tests outside the listed package cost extra'],terms:'Prior appointment required. Additional tests outside the package are charged separately. Confirm current tariff, eligibility and preparation with the hospital. Package duration and tariff end date are not provided.'}});
const kokilaben = (key:string,name:string,price:number,platinum=false):SourcedPackage => ({key,providerKey:'kokilaben-andheri',name,source:'kokilabenHealth',evidence:'The Air Tanzania section explicitly names this health check and its promotional price in USD. Eligibility is limited to the described Air Tanzania arrangement and conditions apply. The source is undated and establishes no current booking availability, duration or test list. Only Platinum packages list one night in a guest room.',data:{treatmentId:'$treatments:health-checkup',locationId:'$record:location',description:`${name}: conditional Air Tanzania health check tariff listed by Kokilaben Hospital for its Mumbai branch.`,price,priceType:'published_price',currency:'USD',priceSourceUrl:packageSources.kokilabenHealth.url,priceSourceName:packageSources.kokilabenHealth.name,priceCheckedAt:packageCollectedAt.slice(0,10),terms:'Air Tanzania passenger arrangement; conditions apply. Source gives no tariff validity dates. Confirm current tariff, eligibility, tests, duration and availability with the hospital. This listing is not a booking offer.',...(platinum?{accommodationStatus:'conditional',accommodationInfo:'One night in a guest room is listed for Platinum packages within the Air Tanzania arrangement; eligibility and applicable conditions need provider confirmation.'}:{})}});
export const sourcedPackages:SourcedPackage[] = [
  deen('deen-basic','Basic Package',3450,['Physician consultation','Eye consultation'],diagnostics),
  deen('deen-executive-a','Executive - A',5900,['Physician consultation','Eye consultation'],[...diagnostics,'HbA1c','Ultrasensitive TSH','Blood urea','Treadmill stress test']),
  deen('deen-senior','Senior Citizen',3400,['Physician consultation'],[...diagnostics,'Ultrasensitive TSH','Blood urea','HbA1c']),
  deen('deen-executive-b','Executive - B',7850,['Physician consultation','Eye consultation'],[...diagnostics,'Blood urea','SGOT','SGPT','HbA1c','Ultrasensitive TSH','Treadmill stress test','Abdominal and pelvic sonography']),
  deen('deen-well-woman-i','Well Woman - I',4770,['Gynaecology consultation'],['HPV genotyping (16,18)','Digital mammography']),
  kokilaben('kokilaben-whole-body-male-iii','Whole Body Check Male - III',260),
  kokilaben('kokilaben-platinum-male','Platinum (Male)',1445,true),
];
