'use client';
import { providerConnectivityLabel } from '@/lib/portals/network';
import Link from 'next/link';
import { useEffect,useRef,useState,type FormEvent,type ReactNode } from 'react';
import { useExperience } from '@/components/experience/provider';
import { T, LocalDateTime } from '@/components/experience/translation';
import { InlineSkeleton } from '@/components/inline-skeleton';
import { getBrowserSupabaseClient } from '@/lib/supabase/browser';
import { inquiryNextStep,inquiryStatusLabel,providerStatusLabel,type InquiryContext,type InquiryDocument } from '@/lib/inquiries/schemas';
type Fields=Record<string,unknown>;
type Run=(action:string,input:Fields)=>Promise<void>;
function Form({title,action,children,input,run,busy,confirm=false,submit='Save'}:{title:string;action:string;children?:ReactNode;input?:(f:FormData)=>Fields;run:Run;busy:boolean;confirm?:boolean;submit?:string}){
  async function handle(e:FormEvent<HTMLFormElement>){e.preventDefault();const element=e.currentTarget;try{await run(action,{...input?.(new FormData(element)),...(confirm&&['share_document','share_provider','link_recovery','provider_response'].includes(action)?{confirmed:true}:{})});element.reset();}catch{/* The parent retains the error and retry operation. */}}
  return <details className="inquiry-disclosure"><summary>{title}</summary><form className="personal-form" onSubmit={handle}>{children}{confirm&&<label className="check-label"><input type="checkbox" required/>I reviewed this action and authorize it.</label>}<button className="save-control" disabled={busy}>{submit}</button></form></details>;
}
function Field({name,label,max=8000,min=1,defaultValue,rows=3}:{name:string;label:string;max?:number;min?:number;defaultValue?:string;rows?:number}){return <label>{label}<textarea name={name} required minLength={min} maxLength={max} defaultValue={defaultValue} rows={rows}/></label>;}
const str=(f:FormData,key:string)=>String(f.get(key)??'');
function localDateTime(value:string|null){if(!value)return '';const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export function InquiryDetail({id,portal='patient'}:{id:string;portal?:'patient'|'support'|'admin'|'provider'}){
  const {api,session}=useExperience(),owner=session?.user.id;
  const [state,setState]=useState<{owner:string;id:string;data:InquiryContext}|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0);
  const operations=useRef(new Map<string,string>()),currentOwner=useRef(owner);
  useEffect(()=>{currentOwner.current=owner;},[owner]);
  const base=`/api/inquiries?portal=${portal}`;
  useEffect(()=>{let active=true;if(owner)void api(`${base}&id=${encodeURIComponent(id)}`).then(raw=>{if(active){setState({owner,id,data:raw as InquiryContext});setError('');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[api,owner,id,base,reload]);
  const context=state&&state.owner===owner&&state.id===id?state.data:null;
  async function run(action:string,input:Fields){const account=owner;setError('');setNotice('');setBusy(true);const key=JSON.stringify({account,id,action,input});let op=operations.current.get(key);if(!op){op=crypto.randomUUID();operations.current.set(key,op);}try{
    await api(base,{method:'POST',body:JSON.stringify({action,input:{...input,caseId:id,operationId:op}})});
    if(currentOwner.current!==account)return;operations.current.delete(key);setReload(v=>v+1);setNotice(action==='read_messages'?'Messages marked as read.':'Change saved.');
  }catch(e){if(currentOwner.current===account)setError(e instanceof Error?e.message:'The change was not saved. Retry.');throw e;}finally{if(currentOwner.current===account)setBusy(false);}}
  async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const account=owner,form=e.currentTarget,body=new FormData(form);body.set('caseId',id);const file=body.get('file');if(!(file instanceof File))return;
    setBusy(true);setError('');setNotice('');try{
      if(!file.size||file.size>3*1024*1024)throw new Error('Choose a nonempty PDF, PNG or JPEG up to 3 MB.');
      const checksum=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))).map(b=>b.toString(16).padStart(2,'0')).join('');
      if(currentOwner.current!==account)return;
      const key=JSON.stringify({account,id,file:file.name,checksum,request:body.get('requestId'),replacement:body.get('replacesId')});let op=operations.current.get(key);if(!op){op=crypto.randomUUID();operations.current.set(key,op);}body.set('operationId',op);if(!body.get('requestId'))body.delete('requestId');if(!body.get('replacesId'))body.delete('replacesId');
      const token=(await getBrowserSupabaseClient()?.auth.getSession())?.data.session?.access_token;if(currentOwner.current!==account)return;if(!token)throw new Error('Sign in to upload.');
      const response=await fetch(`/api/inquiries/documents?portal=${portal}`,{method:'POST',body,headers:{Authorization:`Bearer ${token}`}});const data=await response.json();if(!response.ok)throw new Error(data.error);if(currentOwner.current!==account)return;operations.current.delete(key);form.reset();setReload(v=>v+1);setNotice('Upload saved. Review this file’s current sharing state below.');
    }catch(e){if(currentOwner.current===account)setError(e instanceof Error?e.message:'Upload failed. Keep the file selected and retry.');}finally{if(currentOwner.current===account)setBusy(false);}}
  async function download(d:InquiryDocument){const account=owner;setBusy(true);setError('');try{const token=(await getBrowserSupabaseClient()?.auth.getSession())?.data.session?.access_token;if(currentOwner.current!==account)return;if(!token)throw new Error('Sign in to download.');const response=await fetch(`/api/inquiries/documents?portal=${portal}&id=${d.id}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(!response.ok){const data=await response.json();throw new Error(data.error);}const bytes=await response.blob();if(currentOwner.current!==account)return;const url=URL.createObjectURL(bytes);const a=document.createElement('a');a.href=url;a.download=d.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}catch(e){if(currentOwner.current===account)setError(e instanceof Error?e.message:'Download failed. Please retry.');}finally{if(currentOwner.current===account)setBusy(false);}}
  if(!context)return <>{error?<><p role="alert">{error}</p><button className="save-control" onClick={()=>setReload(v=>v+1)}>Retry loading request</button></>:<InlineSkeleton/>}</>;
  if(context.case.inquiry_source==='legacy')return <section className="inquiry-detail"><p className="eyebrow">SUPPORT REQUEST {id.slice(0,8)}</p><h2>{context.case.title}</h2><p>This earlier Support request is managed in Patient Help.</p><Link className="button button--primary" href="/help">Open Patient Help →</Link></section>;
  const c=context.case,isOwner=context.role==='patient',isStaff=context.role==='support',isProvider=context.role==='provider',active=!c.consent_revoked_at&&!['resolved','closed','cancelled'].includes(c.status);
  const staff=context.staffDirectory.map(s=>({userId:s.id,email:s.name,role:s.role}));
  const manager=['support_manager','admin','super_admin'].includes(staff.find(s=>s.userId===owner)?.role??'');
  const nextStatuses= c.status==='cancelled'?['cancelled']:c.status==='closed'?(manager?['closed','open']:['closed']):c.status==='resolved'?(manager?['resolved','closed','open']:['resolved','closed']):[c.status,...['in_progress','waiting_patient','waiting_provider','escalated','resolved','closed'].filter(s=>s!==c.status&&(s!=='waiting_provider'||c.share_with_provider))];
  const assignableStaff=manager?staff:staff.filter(s=>s.userId===owner||s.userId===c.assigned_to);
  const markRead=()=>void run('read_messages',{}).catch(()=>{});
  return <article className="inquiry-detail">
    <header><p className="eyebrow">REQUEST {id.slice(0,8)}</p><h2>{c.title}</h2><div className="inquiry-status"><strong>{inquiryStatusLabel(c.status)}</strong><span>Updated <LocalDateTime value={c.updated_at}/></span>{c.due_at&&<span>Due <LocalDateTime value={c.due_at}/></span>}<button className="save-control" disabled={busy} onClick={()=>setReload(v=>v+1)}>Refresh updates</button></div></header>
    {error&&<p role="alert" className="inquiry-error">{error}</p>}{notice&&<p role="status" className="personal-notice">{notice}</p>}
    <section className="inquiry-next"><h3>Next step</h3><p>{inquiryNextStep(context)}</p>{c.resolution_summary&&<p><strong>Resolution:</strong> {c.resolution_summary}</p>}</section>
    <section><h3>Selected listing</h3><div className="inquiry-linked"><span>{c.entity_snapshot.kind}</span><Link href={c.entity_snapshot.href}>{c.entity_snapshot.name}</Link>{c.entity_snapshot.publishedRevision!==null&&<small>Request relates to published revision {c.entity_snapshot.publishedRevision}</small>}</div><p className="inquiry-prewrap">{c.description}</p></section>
    <section><h3>Messages</h3><p>Messages and updates are delivered in MedBridge. Email and SMS delivery are not configured.</p>{context.unread>0&&<button className="save-control" disabled={busy} onClick={markRead}>Mark {context.unread} unread messages as read</button>}
      {!context.messages.length&&<p>No messages yet. Your request is saved and available to Support.</p>}
      <ol className="inquiry-messages">{context.messages.filter(m=>m.visibility!=='internal').map(m=><li key={m.id}><header><strong>{m.sender}</strong><span>{m.visibility==='shared'?'Shared with the authorized provider':m.visibility==='provider'?'Provider and Support':'Patient and Support'}</span><small><LocalDateTime value={m.created_at}/></small></header><p className="inquiry-prewrap">{m.body}</p></li>)}</ol>
      {active&&<form className="personal-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);try{await run('message',{body:str(f,'body'),visibility:str(f,'visibility')});form.reset();}catch{}}}><Field name="body" label="Your message"/><label>Recipients<select name="visibility">{!isProvider&&<option value="patient">Patient and Support</option>}{c.share_with_provider&&<option value="shared">Patient, Support and authorized provider</option>}{isProvider&&<option value="provider">Provider and Support</option>}{isStaff&&c.share_with_provider&&<option value="provider">Provider and Support</option>}</select></label><button className="button button--primary" disabled={busy}>Send message</button></form>}
    </section>
    {isStaff&&<section className="inquiry-internal"><h3>Internal Support notes</h3><p>These notes are not visible to the patient or provider.</p>{context.messages.filter(m=>m.visibility==='internal').map(m=><div key={m.id}><small><LocalDateTime value={m.created_at}/></small><p className="inquiry-prewrap">{m.body}</p></div>)}{active&&<Form title="Add internal note" action="message" run={run} busy={busy} input={f=>({body:str(f,'body'),visibility:'internal'})}><Field name="body" label="Internal note"/></Form>}</section>}
    {(isStaff||isProvider)&&active&&<Form title="Request more information" action="request_information" run={run} busy={busy} input={f=>({body:str(f,'body')})} submit="Send information request"><Field name="body" min={5} label="Information needed and why"/></Form>}
    <section><h3>Documents and outstanding actions</h3><p>PDF, PNG or JPEG up to 3 MB. File type and signature are checked. Malware scanning is not configured. A coordination review is not a clinical assessment.</p>
      <ul className="inquiry-document-requests">{context.documentRequests.map(r=><li key={r.id}><strong>{r.title}</strong><p>{r.purpose}</p><small>{r.requesting_party} · {r.status.replaceAll('_',' ')}</small></li>)}</ul>
      {!context.documentRequests.length&&<p>No documents have been requested. No medical checklist is generated automatically.</p>}
      {isOwner&&active&&<details className="inquiry-disclosure"><summary>Upload a private document</summary><form className="personal-form" onSubmit={upload}><label>File<input name="file" type="file" accept="application/pdf,image/png,image/jpeg" required/></label><label>Requested for<select name="requestId"><option value="">My coordination question</option>{context.documentRequests.filter(r=>['requested','replacement_requested','uploaded'].includes(r.status)).map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label><label>Replace a previous file<select name="replacesId"><option value="">New document</option>{context.documents.filter(d=>!['pending_upload','withdrawn'].includes(d.status)).map(d=><option value={d.id} key={d.id}>{d.filename}</option>)}</select></label><p>Uploads start private. Replacing a file withdraws its previous shares; the replacement needs new permission.</p><button className="save-control" disabled={busy}>Upload privately</button></form></details>}
      <ul className="inquiry-documents">{context.documents.map(d=><li key={d.id}><div><strong>{d.filename}</strong><small>{d.status.replaceAll('_',' ')} · {Math.ceil(d.size_bytes/1024)} KB</small>{d.uploaded_at&&<small>Uploaded <LocalDateTime value={d.uploaded_at}/></small>}{d.review_note&&<p>{d.review_note}</p>}</div>{!['pending_upload','withdrawn'].includes(d.status)&&<button disabled={busy} className="save-control" onClick={()=>void download(d)}>Download</button>}
        {isOwner&&<><p>{d.grants.some(g=>!g.revoked_at)?'Shared with: '+d.grants.filter(g=>!g.revoked_at).map(g=>g.recipient==='provider'?context.organization?.name:g.recipient).join(', '):'Private to you'}</p>{active&&!['pending_upload','withdrawn'].includes(d.status)&&(['support','provider'] as const).map(recipient=><div key={recipient}>{d.grants.some(g=>g.recipient===recipient&&!g.revoked_at)?<Form title={`Revoke ${recipient} access to this file`} action="revoke_document" run={run} busy={busy} confirm input={()=>({documentId:d.id,recipient})} submit="Revoke file access"><p>Future downloads by this recipient will be blocked. Previously downloaded copies cannot be recalled.</p></Form>:(recipient==='support'||c.share_with_provider)&&<Form title={`Share this file with ${recipient==='provider'?context.organization?.name:'MedBridge Support'}`} action="share_document" run={run} busy={busy} confirm input={f=>({documentId:d.id,recipient,purpose:str(f,'purpose'),...(recipient==='provider'?{organizationId:context.organization?.id}:{})})} submit="Share this selected file"><p>Only {d.filename} will be shared with {recipient==='provider'?context.organization?.name:'authorized Support staff'} for the purpose below. Other files stay private.</p><Field name="purpose" min={5} max={400} label="Purpose of this file share"/></Form>}</div>)}{active&&!['pending_upload','withdrawn'].includes(d.status)&&<Form title="Withdraw this file" action="withdraw_document" run={run} busy={busy} confirm input={()=>({documentId:d.id})} submit="Withdraw file"><p>Withdraw this file and all its recipient permissions. Audit history is retained.</p></Form>}<details><summary>Sharing history</summary><ul>{d.grants.map(g=><li key={g.id}>{g.recipient} · {g.purpose} · {g.revoked_at?'Revoked':'Active'} <LocalDateTime value={g.revoked_at??g.granted_at}/></li>)}</ul></details></>}
        {(isStaff||isProvider)&&active&&<Form title="Update coordination document review" action="review_document" run={run} busy={busy} input={f=>({documentId:d.id,status:str(f,'status'),...(str(f,'note')?{note:str(f,'note')}:{})})}><label>Review status<select name="status"><option value="under_review">Under review</option><option value="accepted_for_coordination">Accepted for coordination</option><option value="replacement_requested">Replacement requested</option></select></label><Field name="note" label="Review note or replacement reason" max={800} min={5}/></Form>}
      </li>)}</ul>
      {(isStaff||isProvider)&&active&&<Form title="Request a document" action="request_document" run={run} busy={busy} input={f=>({title:str(f,'title'),purpose:str(f,'purpose'),visibility:isProvider?'shared':'patient'})} submit="Send document request"><Field name="title" label="Document requested" max={180} min={3}/><Field name="purpose" label="Coordination purpose and recipient" max={800} min={5}/><p>Request only a necessary coordination document. This is not a hospital admission requirement or medical instruction.</p></Form>}
    </section>
    <section><h3>Provider coordination</h3><p>{context.organization?.name??'No connected provider team for this reference listing.'}</p><p>{c.share_with_provider?'Sharing authorized by the patient for the purpose recorded below.':'Routed to MedBridge Support. Provider access has not been authorized.'}</p><p>Status: {['resolved','closed','cancelled'].includes(c.status)?'Coordination complete':providerStatusLabel(c.provider_response_status)}{c.provider_responded_at&&<> · <LocalDateTime value={c.provider_responded_at}/></>}</p>
      {context.role==='support' && context.providerCoordination?.readiness && <p><T>{providerConnectivityLabel(context.providerCoordination.readiness)}</T></p>}
      {context.providerCoordination?.available===false&&<p>Direct provider coordination is unavailable. Support can continue the permitted coordination process; no external delivery is confirmed.</p>}
      {context.providerCoordination?.latestResponse&&<div className="inquiry-next"><h4>Latest recorded provider response</h4><p>{context.providerCoordination.latestResponse.responderName} · {context.providerCoordination.latestResponse.organizationName} · <LocalDateTime value={context.providerCoordination.latestResponse.createdAt}/></p><p className="inquiry-prewrap">{context.providerCoordination.latestResponse.body}</p></div>}
      {context.providerCoordination?.informationRequestedAt&&<p>Information requested <LocalDateTime value={context.providerCoordination.informationRequestedAt}/>{context.providerCoordination.informationAnsweredAt?<> · Patient replied to the provider <LocalDateTime value={context.providerCoordination.informationAnsweredAt}/></>:c.provider_response_status==='information_requested'?' · Awaiting a shared patient reply.':' · Review the message history for subsequent coordination.'}</p>}
      {isOwner&&active&&context.organization&&context.providerCoordination?.available!==false&&!c.share_with_provider&&<Form title={`Authorize ${context.organization.name}`} action="share_provider" run={run} busy={busy} confirm input={f=>({organizationId:context.organization?.id,purpose:str(f,'purpose')})} submit="Authorize this provider"><p>{context.organization.name} will see the reviewed request, selected listing, shared messages and coordination status. Patient-only messages, internal Support notes, conversation contents and unshared files remain private.</p><Field name="purpose" label="Purpose of provider coordination" min={5} max={400}/></Form>}
      {isOwner&&c.share_with_provider&&<Form title="Revoke provider access" action="revoke_provider" run={run} busy={busy} confirm submit="Revoke provider access"><p>Future provider access to this request and provider-shared documents will stop. Previous downloads cannot be recalled.</p></Form>}
      <details><summary>Provider consent history</summary><ul>{context.consents.map(g=><li key={g.id}>{g.purpose} · {g.revoked_at?'Revoked':'Active'} <LocalDateTime value={g.revoked_at??g.granted_at}/></li>)}</ul></details>
      {isProvider&&active&&<Form title="Respond as provider" action="provider_response" run={run} busy={busy} confirm input={f=>({status:str(f,'status'),body:str(f,'body')})} submit="Send provider response"><label>Response status<select name="status"><option value="responded">Provider responded</option><option value="information_requested">More information needed</option><option value="further_review">Further coordination required</option><option value="accepted_for_coordination">We can continue coordination</option><option value="unable_to_coordinate">Unable to proceed</option></select></label><Field name="body" label="Provider response" min={5}/><p>Confirm this operational response for your organization. Continuing coordination does not confirm an appointment, tariff, treatment or medical eligibility.</p></Form>}
    </section>
    {isStaff&&!c.consent_revoked_at&&<section><h3>Support operations</h3><Form key={c.revision} title="Assignment, status and escalation" action="update" run={run} busy={busy} input={f=>({expectedRevision:c.revision,status:str(f,'status'),assignedTo:str(f,'assignedTo')||null,priority:str(f,'priority'),dueAt:str(f,'dueAt')?new Date(str(f,'dueAt')).toISOString():null,...(str(f,'resolution')?{resolution:str(f,'resolution')}:{}),...(str(f,'reason')?{reason:str(f,'reason')}:{})})}><label>Status<select name="status" defaultValue={c.status}>{nextStatuses.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label><label>Assigned staff<select name="assignedTo" defaultValue={c.assigned_to??''}>{(manager||!c.assigned_to)&&<option value="">Unassigned</option>}{assignableStaff.map(s=><option key={s.userId} value={s.userId}>{s.email} · {s.role.replaceAll('_',' ')}</option>)}{session&&!staff.some(s=>s.userId===session.user.id)&&<option value={session.user.id}>Me</option>}{c.assigned_to&&!staff.some(s=>s.userId===c.assigned_to)&&c.assigned_to!==owner&&<option value={c.assigned_to}>Current assignee</option>}</select></label><label>Priority<select name="priority" defaultValue={c.priority}>{['low','normal','high','urgent'].map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label><label>Due date<input name="dueAt" type="datetime-local" defaultValue={localDateTime(c.due_at)}/></label><label>Resolution required for closing<textarea name="resolution" minLength={5} maxLength={4000} defaultValue={c.resolution_summary??''}/></label><label>Reason required for escalation<textarea name="reason" minLength={5} maxLength={4000}/></label></Form>
      <ul>{context.tasks.map(t=><li key={t.id}>{t.title} · {t.status.replaceAll('_',' ')}{active&&<Form title="Update task" action="save_task" run={run} busy={busy} input={f=>({taskId:t.id,expectedRevision:t.revision,title:t.title,status:str(f,'status'),assignedTo:t.assigned_to,priority:t.priority,dueAt:t.due_at})}><label>Task status<select name="status" defaultValue={t.status}>{['open','in_progress','completed','cancelled'].map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label></Form>}</li>)}</ul>{active&&<Form title="Create Support task" action="save_task" run={run} busy={busy} input={f=>({title:str(f,'title'),status:'open',assignedTo:owner})}><Field name="title" label="Coordination task" max={180} min={3}/></Form>}</section>}
    <section><h3>Activity history</h3><ol className="recovery-timeline">{context.events.map(e=><li key={e.id}><strong>{e.summary}</strong><small><LocalDateTime value={e.created_at}/></small></li>)}</ol></section>
    {isOwner&&<section><h3>Your controls</h3>{context.journeys.length>0&&<Form title="Create a linked Recover task" action="link_recovery" run={run} busy={busy} confirm input={f=>({journeyId:str(f,'journeyId'),eventId:str(f,'eventId'),title:str(f,'title')})} submit="Create my coordination task"><p>This user-created task links to a real request event. No clinical milestone or medical reminder is generated.</p><label>My journey<select name="journeyId" required>{context.journeys.map(j=><option key={j.id} value={j.id}>{j.title}</option>)}</select></label><label>Related event<select name="eventId" required>{context.events.map(e=><option key={e.id} value={e.id}>{e.summary}</option>)}</select></label><Field name="title" label="My coordination task" max={160} min={3}/></Form>}<Link className="text-link" href={c.recovery_journey_id?`/recover?journey=${c.recovery_journey_id}`:'/recover'}>{c.recovery_journey_id?'Open linked Recover journey':'Manage my Recover journeys'} →</Link>
      <Link className="text-link" href={`/assistant?inquiry=${id}`}>Ask MedBridge AI about this request →</Link>
      {active&&<Form title="Cancel this request" action="cancel" run={run} busy={busy} confirm submit="Cancel request"><p>Cancel coordination and revoke provider and file permissions. The audit history remains available.</p></Form>}
      {!c.consent_revoked_at&&<Form title="Withdraw Support consent" action="revoke_support" run={run} busy={busy} confirm submit="Withdraw Support consent"><p>Support and provider access to this request and shared files will stop. The request remains available to you.</p></Form>}
    </section>}
  </article>;
}
