'use client';
import Link from 'next/link';
import { useEffect,useRef,useState,type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { useExperience } from '@/components/experience/provider';
import { SignIn } from '@/components/experience/sign-in';
import { InlineSkeleton } from '@/components/inline-skeleton';
import type { InquiryTarget } from '@/lib/inquiries/schemas';
type RequestProps={kind:string;entityId:string;source:string;conversationId?:string};
export function RequestForm(props:RequestProps){const {session,authReady}=useExperience();if(!authReady)return <InlineSkeleton/>;if(!session)return <section className="inquiry-flow"><h1>Request assistance</h1><p>Sign in to review a coordination question about your selected listing. No request is sent until you review and authorize it.</p><SignIn/></section>;return <AuthenticatedRequestForm key={`${session.user.id}:${props.kind}:${props.entityId}`} {...props}/>;}
function AuthenticatedRequestForm({kind,entityId,source,conversationId}:RequestProps){
  const {session,authReady,api}=useExperience(),router=useRouter();
  const [state,setState]=useState<{owner:string;target:InquiryTarget}|null>(null),[error,setError]=useState(''),[reload,setReload]=useState(0),[busy,setBusy]=useState(false),[review,setReview]=useState<{title:string;objective:string;target:InquiryTarget}|null>(null);
  const operations=useRef(new Map<string,string>());const [draft,setDraft]=useState<{title:string;objective:string}|null>(null);const owner=session?.user.id;const target=state&&state.owner===owner?state.target:null;
  const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  useEffect(()=>{let active=true;if(owner)void api(`/api/inquiries?kind=${encodeURIComponent(kind)}&entityId=${encodeURIComponent(entityId)}`).then(raw=>{if(active){setState({owner,target:raw as InquiryTarget});setError('');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[owner,kind,entityId,api,reload]);
  if(!authReady)return <InlineSkeleton/>;if(!session)return <SignIn/>;
  function prepare(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const next={title:String(form.get('title')).trim(),objective:String(form.get('objective')).trim()};setDraft(next);if(target)setReview({...next,target});setError('');}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!review||!target)return;setBusy(true);setError('');try{
    const input={entityKind:review.target.kind,entityId:review.target.id,expectedPublishedRevision:review.target.publishedRevision,source,title:review.title,objective:review.objective,consent:true,reviewed:true,...(conversationId?{conversationId}:{})};const key=JSON.stringify(input);let operationId=operations.current.get(key);if(!operationId){operationId=crypto.randomUUID();operations.current.set(key,operationId);}const result=await api('/api/inquiries',{method:'POST',body:JSON.stringify({action:'create',input:{...input,operationId}})}) as {id:string};
    if(mounted.current)router.push(`/account?section=requests&request=${result.id}`);
  }catch(e){setError(e instanceof Error?e.message:'Submission failed. Your draft is available; retry.');}finally{setBusy(false);}}
  return <section className="inquiry-flow"><p className="eyebrow">PRIVATE CARE COORDINATION</p><h1>Request assistance</h1><p>Send a reviewed question to MedBridge Support. This is not a booking, current quote or medical consultation.</p>{error&&<div role="alert"><p>{error}</p>{target&&<button className="save-control" disabled={busy} onClick={()=>{setReview(null);setReload(v=>v+1);}}>Reload current listing and review again</button>}</div>}{!target?<>{!error?<InlineSkeleton/>:<button className="save-control" onClick={()=>setReload(v=>v+1)}>Retry loading the selected listing</button>}</>:<>
    <div className="inquiry-linked"><span>{target.kind}</span><Link href={target.href}>{target.name}</Link>{target.publishedRevision!==null&&<small>Published revision {target.publishedRevision}</small>}</div>
    {!review?<form className="personal-form" onSubmit={prepare}><label>Request title<input name="title" minLength={3} maxLength={180} defaultValue={draft?.title??`Assistance with ${target.name}`.slice(0,180)} required/></label><label>How can Support help?<textarea name="objective" minLength={5} maxLength={4000} rows={5} defaultValue={draft?.objective} required placeholder="Your coordination question, preferred timing or information you want clarified."/></label><p>Include only information needed for this question. Documents and provider access require separate permission after submission.</p><button className="button button--primary">Review request</button></form>:<form className="personal-form" onSubmit={submit}><h2>Review before sending</h2><h3>{review.title}</h3><p className="inquiry-prewrap">{review.objective}</p><p><strong>Recipient: MedBridge Support.</strong> Support receives this question and the selected published listing. Your account files and conversation contents are not shared.</p><p>{target.organizationName?`Provider access is a separate decision for ${target.organizationName}.`:'This listing has no connected provider team. Support can coordinate your question; a provider response is pending coordination.'}</p><label className="check-label"><input type="checkbox" required/>I authorize MedBridge Support to coordinate this reviewed request.</label><div className="inline-actions"><button type="button" className="save-control" disabled={busy} onClick={()=>setReview(null)}>Edit request</button><button className="button button--primary" disabled={busy}>{busy?'Submitting…':'Submit request'}</button></div></form>}
  </>}</section>;
}
