import { Suspense } from 'react';
import { ArrowRight, ArrowUpRight, BookOpenCheck } from 'lucide-react';
import Link from '@/components/catalog-link';
import { T } from '@/components/experience/translation';
import { Localized } from '@/components/experience/localized';
import { PackagePrice } from '@/components/experience/package-price';
import { PersonalSummary } from '@/components/experience/personal-summary';
import { SearchPrompt } from '@/components/search-prompt';
import { getHomepageCatalog } from '@/lib/catalog/homepage-service';

export const dynamic = 'force-dynamic';
const pathways=[['01','Explore','Explore hospitals, doctors, treatments and packages.','/discover'],['02','Compare','Place available options side by side.','/compare'],['03','Continue','Keep your options, plans and documents together.','/recover']] as const;
const exampleQuestion='Show health checkup packages in Pune under ₹10,000.';

export default function Home() {
  return <main id="main-content" tabIndex={-1} className="home-page">
    <section className="companion-hero container" aria-labelledby="home-title">
      <div><p className="eyebrow"><T>{'YOUR HEALTHCARE COMPANION'}</T></p><h1 id="home-title"><T>{'What are you trying to figure out?'}</T></h1><p className="companion-hero__lead"><T>{'Find healthcare options. Understand the details. Organize your next step.'}</T></p></div>
      <SearchPrompt id="home-request" label="Ask MedBridge AI" suggestions/>
      <p className="companion-hero__trust"><BookOpenCheck size={16} aria-hidden="true"/><T>{'Published information. Sources you can inspect.'}</T></p>
    </section>
    <PersonalSummary/>
    <section className="companion-path container" aria-label="How MedBridge helps">{pathways.map(([number,title,description,href])=><Link key={title} href={href}><span>{number}</span><div><h2><T>{title}</T></h2><p><T>{description}</T></p></div><ArrowUpRight size={20} aria-hidden="true"/></Link>)}</section>
    <Suspense fallback={<div className="container directory-loading" aria-busy="true"><div className="skeleton-line skeleton-line--title"/><div className="skeleton-results"><div className="skeleton-result"/><div className="skeleton-result"/></div></div>}><HomeCatalog/></Suspense>
    <section className="companion-recover container" aria-labelledby="continuity-title"><div><p className="eyebrow">LIFETIME RECOVER</p><h2 id="continuity-title"><T>{'Your next step deserves a place to live.'}</T></h2><p><T>{'Keep the practical details together before, during and after treatment. Your journey stays yours.'}</T></p><Link className="text-link" href="/recover"><T>{'Organize your journey'}</T><ArrowRight size={17} aria-hidden="true"/></Link></div><ol>{['Choose the next step','Keep provider details and documents together','Track your own progress','Return when you need to'].map((label,index)=><li key={label}><span>{index+1}</span><T>{label}</T></li>)}</ol></section>
    <section className="evidence-story" aria-labelledby="trust-title"><div className="container evidence-story__grid"><div><p className="eyebrow"><T>{'SOURCES, NOT GUESSWORK'}</T></p><h2 id="trust-title"><T>{'Know what we know.'}</T><br/><em><T>{'See what needs confirmation.'}</T></em></h2></div><div><p><T>{'Published options include their source and the details that still need provider confirmation.'}</T></p><details><summary><T>{'How we handle information'}</T></summary><p><T>{'Listings are reviewed before publication. Publication does not establish clinical quality. Public source research is identified separately, and medical decisions stay with a qualified professional.'}</T></p></details><Link className="text-link" href="/help"><T>{'Get help with the next step'}</T><ArrowRight size={17} aria-hidden="true"/></Link></div></div></section>
    <section className="companion-final container" aria-labelledby="final-title"><div><p className="eyebrow"><T>{'START WHERE YOU ARE'}</T></p><h2 id="final-title"><T>{'You don’t need all the answers to ask your first question.'}</T></h2></div><SearchPrompt id="final-request" compact/></section>
  </main>;
}

async function HomeCatalog(){
  const {treatments,hospitals,doctors,packages}=await getHomepageCatalog();
  const example=packages.find(item=>item.city?.toLowerCase()==='pune');
  return <>
    <section className="product-example container" aria-labelledby="example-title"><div><p className="eyebrow"><T>{'SEE HOW IT HELPS'}</T></p><h2 id="example-title"><T>{'A question becomes a clearer next step.'}</T></h2><p><T>{'Explore a real published option, then ask MedBridge AI to check the details that matter to you.'}</T></p><Link className="text-link" href="/packages"><T>{'Explore packages'}</T><ArrowRight size={17} aria-hidden="true"/></Link></div><div className="product-example__preview"><p className="product-example__question"><T>{'“Show me health check packages in Pune.”'}</T></p><span className="eyebrow"><T>{'PUBLISHED OPTION PREVIEW'}</T></span>{example?<article><p className="result-kicker">{example.hospitalName} · {example.city}</p><h3><Link href={`/packages/${example.slug}`}>{example.name}</Link></h3><PackagePrice item={example} compact/><details><summary><T>{'What is included?'}</T></summary><ul>{example.inclusions.slice(0,4).map(item=><li key={item}>{item}</li>)}</ul><Link href={`/packages/${example.slug}`}><T>{'View all inclusions and evidence'}</T> →</Link></details><p className="muted"><T>{'Current availability and final price need provider confirmation.'}</T></p></article>:<p><T>{'No published package matches this example yet. Ask MedBridge AI to explore available options.'}</T></p>}<Link className="button button--primary" href={`/assistant?${new URLSearchParams({q:exampleQuestion,start:'1'})}`}><T>{'Try this question'}</T><ArrowUpRight size={16} aria-hidden="true"/></Link></div></section>
    <section className="curated-providers container" aria-labelledby="providers-title"><div className="editorial-heading"><div><p className="eyebrow"><T>{'PROVIDERS TO EXPLORE'}</T></p><h2 id="providers-title"><T>{'Meet the options behind the answer.'}</T></h2></div><Link className="text-link" href="/hospitals"><T>{'Explore all hospitals'}</T><ArrowRight size={17} aria-hidden="true"/></Link></div>{!hospitals.length&&<p className="catalog-empty"><T>{'No published hospitals are available yet. Reviewed provider listings will appear here when published.'}</T></p>}<div className="provider-selection">{hospitals.map(item=><article key={item.slug}><span className="result-kicker">{item.city}, {item.country}</span><h3><Link href={`/hospitals/${item.slug}`}>{item.name}</Link></h3><p>{item.specialties.slice(0,3).join(' · ')}</p><Link className="result-action" href={`/hospitals/${item.slug}`}><T>{'View hospital'}</T><ArrowUpRight size={16} aria-hidden="true"/></Link></article>)}</div><Localized as="nav" className="companion-doctor-index" aria-label="Explore doctors">{doctors.slice(0,3).map(item=><Link key={item.slug} href={`/doctors/${item.slug}`}><strong>{item.name}</strong><span>{item.specialty} · {item.city}</span><ArrowUpRight size={18} aria-hidden="true"/></Link>)}</Localized><Link className="text-link" href="/doctors"><T>{'Explore all doctors'}</T><ArrowRight size={17} aria-hidden="true"/></Link></section>
    <section className="curated-topics container" aria-labelledby="topics-title"><div className="editorial-heading"><div><p className="eyebrow"><T>{'TREATMENT AREAS'}</T></p><h2 id="topics-title"><T>{'Begin with a topic.'}</T></h2></div><Link className="text-link" href="/treatments"><T>{'Explore all treatments'}</T><ArrowRight size={17} aria-hidden="true"/></Link></div>{!treatments.length&&<p className="editorial-note"><T>{'Published treatment information is being prepared.'}</T></p>}<div className="topic-index">{treatments.map(item=><Link key={item.slug} href={`/treatments/${item.slug}`}><span>{item.specialty}</span><strong>{item.name}</strong><ArrowUpRight size={19} aria-hidden="true"/></Link>)}</div><p className="editorial-note"><T>{'Treatment content is for exploration and has not been clinically reviewed.'}</T></p></section>
    <section className="container curated-packages"><div className="editorial-heading"><div><p className="eyebrow"><T>{'PRICE AND DETAILS, TOGETHER'}</T></p><h2><T>{'Explore published packages.'}</T></h2></div><Link href="/packages"><T>{'Explore packages'}</T> →</Link></div><div className="provider-selection">{packages.map(item=><article key={item.recordId}><p className="result-kicker">{item.hospitalName}</p><h3><Link href={`/packages/${item.slug}`}>{item.name}</Link></h3><PackagePrice compact item={item}/><p className="muted"><T>{'Provider confirmation required'}</T></p><Link className="text-link" href={`/packages/${item.slug}`}><T>{'View package'}</T> →</Link></article>)}</div></section>
  </>;
}
