import { T } from '@/components/experience/translation';
import { Localized } from '@/components/experience/localized';
import { ArrowRight, ArrowUpRight } from 'lucide-react';
import Link from '@/components/catalog-link';
import { PersonalSummary } from '@/components/experience/personal-summary';
import { SearchPrompt } from '@/components/search-prompt';
import { getHomepageCatalog } from '@/lib/catalog/homepage-service';

export const dynamic = 'force-dynamic';
const explore = [['Treatments','/treatments'],['Hospitals','/hospitals'],['Doctors','/doctors'],['Packages','/packages'],['Compare destinations','/compare'],['Second opinion','/second-opinion'],['Medical travel','/medical-travel'],['Lifetime Recover','/recover']] as const;
const help = [['Understand','Turn a complex request into a clear starting point.'],['Explore','Find relevant treatments, providers and services.'],['Verify','See what the available sources actually support.'],['Move forward','Organize requirements and prepare your next step.']] as const;
const prompts = [['Find hospitals','Find hospitals for knee replacement in Mumbai.'],['Compare destinations','Compare knee replacement in India and Turkey.'],['Check provider information','Verify contact information for Kokilaben Dhirubhai Ambani Hospital in Mumbai.'],['Prepare documents','Organize documents for a hospital.']] as const;

export default async function Home() {
  const { treatments, hospitals } = await getHomepageCatalog();
  return <main id="main-content" tabIndex={-1} className="home-page">
    <section className="invitation container" aria-labelledby="home-title">
      <div className="invitation__copy"><p className="eyebrow"><T>{"YOUR HEALTHCARE JOURNEY"}</T></p><h1 id="home-title"><T>{"Your care journey."}</T><br className="desktop-break" /> <T>{"Before, during and beyond treatment."}</T></h1><p className="invitation__lead"><T>{"Describe your treatment, location, budget or question. MedBridge helps organize the information and next steps."}</T></p><SearchPrompt id="home-request" /><Localized as="div" className="suggested-prompts" aria-label="Suggested requests">{prompts.map(([label,question]) => <Link key={label} href={`/assistant?q=${encodeURIComponent(question)}`}><T>{label}</T><ArrowUpRight size={14} aria-hidden="true" /></Link>)}</Localized><p className="invitation__scope"><T>{"Discovery uses reviewed, published listings. Public source research is identified separately. Medical decisions stay with a qualified professional."}</T></p></div>
      <Localized as="aside" className="request-path" aria-label="How MedBridge helps with a request"><p className="eyebrow"><T>{"FROM QUESTION TO CLARITY"}</T></p><p className="request-path__question"><T>{"“Where do I"}</T><br /><T>{"start?”"}</T></p><ol>{['Understand the request','Research available options','Verify the evidence','Organize the next step'].map((item,index)=><li key={item}><span>0{index+1}</span><T>{item}</T></li>)}</ol><span className="request-path__note"><T>{"A way to work through your question."}</T><br /><T>{"Each request uses only relevant steps."}</T></span></Localized>
    </section>
    <PersonalSummary/>
    <section className="help-section container" aria-labelledby="help-title"><div className="editorial-heading"><p className="eyebrow"><T>{"A CLEARER WAY THROUGH"}</T></p><h2 id="help-title"><T>{"Complex questions."}</T><br /><T>{"More manageable steps."}</T></h2></div><div className="help-concepts">{help.map(([title,description],index)=><article key={title}><span>0{index+1}</span><h3><T>{title}</T></h3><p><T>{description}</T></p></article>)}</div></section>
    <section className="explore-room" aria-labelledby="explore-title"><div className="container explore-room__grid"><div><p className="eyebrow"><T>{"EXPLORE"}</T></p><h2 id="explore-title"><T>{"Find your"}</T><br /><T>{"starting point."}</T></h2><p><T>{"Browse a topic, meet the information behind a provider, or place destinations side by side."}</T></p><Link className="text-link" href="/discover"><T>{"Explore all care options"}</T><ArrowRight size={17} aria-hidden="true" /></Link></div><Localized as="nav" className="explore-index" aria-label="Explore care">{explore.map(([label,href])=><Link href={href} key={href}><T>{label}</T><ArrowUpRight size={21} aria-hidden="true" /></Link>)}</Localized></div></section>
    <section className="journey-editorial container" aria-labelledby="journey-title"><p className="eyebrow"><T>{"KEEP THE WHOLE JOURNEY IN VIEW"}</T></p><h2 id="journey-title"><T>{"One step informs the next."}</T></h2><div>{[['Plan','Understand what you need.','Care Workspace','/assistant'],['Treat','Explore and compare care options.','Explore providers','/hospitals'],['Lifetime Recover','Stay connected beyond treatment.','Recovery journey','/recover']].map(([name,copy,label,href],index)=><article key={name}><span className="journey-editorial__number">0{index+1}</span><h3><T>{name}</T></h3><p><T>{copy}</T></p><Link href={href}><T>{label}</T><ArrowRight size={16} aria-hidden="true" /></Link></article>)}</div></section>
    <section className="curated-topics container" aria-labelledby="topics-title"><div className="editorial-heading"><div><p className="eyebrow"><T>{"TREATMENT AREAS"}</T></p><h2 id="topics-title"><T>{"Begin with a topic."}</T></h2></div><Link className="text-link" href="/treatments"><T>{"Explore all treatments"}</T><ArrowRight size={17} aria-hidden="true" /></Link></div>{!treatments.length && <p className="editorial-note"><T>{"Published treatment information is being prepared."}</T></p>}<div className="topic-index">{treatments.slice(0,8).map(item=><Link key={item.slug} href={`/treatments/${item.slug}`}><span>{item.specialty}</span><strong>{item.name}</strong><ArrowUpRight size={19} aria-hidden="true" /></Link>)}</div><p className="editorial-note"><T>{"Treatment content is for exploration and has not been clinically reviewed."}</T></p></section>
    <section className="curated-providers container" aria-labelledby="providers-title"><div className="editorial-heading"><div><p className="eyebrow"><T>{"PROVIDERS TO EXPLORE"}</T></p><h2 id="providers-title"><T>{"Look beyond a name."}</T></h2></div><Link className="text-link" href="/hospitals"><T>{"Explore all hospitals"}</T><ArrowRight size={17} aria-hidden="true" /></Link></div>{!hospitals.length && <p className="catalog-empty"><T>{"No published hospitals are available yet. Reviewed provider listings will appear here when published."}</T></p>}<div className="provider-selection">{hospitals.slice(0,3).map(item=><article key={item.slug}><span className="result-kicker">{item.city}, {item.country}</span><h3><Link href={`/hospitals/${item.slug}`}>{item.name}</Link></h3><p>{item.specialties.slice(0,3).join(' · ')}</p><span className="editorial-note"><T>{item.provenance?.origin === "admin_reference" ? "MedBridge reference information" : "Published provider · inspect field evidence"}</T></span><Link className="result-action" href={`/hospitals/${item.slug}`}><T>{"View hospital"}</T><ArrowUpRight size={16} aria-hidden="true" /></Link></article>)}</div></section>
    <section className="evidence-story" aria-labelledby="trust-title"><div className="container evidence-story__grid"><div><p className="eyebrow"><T>{"CLARITY INCLUDES UNCERTAINTY"}</T></p><h2 id="trust-title"><T>{"Know what’s supported."}</T><br /><em><T>{"See what’s still missing."}</T></em></h2></div><div><p><T>{"Provider information is only as useful as the evidence behind it. The workspace keeps source statements, check dates and unresolved details close to the answer."}</T></p><p><T>{"Catalog listings require review and explicit publication. Public source research is separate; factual verification does not establish clinical quality."}</T></p><Link className="text-link" href={`/assistant?q=${encodeURIComponent(prompts[2][1])}`}><T>{"Check provider information"}</T><ArrowRight size={17} aria-hidden="true" /></Link></div></div></section>
    <section className="final-invitation container" aria-labelledby="final-title"><p className="eyebrow"><T>{"START WHERE YOU ARE"}</T></p><h2 id="final-title"><T>{"You don’t need all the answers"}</T><br /><T>{"to ask your first question."}</T></h2><SearchPrompt id="final-request" compact /></section>
  </main>;
}
