import { ArrowRight, ArrowUpRight } from 'lucide-react';
import Link from 'next/link';
import { SearchPrompt } from '@/components/search-prompt';
import { getHomepageCatalog } from '@/lib/catalog/homepage-service';

export const dynamic = 'force-dynamic';
const explore = [['Treatments','/treatments'],['Hospitals','/hospitals'],['Doctors','/doctors'],['Packages','/packages'],['Compare destinations','/compare'],['Second opinion','/second-opinion'],['Medical travel','/medical-travel'],['Recovery','/recovery']] as const;
const help = [['Understand','Turn a complex request into a clear starting point.'],['Explore','Find relevant treatments, providers and services.'],['Verify','See what the available sources actually support.'],['Move forward','Organize requirements and prepare your next step.']] as const;
const prompts = [['Find hospitals','Find hospitals for knee replacement in Mumbai.'],['Compare destinations','Compare knee replacement in India and Turkey.'],['Check provider information','Verify contact information for Kokilaben Dhirubhai Ambani Hospital in Mumbai.'],['Prepare documents','Organize documents for a hospital.']] as const;

export default async function Home() {
  const { treatments, hospitals } = await getHomepageCatalog();
  return <main id="main-content" tabIndex={-1} className="home-page">
    <section className="invitation container" aria-labelledby="home-title">
      <div className="invitation__copy"><p className="eyebrow">YOUR HEALTHCARE JOURNEY</p><h1 id="home-title">Tell us what you’re<br className="desktop-break" /> trying to <em>figure out.</em></h1><p className="invitation__lead">Describe your treatment, location, budget or question. MedBridge helps organize the information and next steps.</p><SearchPrompt id="home-request" /><div className="suggested-prompts" aria-label="Suggested requests">{prompts.map(([label,question]) => <Link key={label} href={`/assistant?q=${encodeURIComponent(question)}`}>{label}<ArrowUpRight size={14} aria-hidden="true" /></Link>)}</div><p className="invitation__scope">Discovery uses reviewed, published listings. Public source research is identified separately. Medical decisions stay with a qualified professional.</p></div>
      <aside className="request-path" aria-label="How MedBridge helps with a request"><p className="eyebrow">FROM QUESTION TO CLARITY</p><p className="request-path__question">“Where do I<br />start?”</p><ol>{['Understand the request','Research available options','Verify the evidence','Organize the next step'].map((item,index)=><li key={item}><span>0{index+1}</span>{item}</li>)}</ol><span className="request-path__note">A way to work through your question.<br />Each request uses only relevant steps.</span></aside>
    </section>
    <section className="help-section container" aria-labelledby="help-title"><div className="editorial-heading"><p className="eyebrow">A CLEARER WAY THROUGH</p><h2 id="help-title">Complex questions.<br />More manageable steps.</h2></div><div className="help-concepts">{help.map(([title,description],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section className="explore-room" aria-labelledby="explore-title"><div className="container explore-room__grid"><div><p className="eyebrow">EXPLORE</p><h2 id="explore-title">Find your<br />starting point.</h2><p>Browse a topic, meet the information behind a provider, or place destinations side by side.</p><Link className="text-link" href="/discover">Explore all care options <ArrowRight size={17} aria-hidden="true" /></Link></div><nav className="explore-index" aria-label="Explore care">{explore.map(([label,href])=><Link href={href} key={href}>{label}<ArrowUpRight size={21} aria-hidden="true" /></Link>)}</nav></div></section>
    <section className="journey-editorial container" aria-labelledby="journey-title"><p className="eyebrow">KEEP THE WHOLE JOURNEY IN VIEW</p><h2 id="journey-title">One step informs the next.</h2><div>{[['Plan','Understand what you need.','Care Workspace','/assistant'],['Treat','Explore and compare care options.','Explore providers','/hospitals'],['Recover','Prepare for continuity after care.','Recovery pathway','/recovery']].map(([name,copy,label,href],index)=><article key={name}><span className="journey-editorial__number">0{index+1}</span><h3>{name}</h3><p>{copy}</p><Link href={href}>{label}<ArrowRight size={16} aria-hidden="true" /></Link></article>)}</div></section>
    <section className="curated-topics container" aria-labelledby="topics-title"><div className="editorial-heading"><div><p className="eyebrow">TREATMENT AREAS</p><h2 id="topics-title">Begin with a topic.</h2></div><Link className="text-link" href="/treatments">Explore all treatments <ArrowRight size={17} aria-hidden="true" /></Link></div>{!treatments.length && <p className="editorial-note">Published treatment information is being prepared.</p>}<div className="topic-index">{treatments.slice(0,8).map(item=><Link key={item.slug} href={`/treatments/${item.slug}`}><span>{item.specialty}</span><strong>{item.name}</strong><ArrowUpRight size={19} aria-hidden="true" /></Link>)}</div><p className="editorial-note">Treatment content is for exploration and has not been clinically reviewed.</p></section>
    <section className="curated-providers container" aria-labelledby="providers-title"><div className="editorial-heading"><div><p className="eyebrow">PROVIDERS TO EXPLORE</p><h2 id="providers-title">Look beyond a name.</h2></div><Link className="text-link" href="/hospitals">Explore all hospitals <ArrowRight size={17} aria-hidden="true" /></Link></div>{!hospitals.length && <p className="catalog-empty">No published hospitals are available yet. Reviewed provider listings will appear here when published.</p>}<div className="provider-selection">{hospitals.slice(0,3).map(item=><article key={item.slug}><span className="result-kicker">{item.city}, {item.country}</span><h3><Link href={`/hospitals/${item.slug}`}>{item.name}</Link></h3><p>{item.specialties.slice(0,3).join(' · ')}</p><span className="editorial-note">{item.provenance?.origin === "admin_reference" ? "MedBridge reference information" : "Published provider · inspect field evidence"}</span><Link className="result-action" href={`/hospitals/${item.slug}`}>View hospital <ArrowUpRight size={16} aria-hidden="true" /></Link></article>)}</div></section>
    <section className="evidence-story" aria-labelledby="trust-title"><div className="container evidence-story__grid"><div><p className="eyebrow">CLARITY INCLUDES UNCERTAINTY</p><h2 id="trust-title">Know what’s supported.<br /><em>See what’s still missing.</em></h2></div><div><p>Provider information is only as useful as the evidence behind it. The workspace keeps source statements, check dates and unresolved details close to the answer.</p><p>Catalog listings require review and explicit publication. Public source research is separate; factual verification does not establish clinical quality.</p><Link className="text-link" href={`/assistant?q=${encodeURIComponent(prompts[2][1])}`}>Check provider information <ArrowRight size={17} aria-hidden="true" /></Link></div></div></section>
    <section className="final-invitation container" aria-labelledby="final-title"><p className="eyebrow">START WHERE YOU ARE</p><h2 id="final-title">You don’t need all the answers<br />to ask your first question.</h2><SearchPrompt id="final-request" compact /></section>
  </main>;
}
