import { T } from './experience/translation';
import type { SearchService } from '@/lib/discovery/search-service';
import type { DiscoveryFilters } from '@/types/discovery';
export function DirectoryFilters({type,facets,filters}:{type:string;facets:Awaited<ReturnType<SearchService['facets']>>;filters:DiscoveryFilters}){
 const fields=[...(type!=='packages'?[{key:'specialty',label:'Specialty',items:facets.specialties.map(name=>({value:name,label:name}))}]:[]),{key:'city',label:'Location',items:facets.cities.map(name=>({value:name,label:name}))},...(type==='doctors'?[{key:'hospital',label:'Hospital',items:facets.hospitals.map(h=>({value:h.slug,label:h.name}))}]:[]),...(type==='packages'?[{key:'treatment',label:'Treatment',items:facets.treatments.map(t=>({value:t.slug,label:t.name}))}]:[])];
 const editable=fields.filter(field=>field.items.length>0).map(field=>field.key);
 const retained=Object.entries(filters).filter(([key,value])=>!['q','type','sort',...editable].includes(key)&&value!==undefined&&value!=='');
 return <form className="directory-filters" action={`/${type}`} key={JSON.stringify(filters)}>{filters.q&&<input type="hidden" name="q" value={filters.q}/>}<input type="hidden" name="type" value={type}/>{retained.map(([key,value])=><input type="hidden" key={key} name={key} value={String(value)}/>)}{fields.filter(field=>field.items.length>0).map(field=><label key={field.key}><T>{field.label}</T><select name={field.key} defaultValue={String(filters[field.key as keyof DiscoveryFilters]??'')}><option value=""><T>{'All'}</T></option>{field.items.map(item=><option value={item.value} key={item.value}>{item.label}</option>)}</select></label>)}<label><T>{'Sort by'}</T><select name="sort" defaultValue={filters.sort}><option value="name"><T>{'Name'}</T></option><option value="relevance"><T>{'Relevance'}</T></option><option value="location"><T>{'Location'}</T></option>{type==='packages'&&<option value="price"><T>{'Price within currency'}</T></option>}</select></label><button className="button button--outline" type="submit"><T>{'Apply filters'}</T> →</button></form>;
}
