import { MedBridgeLogo } from './medbridge-logo';
import { T } from '@/components/experience/translation';
import { Localized } from '@/components/experience/localized';
import Link from '@/components/catalog-link';
import { navigationGroups } from '@/lib/navigation';
import { ArrowUpRight } from 'lucide-react';
export function SiteFooter() {
  return <footer className="site-footer site-footer--visual4"><div className="container footer-conclusion"><Link className="brand brand--light" href="/" aria-label="MedBridge home"><MedBridgeLogo onDark/><span>MEDBRIDGE</span></Link><p><T>{'A clearer way through'}</T>{' '}<em><T>{'your healthcare questions.'}</T></em></p><Link className="text-link" href="/assistant"><T>{'Ask MedBridge AI'}</T><ArrowUpRight size={20} aria-hidden="true"/></Link></div><div className="container footer-navigation"><div><p className="footer-limit"><T>{'Catalog listings require review and publication. Confirm current details with the provider. Bookings, payments and clinical review are not active.'}</T></p><Link href="/account?section=privacy"><T>{'Privacy and consent'}</T></Link></div><Localized as="nav" aria-label="Footer Explore"><span className="footer-label"><T>{'Explore'}</T></span>{navigationGroups[0].items.map(item=><Link key={item.href} href={item.href}><T>{item.label}</T></Link>)}<Link href="/packages"><T>{'Packages'}</T></Link></Localized><details className="footer-pathways"><summary><T>{'Your next steps'}</T></summary>{navigationGroups.slice(1).map(group=><Localized as="nav" key={group.label} aria-label={group.label}>{group.items.map(item=><Link key={item.href} href={item.href}><T>{item.label}</T></Link>)}</Localized>)}</details><Localized as="nav" aria-label="Platform portals"><span className="footer-label"><T>{'Platform'}</T></span><Link href="/provider"><T>{'Provider portal'}</T></Link><Link href="/support"><T>{'Support portal'}</T></Link><Link href="/admin"><T>{'Admin portal'}</T></Link><Link href="/help"><T>{'Get support'}</T></Link></Localized></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} MedBridge</span><span><T>{'Information here is not medical advice.'}</T></span></div></footer>;
}
