"use client";
import { useState } from 'react';
import { T, LocalNumber, useTranslation } from '@/components/experience/translation';
import { InquiryDetail } from '@/components/inquiries/detail';
import { incidentCategories, resolutionCodes, type OperationsOverview, type OperationsInquiry } from '@/lib/operations/contracts';
import { networkNextStep, type NetworkReadiness } from '@/lib/portals/network';
import { label, type Field } from '@/lib/portals/config';
import { date, Empty, ErrorPanel, Loading, Modal, Panel, Status as PortalStatus, usePortal, useResource } from './core';
import { CommandForm } from './command-form';

function Status({value}:{value:unknown}){
 const {locale}=useTranslation();const states:Record<string,[string,string]>={open:['खुला','उघडे'],closed:['बंद','बंद'],medium:['मध्यम','मध्यम'],low:['कम','कमी'],high:['अधिक','जास्त'],unknown:['परिणाम अनिश्चित','परिणाम अनिश्चित'],partially_completed:['आंशिक रूप से पूरा','अंशतः पूर्ण']};
 const local=states[String(value)];
 if(locale==='en'||!local)return <PortalStatus value={value}/>;
 return <span className={`portal-status status-${String(value)}`} data-status={String(value)}><span className="portal-status-dot" aria-hidden="true"/>{local[locale==='hi'?0:1]}</span>;
}
const confirmation:Field={key:'confirmed',label:'I reviewed and confirm this action',type:'checkbox'};
type Form={title:string;action:string;input?:Record<string,unknown>;fields:Field[];initial?:Record<string,unknown>};
function Counts({items}:{items:Array<[string,number]>}){return <dl className="operations-counts">{items.map(([title,value])=><div key={title}><dt><T>{title}</T></dt><dd><LocalNumber value={value}/></dd></div>)}</dl>;}
function Queue({admin,onAction,filterValue,onFilterChange}:{admin:boolean;onAction?:(form:Form)=>void;filterValue?:string;onFilterChange?:(value:string)=>void}){
 const [selected,setSelected]=useState<string|null>(null);const [localFilter,setLocalFilter]=useState('overdue');const filter=filterValue??localFilter;const setFilter=onFilterChange??setLocalFilter;const{data,error,loading}=useResource<{rows:OperationsInquiry[];asOf:string;limit:number}>('operations_inquiries',{filter});
 return <Panel title="Inquiries needing attention" actions={<label className="portal-field"><span className="sr-only"><T>Attention filter</T></span><select value={filter} onChange={e=>setFilter(e.target.value)}>{['overdue','all','unassigned','support','provider','patient'].map(v=><option key={v} value={v}><T>{({overdue:'Overdue',all:'All active',unassigned:'Unassigned',support:'Awaiting Support',provider:'Awaiting provider',patient:'Awaiting patient'})[v]!}</T></option>)}</select></label>}>
  <p className="portal-muted"><T>Operational thresholds do not indicate medical urgency. Status changes require an explicit authorized action.</T></p>
  {error?<ErrorPanel message={error}/>:loading?<Loading/>:data?.rows.length?<><p className="portal-muted"><T>Up to 50 matching inquiries. Activity times are shown in your selected timezone.</T></p><div className="operations-list">{data.rows.map(row=><article className="operations-row" key={row.id}>
   <div><strong><T>{row.attention==='provider'?'Awaiting provider':row.attention==='patient'?'Awaiting patient':row.attention==='unassigned'?'Unassigned':'Awaiting Support'}</T></strong><p><Status value={row.status}/>{' '}<Status value={row.overdue?'overdue':'within_policy'}/></p><details><summary><T>Details</T></summary><dl><dt><T>Inquiry ID</T></dt><dd className="operations-id">{row.id}</dd><dt><T>Last meaningful activity</T></dt><dd>{date(row.lastActivityAt)}</dd><dt><T>Provider coordination</T></dt><dd><Status value={row.providerStatus}/></dd></dl></details></div>
   <div><p><LocalNumber value={row.elapsedHours}/> <T>hours waiting</T></p><small><T>Threshold</T>: <LocalNumber value={row.thresholdHours}/> <T>hours</T></small></div>
   <div className="portal-actions"><button className="portal-button secondary" onClick={()=>setSelected(row.id)}><T>Open inquiry</T></button>{admin&&row.overdue&&row.status!=='escalated'&&<button className="portal-button secondary" onClick={()=>onAction?.({title:'Escalate overdue inquiry',action:'operations_escalate',input:{caseId:row.id,expectedRevision:row.revision},fields:[confirmation]})}><T>Escalate</T></button>}</div>
  </article>)}</div></>:<Empty title="No inquiries match this filter"/>}
 {selected&&<Modal title="Care coordination request" onClose={()=>setSelected(null)}><InquiryDetail id={selected} portal={admin?'admin':'support'}/></Modal>}
 </Panel>;
}
export function SupportAttention(){return <Queue admin={false}/>;}
export function Operations(){
 const {context,refresh}=usePortal();const {data,error,loading}=useResource<OperationsOverview>('operations_overview');
 const network=useResource<{rows:NetworkReadiness[]}>('network_readiness');const[form,setForm]=useState<Form|null>(null);const[queueFilter,setQueueFilter]=useState('overdue');
 const openHealth=()=>setForm({title:'Run a verified health check',action:'operations_health_check',fields:[confirmation]});
 const incident=()=>setForm({title:'Open operational incident',action:'operations_incident_create',initial:{category:'application',severity:'medium',ownerId:context.userId},fields:[{key:'category',label:'Component',type:'select',options:incidentCategories},{key:'severity',label:'Operational impact',type:'select',options:['low','medium','high','critical']},{key:'ownerId',label:'Admin owner',type:'select',catalog:'staff',catalogParams:{q:'admin'}},{key:'correlationId',label:'Correlation ID (optional)'},confirmation]});
 const h=data?.health;
 return <div className="operations-workspace">
  <div className="operations-intro"><div><h2><T>Operations</T></h2><p><T>Check service health, review waiting work and reconcile uncertain outcomes.</T></p>{data&&<small><T>Measured at</T>: {date(data.asOf)}</small>}</div><button className="portal-button secondary" onClick={refresh}><T>Refresh</T></button></div>
  {error?<ErrorPanel message={error}/>:loading?<Loading/>:data&&<>
   <Panel title="Application health" actions={<button className="portal-button" onClick={openHealth}><T>Check health</T></button>}>
    <dl className="operations-health"><div><dt><T>Latest verified check</T></dt><dd>{h?<><Status value={h.status}/><p>{date(h.checkedAt)}</p><small>{h.durationMs} ms · {h.attempts} <T>attempts</T></small></>:<T>Not measured</T>}</dd></div><div><dt><T>Database</T></dt><dd>{h?<Status value={h.database}/>:<T>Not measured</T>}</dd></div><div><dt><T>Private storage bucket</T></dt><dd>{h?<Status value={h.storage}/>:<T>Not measured</T>}</dd></div><div><dt><T>AI integration</T></dt><dd>{h?<Status value={h.ai}/>:<T>Not measured</T>}</dd></div></dl>
    <p><T>Last successful check</T>: {data.lastSuccessfulCheck?date(data.lastSuccessfulCheck):<T>Not measured</T>}</p><details><summary><T>Verified health history</T></summary>{data.healthHistory.map((check,index)=><p key={index}>{date(check.checkedAt)} · <Status value={check.status}/> · {check.durationMs} ms</p>)}</details>
    <p className="portal-muted"><T>Liveness confirms this application responds. Readiness probes the database with a timeout; it does not call the AI model or confirm external delivery.</T></p>
    <p><T>Independent monitoring and operational alert delivery require external verification. Email and SMS delivery: not configured.</T></p><dl><dt><T>Dependency probe configuration</T></dt><dd><Status value={data.monitoring?.dependencyProbe??'not_configured'}/></dd><dt><T>Document scanner configuration</T></dt><dd><Status value={data.monitoring?.scanner??'not_configured'}/></dd></dl><p><T>Keep documents blocked until a genuine scanner succeeds. A configured credential does not prove monitoring, scanning or recipient delivery.</T></p>
   </Panel>
   <Panel title="Inquiry workflow" actions={<button className="portal-button secondary" onClick={()=>setForm({title:'Set operational thresholds',action:'operations_policy',initial:data.policy,fields:([['unassignedHours','Unassigned threshold (hours)'],['supportHours','Support threshold (hours)'],['providerHours','Provider threshold (hours)'],['patientHours','Patient threshold (hours)']] as const).map(([key,label])=>({key,label,type:'number',min:1} as Field)).concat(confirmation)})}><T>Edit thresholds</T></button>}>
    <Counts items={[["New in 24 hours",data.inquiries.new24h],["Active inquiries",data.inquiries.active],["Unassigned",data.inquiries.unassigned],["Awaiting Support",data.inquiries.support],["Awaiting provider",data.inquiries.provider],["Awaiting patient",data.inquiries.patient],["Overdue",data.inquiries.overdue]]}/>
   </Panel>
   <Queue admin onAction={setForm} filterValue={queueFilter} onFilterChange={setQueueFilter}/>
   <Panel title="Recent failures and recovery">
    <p className="portal-muted"><T>Last 24 hours, latest 30 requests with failures or execution limits. Reconciliation checks the original command receipt; it never resends a message or re-shares a document.</T></p>
    {data.failures.length?<div className="operations-list">{data.failures.map(e=>{const job=data.recoveries.find(j=>j.source_event_id===e.id);return <article className="operations-row" key={e.id}><div><strong><T>{e.kind==='ai'?'AI execution':'Inquiry command'}</T></strong><p><Status value={e.outcome}/> <Status value={e.category}/></p><details><summary><T>Details</T></summary><p className="operations-id"><T>Correlation ID</T>: {e.correlationId}</p><p>{date(e.occurredAt)} · {e.durationMs} ms</p></details></div><div>{job?<><Status value={job.status}/><p>{job.attempt_count}/3 <T>attempts</T></p><p><T>{({commit_confirmed:'Original action saved; receipt confirmed.',commit_unconfirmed:'Original action not confirmed.',not_retryable:'Permanent failure; do not retry.',attempt_limit:'Maximum reconciliation attempts reached.'} as Record<string,string>)[job.result_code]}</T></p>{job.next_attempt_at&&<small><T>Next eligible check</T>: {date(job.next_attempt_at)}</small>}</>:<T>Not reconciled</T>}</div>{e.kind==='inquiry'&&e.operationId&&(!job||job.status==='unknown')&&<button className="portal-button secondary" disabled={Boolean(job?.next_attempt_at&&Date.parse(job.next_attempt_at)>Date.parse(data.asOf))} onClick={()=>setForm({title:'Reconcile uncertain inquiry outcome',action:'operations_reconcile',input:{eventId:e.id},fields:[confirmation]})}><T>Check original receipt</T></button>}</article>;})}</div>:<Empty title="No recorded request failures in this window"/>}
   </Panel>
   <Panel title="Notification delivery"><Counts items={[["Created in 24 hours",data.notifications.created],["Read from this cohort",data.notifications.read],["Unread from this cohort",data.notifications.unread]]}/><p><T>In-app records are created atomically with their source action. Unread does not mean queued. External delivery attempts and confirmation are not measured because no email or SMS transport is configured.</T></p></Panel>
   <Panel title="AI execution observability"><Counts items={[["Runs in 24 hours",data.ai.runs],["Finished runs",data.ai.finished],["Failed runs",data.ai.failed],["Unfinished for over 5 minutes",data.ai.stalled],["Observed request failures",data.ai.requestFailures],["Completed after model retry",data.ai.recovered]]}/><p className="portal-muted"><T>Unfinished runs are signals to investigate, not confirmed failures. Request telemetry starts with this release; earlier retry outcomes are not measured.</T></p><details><summary><T>Recent execution diagnostics</T></summary>{data.runs.length?<div className="operations-list">{data.runs.map(r=><article className="operations-row" key={r.id}><div><code className="operations-id">{r.id}</code><p>{date(r.createdAt)}</p></div><Status value={r.status}/><span>{r.durationMs===null?<T>Not measured</T>:`${r.durationMs} ms`}</span>{r.category&&<Status value={r.category}/>}</article>)}</div>:<Empty title="No executions in this window"/>}<h3><T>Model attempts</T></h3>{data.events.filter(e=>e.kind==='ai').map(e=><p key={e.id} className="operations-id">{e.executionId??e.correlationId}: {e.retryCount} <T>retries</T> · {e.modelFailures.map((c,index)=><Status key={index} value={c}/>)} · <T>{e.recovered?'Completed after model retry':'No confirmed retry recovery'}</T></p>)}<h3><T>Failed tools</T></h3>{data.tools.map(t=><p key={t.id}><code>{t.tool}</code> · <Status value={t.category}/> · <code className="operations-id">{t.runId}</code></p>)}</details></Panel>
   <Panel title="Operational incidents" actions={<button className="portal-button secondary" onClick={incident}><T>Open incident</T></button>}>
    <p className="portal-muted"><T>Severity describes operational impact. Resolution notes use structured categories to keep patient information out of incident records.</T></p>
    <p><T>Incidents without an active authorized owner require escalation to the project owner.</T> <LocalNumber value={data.incidents.unowned??0}/></p>{data.incidentRows.length?<div className="operations-list">{data.incidentRows.map(i=><article className="operations-row" key={i.id}><div><strong><T>{label(i.category)}</T></strong><p><Status value={i.severity}/> <Status value={i.status}/></p><details><summary><T>Details</T></summary><p className="operations-id"><T>Incident ID</T>: {i.id}</p><p className="operations-id"><T>Admin owner ID</T>: {i.owner_id??'—'}</p><p>{date(i.created_at)}</p>{i.resolution_note&&<p><T>{label(i.resolution_note)}</T></p>}</details></div>{i.status!=='closed'&&<button className="portal-button secondary" onClick={()=>setForm({title:'Update operational incident',action:'operations_incident_update',input:{incidentId:i.id,expectedRevision:i.revision,status:({open:'acknowledged',acknowledged:'investigating',investigating:'resolved',resolved:'closed'} as Record<string,string>)[i.status]},initial:{ownerId:i.owner_id??context.userId,resolution:i.resolution_note??'investigation_completed'},fields:[{key:'ownerId',label:'Admin owner',type:'select',catalog:'staff',catalogParams:{q:'admin'}},...(['investigating','resolved'].includes(i.status)?[{key:'resolution',label:'Resolution note',type:'select' as const,options:resolutionCodes}]:[]),confirmation]})}><T>{({open:'Acknowledge',acknowledged:'Investigate',investigating:'Resolve',resolved:'Close incident'} as Record<string,string>)[i.status]}</T></button>}</article>)}</div>:<Empty title="No operational incidents recorded"/>}
   </Panel>
   <Panel title="Provider pilot readiness"><Counts items={[["Registered organizations",data.providers.registered],["Awaiting verification",data.providers.awaitingVerification],["Awaiting ownership",data.providers.awaitingOwnership],["Approved without active team",data.providers.withoutTeam],["Organizations with published listings",data.providers.withPublishedListings],["Connected organizations",data.providers.connected],["Provider response observed",data.providers.responseObserved]]}/><p><T>A real provider pilot requires authorized onboarding and a genuine acceptance test. Registration or local QA does not establish participation.</T></p>{network.error?<ErrorPanel message={network.error}/>:network.loading?<Loading/>:network.data?.rows.filter(r=>r.origin==='provider_submitted').map(r=><details key={r.id}><summary>{r.name}</summary><p><Status value={r.verificationStatus}/></p><p><T>{networkNextStep(r)}</T></p><p><T>Active team members</T>: {r.activeMembers} · <T>Owned canonical listings</T>: {r.ownedListings} · <T>Published owned listings</T>: {r.publishedListings}</p><p><T>{r.canReceiveInquiries?'Ready for patient authorization':'Support coordination available'}</T></p><p><T>{data.pilotRows.find(p=>p.organizationId===r.id)?.responseObserved?'Consented provider response recorded.':'No current consented provider response recorded.'}</T></p><p><T>{data.pilotRows.find(p=>p.organizationId===r.id)?.notificationCreated?'In-app inquiry notification created.':'No in-app inquiry notification recorded.'}</T></p><p><T>{data.pilotRows.find(p=>p.organizationId===r.id)?.acceptanceRecorded?'Pilot acceptance: recorded by Admin against a consented inquiry.':'Pilot acceptance: not recorded. External notification capability: not configured.'}</T></p>{r.canReceiveInquiries&&!data.pilotRows.find(p=>p.organizationId===r.id)?.acceptanceRecorded&&<button className="portal-button secondary" onClick={()=>setForm({title:'Record genuine pilot acceptance',action:'operations_accept_pilot',input:{organizationId:r.id},fields:[{key:'caseId',label:'Consented pilot inquiry ID'},{key:'realParticipantConfirmed',label:'A real authorized provider participated in this acceptance test',type:'checkbox'},confirmation]})}><T>Record genuine pilot acceptance</T></button>}</details>)}</Panel>
  </>}
  {form&&<Modal title={form.title} onClose={()=>setForm(null)}><p><T>{form.action==='operations_accept_pilot'?'Record genuine participation after reviewing the authorized inquiry, actual provider response and in-app notification. Current authority and patient consent are checked again.':'Review the current state before confirming. This action is audited.'}</T></p><CommandForm key={form.action+JSON.stringify(form.input)} action={form.action} input={form.input} fields={form.fields} initial={form.initial} onDone={()=>setForm(null)} submit="Confirm action"/></Modal>}
 </div>;
}
