-- Isolated QA contract tests. Real engine tests are separate; never run in production.
\set ON_ERROR_STOP on
begin;
do $$begin if current_database() not like 'production_catalog_%' then raise exception 'Disposable catalog QA required';end if;end;$$;
create function pg_temp.s_assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL %',label;end if;raise notice 'PASS %',label;end;$$;
create function pg_temp.s_denied(stmt text,code text) returns void language plpgsql as $$begin begin execute stmt;exception when others then if position(code in sqlerrm)>0 then raise notice 'PASS denial %',code;return;end if;raise;end;raise exception 'FAIL expected denial';end;$$;
create temp table sj(k text primary key,id uuid,v jsonb);
insert into sj values('job',null,public.document_security_register('care-documents','QA-security/opaque.pdf',repeat('1',64),20,'application/pdf'));
update sj set id=(v->>'id')::uuid;
select pg_temp.s_assert(public.document_security_register('care-documents','QA-security/opaque.pdf',repeat('1',64),20,'application/pdf')->>'id'=(select id::text from sj where k='job'),'registration retry keeps one job');
select pg_temp.s_denied($s$select public.document_security_register('care-documents','QA-security/opaque.pdf',repeat('2',64),20,'application/pdf')$s$,'DOCUMENT_SECURITY_CONFLICT');
select pg_temp.s_denied($s$select public.document_security_assert_clean('care-documents','QA-security/opaque.pdf')$s$,'DOCUMENT_SECURITY_BLOCKED');
select pg_temp.s_denied(format('select public.document_security_ready(%L)',(select id from sj where k='job')),'DOCUMENT_SECURITY_NOT_STORED');
insert into storage.objects(bucket_id,name) values('care-documents','QA-security/opaque.pdf');
select public.document_security_ready((select id from sj where k='job'));
insert into sj values('claim',null,public.document_security_claim());
select pg_temp.s_assert((select v->>'id'=(select id::text from sj where k='job') and v->>'state'='scanning' from sj where k='claim'),'one leased scan job claimed');
select pg_temp.s_assert(public.document_security_claim() is null,'duplicate worker cannot claim a live lease');
select pg_temp.s_denied(format('select public.document_security_result(%L,%L,%L)',(select id from sj where k='job'),gen_random_uuid(),'{}'),'DOCUMENT_SECURITY_LEASE');
select pg_temp.s_denied(format('select public.document_security_result(%L,%L,%L)',(select id from sj where k='job'),(select v->>'lease' from sj where k='claim'),'{"state":"clean","checksum":"bad"}'),'DOCUMENT_SECURITY_RESULT');
insert into sj values('result',null,jsonb_build_object('state','clean','checksum',repeat('1',64),'engine','ClamAV','engineVersion','1.4.6','signatureVersion','123','signatureAt',now(),'policyVersion','clamav-v1'));
select public.document_security_result((select id from sj where k='job'),(select (v->>'lease')::uuid from sj where k='claim'),(select v from sj where k='result'));
select pg_temp.s_assert(public.document_security_assert_clean('care-documents','QA-security/opaque.pdf')->>'checksum'=repeat('1',64),'only verified checksum clean proof accepted');
select public.document_security_result((select id from sj where k='job'),(select (v->>'lease')::uuid from sj where k='claim'),(select v from sj where k='result'));
select pg_temp.s_assert((select count(*)=1 from public.audit_events where entity_id=(select id from sj where k='job') and metadata->>'state'='clean'),'duplicate ACK has one audit');
select pg_temp.s_assert(not exists(select 1 from public.audit_events where entity_id=(select id from sj where k='job') and metadata::text~'opaque|checksum|filename|path|token'),'security audits contain no sensitive metadata');
-- Direct storage is denied even after a clean contract fixture; no user signing bypass.
set local role authenticated;
select pg_temp.s_assert((select count(*)=0 from storage.objects where name='QA-security/opaque.pdf'),'direct storage and signing SELECT blocked');
reset role;
select pg_temp.s_assert(not has_table_privilege('authenticated','public.document_security_jobs','update'),'client cannot edit scan states');
select pg_temp.s_assert(not has_function_privilege('authenticated','public.document_security_result(uuid,uuid,jsonb)','execute'),'client cannot forge verdict');
select pg_temp.s_assert(not has_function_privilege('authenticated','private.inquiry_command_before_security(text,jsonb)','execute'),'old command cannot bypass security wrapper');
select pg_temp.s_assert(not has_function_privilege('authenticated','private.inquiry_document_delivery_before_security(uuid)','execute'),'old delivery cannot bypass wrapper');
select pg_temp.s_assert(not has_function_privilege('authenticated','private.portal_command_before_security(text,jsonb)','execute'),'old provider command cannot bypass wrapper');
select pg_temp.s_assert(not exists(select 1 from pg_policy where polname in ('inquiry_documents_read','inquiry_document_grants_read','inquiry_private_document_audit') and pg_get_expr(polqual,polrelid) like '%before_security%'),'all document and audit policies reference the authorized wrapper');
set local role authenticated;
select pg_temp.s_denied('select public.document_security_review()','PORTAL_DENIED');
reset role;
-- Malware quarantine and bounded interrupted recovery use contract fixtures only.
update public.document_security_jobs set state='scanning',scanned_at=null,lease_until=now()+interval '1 minute' where id=(select id from sj where k='job');
select public.document_security_result((select id from sj where k='job'),(select (v->>'lease')::uuid from sj where k='claim'),(select jsonb_set(v,'{state}','"quarantined"') from sj where k='result'));
select pg_temp.s_denied($s$select public.document_security_assert_clean('care-documents','QA-security/opaque.pdf')$s$,'DOCUMENT_SECURITY_BLOCKED');
update public.document_security_jobs set state='scanning',attempts=2,lease_until=now()-interval '1 second',next_attempt_at=now()-interval '1 second' where id=(select id from sj where k='job');
update sj set v=public.document_security_claim() where k='claim';
select pg_temp.s_assert((select attempts=3 from public.document_security_jobs where id=(select id from sj where k='job')),'expired scan recovered with bounded third attempt');
update public.document_security_jobs set lease_until=now()-interval '1 second' where id=(select id from sj where k='job');
select pg_temp.s_assert(public.document_security_claim() is null,'attempt exhaustion does not loop');
select pg_temp.s_assert((select state='scan_failed' and failure_category='lease_expired' from public.document_security_jobs where id=(select id from sj where k='job')),'exhausted lease persisted blocked');
select pg_temp.s_denied($s$select public.document_security_assert_clean('care-documents','missing.pdf')$s$,'DOCUMENT_SECURITY_BLOCKED');
select public.document_security_retire('care-documents','QA-security/opaque.pdf');
select pg_temp.s_assert((select not ready and lease is null from public.document_security_jobs where id=(select id from sj where k='job')),'retirement invalidates all pending work');
-- Explicit security administrator recovery cannot override a verdict.
insert into sj(k,id) values('admin',gen_random_uuid()),('support',gen_random_uuid());
insert into auth.users(id,email) select id,'scan-'||id::text||'@qa.invalid' from sj where k in ('admin','support');
insert into public.staff_roles(user_id,role) select id,case k when 'admin' then 'super_admin' else 'support_agent' end from sj where k in ('admin','support');
grant select on sj to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from sj where k='support'),true);
select pg_temp.s_denied('select public.document_security_review()','PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from sj where k='admin'),true);
select pg_temp.s_denied(format('select public.document_security_review(%L,true,true)',(select id from sj where k='job')),'DOCUMENT_SECURITY_RETRY_DENIED');
reset role;
update public.document_security_jobs set state='scan_failed',failure_category='timeout',ready=true where id=(select id from sj where k='job');
set local role authenticated;
select pg_temp.s_denied(format('select public.document_security_review(%L,true,false)',(select id from sj where k='job')),'DOCUMENT_SECURITY_RETRY_DENIED');
select public.document_security_review((select id from sj where k='job'),true,true);
select pg_temp.s_denied(format('select public.document_security_review(%L,true,true)',(select id from sj where k='job')),'DOCUMENT_SECURITY_RETRY_DENIED');
reset role;
select pg_temp.s_assert((select state='pending_scan' and attempts=0 from public.document_security_jobs where id=(select id from sj where k='job')),'authorized retry only queues a new real scan');
update sj set v=public.document_security_claim() where k='claim';
select pg_temp.s_denied(format('select public.document_security_result(%L,%L,%L)',(select id from sj where k='job'),(select v->>'lease' from sj where k='claim'),(select jsonb_set(v,'{signatureAt}',to_jsonb(now()-interval '49 hours')) from sj where k='result')),'DOCUMENT_SECURITY_RESULT');
select public.document_security_result((select id from sj where k='job'),(select (v->>'lease')::uuid from sj where k='claim'),jsonb_build_object('state','scan_failed','checksum',repeat('1',64),'category','timeout'));
select pg_temp.s_assert(public.document_security_claim() is null,'failed scan observes persisted retry backoff');
select pg_temp.s_assert((select state='scan_failed' and next_attempt_at>now() from public.document_security_jobs where id=(select id from sj where k='job')),'timeout stays blocked with a persisted retry schedule');
insert into sj(k,id) values('case',gen_random_uuid());
insert into public.cases(id,owner_id,title) select id,(select id from sj where k='admin'),'LOCAL scan metadata QA' from sj where k='case';
insert into public.case_documents(case_id,uploaded_by,title,document_type,storage_path,mime_type,file_size_bytes) select id,(select id from sj where k='admin'),'QA metadata','summary','QA-security/opaque.pdf','application/pdf',20 from sj where k='case';
set local role authenticated;
select pg_temp.s_assert((select count(*)=0 from public.case_documents where case_id=(select id from sj where k='case')),'even authorized owner cannot supply unscanned file metadata to AI');
reset role;
-- Contract proof only, not a malware-scanner test.
update public.document_security_jobs set state='clean',scanned_at=now(),engine_version='1.4.6',signature_at=now() where id=(select id from sj where k='job');
set local role authenticated;
select pg_temp.s_assert((select count(*)=1 from public.case_documents where case_id=(select id from sj where k='case')),'clean metadata retains existing case authorization');
reset role;
rollback;
