-- LOCAL QA ONLY. No claims of real provider participation. Roll back by default.
\set ON_ERROR_STOP on
begin;
do $$begin if current_database() not like 'production_catalog_%' then raise exception 'Disposable database required';end if;end;$$;
create temporary table net(k text primary key,id uuid default gen_random_uuid(),v jsonb);
insert into net(k) values('admin'),('provider'),('editor'),('other'),('patient'),('support'),('document');
insert into auth.users(id,email) select id,'network-'||k||'@qa.invalid' from net where k<>'document';
insert into public.staff_roles(user_id,role) select id,case k when 'admin' then 'super_admin' else 'support_agent' end from net where k in ('admin','support');
grant all on net to authenticated;grant select on net to anon;
create function pg_temp.n_assert(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',msg;end if;raise notice 'PASS: %',msg;end;$$;
create function pg_temp.n_denied(stmt text,code text) returns void language plpgsql as $$begin begin execute stmt;exception when others then if position(code in sqlerrm)>0 then raise notice 'PASS: denied %',code;return;end if;raise;end;raise exception 'FAIL: operation permitted';end;$$;
create function pg_temp.n_input(extra jsonb default '{}') returns jsonb language sql as $$select jsonb_build_object('organizationId',(select id from net where k='org'),'operationId',gen_random_uuid(),'confirmed',true)||extra;$$;
create function pg_temp.n_case(extra jsonb default '{}') returns jsonb language sql as $$select jsonb_build_object('caseId',(select id from net where k='case'),'operationId',gen_random_uuid())||extra;$$;
\ir pg-catalog-reference-fixtures.sql
select pg_temp.qa_publish_references((select id from net where k='admin'));
insert into net(k,v) select 'baseline_hospitals',to_jsonb(count(*)) from public.hospitals where private.catalog_public_visible('hospital',id);
\ir pg-network-reference-fixtures.sql
insert into net(k,v) values('reference',pg_temp.qa_network_reference((select id from net where k='admin'))),('unrelated_reference',pg_temp.qa_network_reference((select id from net where k='admin')));
insert into net(k,id) select 'hospital',(v->>'hospitalId')::uuid from net where k='reference';
select pg_temp.n_assert(private.provider_connectivity('hospital',(select (v->>'hospitalId')::uuid from net where k='unrelated_reference'))='no_owner','reference-only listing has an executable honest no-owner Support state');
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from net where k='provider'),true);
insert into net(k,id) select 'org',(public.portal_command('create_organization','{"name":"LOCAL NETWORK Provider","providerType":"hospital","sourceKind":"first_party"}')->>'id')::uuid;
select pg_temp.n_assert(public.portal_network_readiness((select id from net where k='org'))->'rows'->0->>'verificationStatus'='not_submitted','registration grants a draft workspace, not authority');
select pg_temp.n_assert(public.inquiry_target('hospital',(select id from net where k='hospital'))->>'organizationId' is null,'published reference has no invented operational owner');
select pg_temp.n_denied(format('select public.portal_network_command(''assign_listing_ownership'',%L)',pg_temp.n_input(jsonb_build_object('entityKind','hospital','entityId',(select id from net where k='hospital'),'reason','Unrelated self-claim.'))::text),'PORTAL_DENIED');
select pg_temp.n_denied(format('select public.portal_network_command(''review_organization_verification'',%L)',pg_temp.n_input(jsonb_build_object('requestId',gen_random_uuid(),'status','approved','reason','Self-approval must fail.'))::text),'PORTAL_DENIED');
insert into net(k,id) select 'draft',(public.portal_command('save_record',jsonb_build_object('organizationId',(select id from net where k='org'),'kind','organization','name','LOCAL NETWORK Draft','data',jsonb_build_object('cityId',(select id from public.cities where slug='mumbai'),'description','Local private draft.','email','authority@qa.invalid','phone','00000000')))->>'id')::uuid;
reset role;
insert into storage.objects(bucket_id,name) select 'provider-documents',(select id::text from net where k='org')||'/'||id::text from net where k='document';
set local role authenticated;
select public.portal_command('register_document',jsonb_build_object('organizationId',(select id from net where k='org'),'documentId',(select id from net where k='document'),'name','LOCAL NETWORK authority.pdf','documentType','supporting_evidence','storagePath',(select id::text from net where k='org')||'/'||(select id::text from net where k='document'),'mimeType','application/pdf','sizeBytes',20));
insert into net(k,v) values('submit',pg_temp.n_input(jsonb_build_object('documentId',(select id from net where k='document'),'hospitalId',(select id from net where k='hospital'),'legalName','Local authorized organization','contactName','Local representative','contactEmail','authority@qa.invalid','contactPhone','00000000','declaration','Local QA declaration, no real organization represented.')));
insert into net(k,id) select 'request',(public.portal_network_command('submit_organization_verification',(select v from net where k='submit'))->>'requestId')::uuid;
select pg_temp.n_assert(public.portal_network_command('submit_organization_verification',(select v from net where k='submit'))->>'requestId'=(select id::text from net where k='request'),'submission retry returns same authority request');
select pg_temp.n_assert((select count(*)=1 from public.organization_verification_requests where organization_id=(select id from net where k='org')),'submission retry does not duplicate review requests');
select pg_temp.n_denied(format('select public.portal_network_command(''submit_organization_verification'',%L)',((select v from net where k='submit')||'{"legalName":"Changed retry"}')::text),'INQUIRY_RETRY_CONFLICT');
select set_config('request.jwt.claim.sub',(select id::text from net where k='support'),true);
select pg_temp.n_assert((select count(*)=0 from public.organization_verification_requests),'Support cannot read authority contact details or evidence');
select pg_temp.n_assert(public.portal_network_readiness((select id from net where k='org'))->'rows'->0->>'verificationStatus'='submitted','Support can read safe factual readiness');
select set_config('request.jwt.claim.sub',(select id::text from net where k='other'),true);
select pg_temp.n_assert((select count(*)=0 from public.organization_verification_requests),'another organization cannot read authority requests');
select pg_temp.n_denied(format('select public.portal_network_readiness(%L)',(select id from net where k='org')),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from net where k='admin'),true);
select public.portal_network_command('review_organization_verification',pg_temp.n_input(jsonb_build_object('requestId',(select id from net where k='request'),'status','changes_requested','reason','Local reviewer requests better authority clarification.')));
select set_config('request.jwt.claim.sub',(select id::text from net where k='provider'),true);
update net set id=(public.portal_network_command('submit_organization_verification',(select v from net where k='submit')||jsonb_build_object('operationId',gen_random_uuid(),'declaration','Local clarified authority declaration for isolated QA only.'))->>'requestId')::uuid where k='request';
select pg_temp.n_assert((select count(*)=2 from public.organization_verification_requests where organization_id=(select id from net where k='org')),'changes requested permits a new immutable review request and retains history');
select set_config('request.jwt.claim.sub',(select id::text from net where k='admin'),true);
insert into net(k,v) values('review',pg_temp.n_input(jsonb_build_object('requestId',(select id from net where k='request'),'status','approved','reason','Isolated QA authority review.','contactConfirmation','Local QA contact verification only.')));
select pg_temp.n_denied(format('select public.portal_network_command(''review_organization_verification'',%L)',(select v::text from net where k='review')),'PORTAL_EVIDENCE_REQUIRED');
select public.portal_command('review_document',jsonb_build_object('documentId',(select id from net where k='document'),'status','approved','message','Local private authority fixture reviewed.'));
select pg_temp.n_denied(format('select public.portal_network_command(''review_organization_verification'',%L)',((select v from net where k='review')-'contactConfirmation')::text),'PORTAL_CONTACT_CONFIRMATION_REQUIRED');
select pg_temp.n_denied(format('select public.portal_network_command(''review_organization_verification'',%L)',((select v from net where k='review')||'{"confirmed":false}')::text),'PORTAL_CONFIRMATION_REQUIRED');
select public.portal_network_command('review_organization_verification',(select v from net where k='review'));
select pg_temp.n_assert(public.inquiry_target('hospital',(select id from net where k='hospital'))->>'organizationId' is null,'authority approval alone does not connect or publish a listing');
select pg_temp.n_denied(format('select public.portal_network_command(''assign_listing_ownership'',%L)',pg_temp.n_input(jsonb_build_object('entityKind','hospital','entityId',(select (v->>'hospitalId')::uuid from net where k='unrelated_reference'),'reason','Unrelated scope must fail.'))::text),'PORTAL_OWNERSHIP_SCOPE');
select public.portal_network_command('assign_listing_ownership',pg_temp.n_input(jsonb_build_object('entityKind','hospital','entityId',(select id from net where k='hospital'),'recordId',(select id from net where k='draft'),'reason','Assign exact reviewed canonical hospital.')));
select public.portal_network_command('assign_listing_ownership',pg_temp.n_input(jsonb_build_object('entityKind','doctor','entityId',(select (v->>'doctorId')::uuid from net where k='reference'),'reason','Scoped local affiliated doctor.')));
select public.portal_network_command('assign_listing_ownership',pg_temp.n_input(jsonb_build_object('entityKind','package','entityId',(select (v->>'packageId')::uuid from net where k='reference'),'reason','Scoped local hospital package.')));
reset role;
\ir pg-network-authority-fixtures.sql
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from net where k='other'),true);
insert into net(k,id) select 'competing_org',(public.portal_command('create_organization','{"name":"LOCAL competing claimant","providerType":"hospital","sourceKind":"first_party"}')->>'id')::uuid;
reset role;
select pg_temp.qa_approve_authority((select id from net where k='competing_org'),(select id from net where k='other'),(select id from net where k='admin'),(select id from net where k='hospital'));
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from net where k='admin'),true);
select pg_temp.n_denied(format('select public.portal_network_command(''assign_listing_ownership'',%L)',pg_temp.n_input(jsonb_build_object('organizationId',(select id from net where k='competing_org'),'entityKind','hospital','entityId',(select id from net where k='hospital'),'reason','Competing claim must not silently transfer.'))::text),'PORTAL_OWNERSHIP_CONFLICT');
select pg_temp.n_assert((select canonical_id=(select id from net where k='hospital') and published_revision is null from public.provider_records where id=(select id from net where k='draft')),'ownership binds the private draft without publishing it');
select pg_temp.n_assert(public.portal_network_readiness((select id from net where k='org'))->'rows'->0->>'canReceiveInquiries'='true','verified member and published canonical ownership enable consented coordination');
select set_config('request.jwt.claim.sub',(select id::text from net where k='provider'),true);
insert into net(k,id) select 'submission',(public.portal_command('submit',jsonb_build_object('organizationId',(select id from net where k='org')))->>'id')::uuid;
select pg_temp.n_denied(format('select public.portal_publication_command(''publish_submission'',%L)',jsonb_build_object('submissionId',(select id from net where k='submission'))::text),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from net where k='admin'),true);
select public.portal_review_command('review_section',jsonb_build_object('submissionId',(select id from net where k='submission'),'recordId',(select id from net where k='draft'),'expectedRevision',1,'status','approved'));
select public.portal_command('review_field',jsonb_build_object('submissionId',(select id from net where k='submission'),'recordId',(select id from net where k='draft'),'field','name','status','verified','documentId',(select id from net where k='document'),'evidence','Local exact canonical identity evidence only.'));
select public.portal_command('review_submission',jsonb_build_object('submissionId',(select id from net where k='submission'),'status','approved'));
select public.portal_publication_command('publish_submission',jsonb_build_object('submissionId',(select id from net where k='submission')));
select pg_temp.n_assert((select hospital_id=(select id from net where k='hospital') from public.organizations where id=(select id from net where k='org')),'reviewed first-party publication preserves the canonical reference identity');

reset role;
set local role anon;
select pg_temp.n_assert((select count(*)=(select v::integer+2 from net where k='baseline_hospitals') from public.hospitals),'ownership and first-party publication do not duplicate canonical hospitals');
select pg_temp.n_assert(exists(select 1 from public.packages where id=(select (v->>'packageId')::uuid from net where k='reference')) and exists(select 1 from public.doctors where id=(select (v->>'doctorId')::uuid from net where k='reference')),'reference publisher child listings survive operational owner publication');
select pg_temp.n_assert((select source_kind='first_party' from public.hospitals where id=(select id from net where k='hospital')),'only explicit first-party publication changes canonical provenance');
select pg_temp.n_denied('select * from public.organization_verification_requests','permission denied');
select pg_temp.n_denied('select * from public.provider_listing_ownership','permission denied');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from net where k='provider'),true);
insert into net(k,id) select 'invite',(public.portal_command('invite_member',jsonb_build_object('organizationId',(select id from net where k='org'),'operationId',gen_random_uuid(),'email','network-editor@qa.invalid','role','provider_editor'))->>'id')::uuid;
select set_config('request.jwt.claim.sub',(select id::text from net where k='other'),true);
select pg_temp.n_denied(format('select public.portal_command(''accept_invite'',%L)',jsonb_build_object('inviteId',(select id from net where k='invite'))::text),'PORTAL_INVITE_INVALID');
select set_config('request.jwt.claim.sub',(select id::text from net where k='editor'),true);
select public.portal_command('accept_invite',jsonb_build_object('inviteId',(select id from net where k='invite'),'operationId',gen_random_uuid()));
select pg_temp.n_denied(format('select public.portal_command(''invite_member'',%L)',jsonb_build_object('organizationId',(select id from net where k='org'),'email','network-other@qa.invalid','role','provider_admin')::text),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from net where k='patient'),true);
insert into net(k,id) select 'case',(public.inquiry_command('create',jsonb_build_object('operationId',gen_random_uuid(),'entityKind','hospital','entityId',(select id from net where k='hospital'),'expectedPublishedRevision',(public.inquiry_target('hospital',(select id from net where k='hospital'))->>'publishedRevision')::integer,'source','hospital_detail','title','LOCAL NETWORK controlled inquiry','objective','A local administrative coordination question.','consent',true,'reviewed',true))->>'id')::uuid;
select set_config('request.jwt.claim.sub',(select id::text from net where k='editor'),true);
select pg_temp.n_denied(format('select public.inquiry_context(%L)',(select id from net where k='case')),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from net where k='patient'),true);
select public.inquiry_command('share_provider',pg_temp.n_case(jsonb_build_object('organizationId',(select id from net where k='org'),'purpose','Local consent to named recipient.','confirmed',true)));
select set_config('request.jwt.claim.sub',(select id::text from net where k='support'),true);
select public.inquiry_command('update',pg_temp.n_case(jsonb_build_object('expectedRevision',(public.inquiry_context((select id from net where k='case'))->'case'->>'revision')::integer,'assignedTo',(select id from net where k='support'),'status','in_progress')));
select pg_temp.n_assert(public.inquiry_context((select id from net where k='case'))->'providerCoordination'->>'readiness'='connected','assigned Support sees actual current connectivity');
select set_config('request.jwt.claim.sub',(select id::text from net where k='editor'),true);
select pg_temp.n_assert(public.inquiry_context((select id from net where k='case'))->>'role'='provider','authorized team receives the persisted consented inquiry');
insert into net(k,v) values('response',pg_temp.n_case('{"status":"responded","body":"LOCAL QA response from the authorized team. No appointment or treatment is confirmed.","confirmed":true}'));
select public.inquiry_command('provider_response',(select v from net where k='response'));
select public.inquiry_command('provider_response',(select v from net where k='response'));
select set_config('request.jwt.claim.sub',(select id::text from net where k='patient'),true);
select pg_temp.n_assert(public.inquiry_context((select id from net where k='case'))->'providerCoordination'->'latestResponse'->>'body'='LOCAL QA response from the authorized team. No appointment or treatment is confirmed.','patient reads the actual attributable response after a fresh role context');
select set_config('request.jwt.claim.sub',(select id::text from net where k='admin'),true);
-- Operational acceptance records verify current authority, actual response and actual in-app notification.
insert into net(k,v) values('pilot_acceptance',jsonb_build_object('operationId',gen_random_uuid(),'confirmed',true,'realParticipantConfirmed',true,'organizationId',(select id from net where k='org'),'caseId',(select id from net where k='case')));
select pg_temp.n_denied(format('select public.operations_command(''operations_accept_pilot'',%L)',((select v from net where k='pilot_acceptance')||'{"realParticipantConfirmed":false}')::text),'PORTAL_EVIDENCE_REQUIRED');
select public.operations_command('operations_accept_pilot',(select v from net where k='pilot_acceptance'));
select public.operations_command('operations_accept_pilot',(select v from net where k='pilot_acceptance'));
select pg_temp.n_assert(exists(select 1 from jsonb_array_elements(public.operations_overview()->'pilotRows')r where r->>'organizationId'=(select id::text from net where k='org') and r->>'acceptanceRecorded'='true'),'local acceptance attestation is backed by current consented response and notification, not registration');
select public.portal_command('organization_status',jsonb_build_object('organizationId',(select id from net where k='org'),'status','suspended','reason','Local operational suspension test.','confirmed',true,'operationId',gen_random_uuid()));
select pg_temp.n_assert(not exists(select 1 from jsonb_array_elements(public.operations_overview()->'pilotRows')r where r->>'organizationId'=(select id::text from net where k='org') and r->>'acceptanceRecorded'='true'),'suspended authority invalidates operational acceptance readiness');
select set_config('request.jwt.claim.sub',(select id::text from net where k='editor'),true);
select pg_temp.n_denied(format('select public.inquiry_context(%L)',(select id from net where k='case')),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from net where k='admin'),true);
select public.portal_command('organization_status',jsonb_build_object('organizationId',(select id from net where k='org'),'status','active','reason','Local suspension test resolved.','confirmed',true,'operationId',gen_random_uuid()));
select public.portal_command('review_document',jsonb_build_object('documentId',(select id from net where k='document'),'status','expired','message','Local current-evidence expiry test.'));
select set_config('request.jwt.claim.sub',(select id::text from net where k='editor'),true);
select pg_temp.n_denied(format('select public.inquiry_context(%L)',(select id from net where k='case')),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from net where k='admin'),true);
select public.portal_command('review_document',jsonb_build_object('documentId',(select id from net where k='document'),'status','approved','message','Local evidence restoration, isolated QA only.'));
select set_config('request.jwt.claim.sub',(select id::text from net where k='other'),true);
select pg_temp.n_denied(format('select public.inquiry_context(%L)',(select id from net where k='case')),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from net where k='provider'),true);
select pg_temp.n_denied(format('select public.portal_command(''update_member'',%L)',jsonb_build_object('organizationId',(select id from net where k='org'),'userId',(select id from net where k='editor'),'role','provider_editor','active',false)::text),'PORTAL_CONFIRMATION_REQUIRED');
select public.portal_command('update_member',jsonb_build_object('organizationId',(select id from net where k='org'),'userId',(select id from net where k='editor'),'role','provider_editor','active',false,'confirmed',true,'operationId',gen_random_uuid()));
select set_config('request.jwt.claim.sub',(select id::text from net where k='editor'),true);
select pg_temp.n_denied(format('select public.inquiry_context(%L)',(select id from net where k='case')),'PORTAL_DENIED');
select pg_temp.n_assert((select count(*)=0 from public.provider_documents),'revoked member loses evidence access in the existing auth context');
select set_config('request.jwt.claim.sub',(select id::text from net where k='admin'),true);
select public.portal_network_command('revoke_listing_ownership',pg_temp.n_input(jsonb_build_object('entityKind','hospital','entityId',(select id from net where k='hospital'),'reason','Local explicit ownership revocation.')));
select set_config('request.jwt.claim.sub',(select id::text from net where k='provider'),true);
select pg_temp.n_denied(format('select public.inquiry_context(%L)',(select id from net where k='case')),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from net where k='patient'),true);
select pg_temp.n_assert(public.inquiry_context((select id from net where k='case'))->'providerCoordination'->>'available'='false','revocation retains patient history with honest unavailable state');
select pg_temp.n_assert(public.inquiry_target('package',(select (v->>'packageId')::uuid from net where k='reference'))->>'organizationId' is null,'revoking hospital ownership also disables its package inquiry connection');
select set_config('request.jwt.claim.sub',(select id::text from net where k='provider'),true);
insert into net(k,v) values('cached_invite',jsonb_build_object('organizationId',(select id from net where k='org'),'operationId',gen_random_uuid(),'email','retry-role@qa.invalid','role','provider_editor'));
select public.portal_command('invite_member',(select v from net where k='cached_invite'));
select set_config('request.jwt.claim.sub',(select id::text from net where k='admin'),true);
select public.portal_command('update_member',jsonb_build_object('organizationId',(select id from net where k='org'),'userId',(select id from net where k='editor'),'role','provider_admin','active',true,'confirmed',true));
select public.portal_command('update_member',jsonb_build_object('organizationId',(select id from net where k='org'),'userId',(select id from net where k='provider'),'role','provider_editor','active',true,'confirmed',true));
select set_config('request.jwt.claim.sub',(select id::text from net where k='provider'),true);
select pg_temp.n_denied(format('select public.portal_command(''invite_member'',%L)',(select v from net where k='cached_invite')::text),'PORTAL_DENIED');
reset role;
select pg_temp.n_assert((select count(*)>8 from public.audit_events where actor_id in(select id from net)),'approvals, ownership and team changes leave auditable history');
select pg_temp.n_assert((select count(*)>5 from public.portal_notifications where user_id in(select id from net)),'actual operational events persist in-app notifications');
rollback;
\echo Provider network authority, canonical binding, inquiry lifecycle and immediate revocation checks passed.
