-- Run only on a disposable local database with validate-production-catalog.sql keep_fixture=1.
\set ON_ERROR_STOP on
begin;
do $$begin if current_database() not like 'production_catalog_personal_inquiry_%' then raise exception 'Disposable inquiry QA database required';end if;end;$$;
create temporary table iq(k text primary key,id uuid default gen_random_uuid(),v jsonb);
insert into iq(k) values('patient'),('other'),('manager'),('agent'),('unassigned_agent'),('other_provider');
insert into auth.users(id,email) select id,'inquiry-'||k||'@qa.invalid' from iq;
insert into public.staff_roles(user_id,role) select id,case k when 'manager' then 'support_manager' else 'support_agent' end from iq where k in ('manager','agent','unassigned_agent');
insert into iq(k,id) select 'hospital',id from public.hospitals where source_kind='first_party' and publication_status='published' limit 1;
insert into iq(k,id) select 'package',id from public.packages where source_kind='first_party' and publication_status='published' limit 1;
insert into iq(k,id) select 'doctor',id from public.doctors where source_kind='first_party' and publication_status='published' limit 1;
insert into iq(k,id) select 'org',id from public.organizations where hospital_id=(select id from iq where k='hospital');
insert into iq(k,id) select 'provider',user_id from public.organization_members where organization_id=(select id from iq where k='org') and active limit 1;
grant all on iq to authenticated;
create function pg_temp.iq_assert(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',msg;end if;raise notice 'PASS: %',msg;end;$$;
create function pg_temp.iq_denied(stmt text,code text) returns void language plpgsql as $$begin begin execute stmt;exception when others then if position(code in sqlerrm)>0 then raise notice 'PASS: denied %',code;return;end if;raise;end;raise exception 'FAIL: permitted operation';end;$$;
create function pg_temp.iq_input(extra jsonb default '{}') returns jsonb language sql as $$select jsonb_build_object('operationId',gen_random_uuid(),'caseId',(select id from iq where k='case'))||extra;$$;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from iq where k='patient'),true);
insert into iq(k,v) values('create_input',jsonb_build_object('operationId',gen_random_uuid(),'entityKind','hospital','entityId',(select id from iq where k='hospital'),'expectedPublishedRevision',(public.inquiry_target('hospital',(select id from iq where k='hospital'))->>'publishedRevision')::integer,'source','hospital_detail','title','LOCAL QA hospital inquiry','objective','A local coordination question only.','consent',true,'reviewed',true));
insert into iq(k,id) select 'case',(public.inquiry_command('create',(select v from iq where k='create_input'))->>'id')::uuid;
select pg_temp.iq_assert((select hospital_id=(select id from iq where k='hospital') and organization_id=(select id from iq where k='org') and inquiry_source='hospital_detail' and (entity_snapshot->>'publishedRevision')::integer=(public.inquiry_target('hospital',(select id from iq where k='hospital'))->>'publishedRevision')::integer from public.support_cases where id=(select id from iq where k='case')),'hospital request persists exact entity and publication revision');
select pg_temp.iq_assert(public.inquiry_command('create',(select v from iq where k='create_input'))->>'id'=(select id::text from iq where k='case'),'submission retry returns same persistent request');
select pg_temp.iq_assert((select count(*)=1 from public.support_cases where title='LOCAL QA hospital inquiry'),'retry does not duplicate inquiries');
select pg_temp.iq_denied(format('select public.inquiry_command(''create'',%L)',((select v from iq where k='create_input')||'{"title":"changed retry"}')::text),'INQUIRY_RETRY_CONFLICT');
select pg_temp.iq_denied(format('select public.inquiry_command(''create'',%L)',((select v from iq where k='create_input')||jsonb_build_object('operationId',gen_random_uuid(),'consent',false))::text),'PORTAL_CONSENT_REQUIRED');
select pg_temp.iq_denied(format('select public.inquiry_command(''create'',%L)',((select v from iq where k='create_input')||jsonb_build_object('operationId',gen_random_uuid(),'source','legacy'))::text),'INQUIRY_INPUT_INVALID');
select pg_temp.iq_denied(format('select public.inquiry_command(''create'',%L)',((select v from iq where k='create_input')||jsonb_build_object('operationId',gen_random_uuid(),'entityId',gen_random_uuid()))::text),'INQUIRY_ENTITY_UNAVAILABLE');
insert into iq(k,id) select 'package_case',(public.inquiry_command('create',(select v from iq where k='create_input')||jsonb_build_object('operationId',gen_random_uuid(),'entityKind','package','entityId',(select id from iq where k='package'),'expectedPublishedRevision',(public.inquiry_target('package',(select id from iq where k='package'))->>'publishedRevision')::integer,'source','package_detail','title','LOCAL QA package inquiry'))->>'id')::uuid;
select pg_temp.iq_assert((select package_id=(select id from iq where k='package') and hospital_id=(select id from iq where k='hospital') from public.support_cases where id=(select id from iq where k='package_case')),'package inquiry keeps its actual hospital and package');
select public.inquiry_command('create',(select v from iq where k='create_input')||jsonb_build_object('operationId',gen_random_uuid(),'entityKind','doctor','entityId',(select id from iq where k='doctor'),'expectedPublishedRevision',(public.inquiry_target('doctor',(select id from iq where k='doctor'))->>'publishedRevision')::integer,'source','doctor_detail','title','LOCAL QA doctor inquiry'));
select set_config('request.jwt.claim.sub',(select id::text from iq where k='other'),true);
select pg_temp.iq_assert((select count(*)=0 from public.support_cases),'another patient cannot read inquiry rows');
select pg_temp.iq_denied(format('select public.inquiry_context(%L)',(select id from iq where k='case')),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from iq where k='provider'),true);
select pg_temp.iq_assert((select count(*)=0 from public.support_cases where id=(select id from iq where k='case')),'provider cannot see unshared request');
select set_config('request.jwt.claim.sub',(select id::text from iq where k='manager'),true);
select pg_temp.iq_assert((select count(*)=3 from public.support_cases where patient_id=(select id from iq where k='patient')),'authorized Support queue sees submitted requests');
select public.inquiry_command('update',pg_temp.iq_input(jsonb_build_object('expectedRevision',(select revision from public.support_cases where id=(select id from iq where k='case')),'status','in_progress','assignedTo',(select id from iq where k='agent'))));
select set_config('request.jwt.claim.sub',(select id::text from iq where k='unassigned_agent'),true);
select pg_temp.iq_denied(format('select public.inquiry_context(%L)',(select id from iq where k='case')),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from iq where k='agent'),true);
select public.inquiry_command('request_information',pg_temp.iq_input('{"body":"Please clarify your preferred coordination timing."}'));
select public.inquiry_command('message',pg_temp.iq_input('{"body":"INTERNAL_QA_NEVER_EXPOSE","visibility":"internal"}'));
select public.inquiry_command('save_task',pg_temp.iq_input(jsonb_build_object('title','Follow up locally','assignedTo',auth.uid(),'status','open')));
insert into iq(k,id) select 'document_request',(public.inquiry_command('request_document',pg_temp.iq_input('{"title":"Coordination summary","purpose":"Clarify this local administrative question.","visibility":"patient"}'))->>'id')::uuid;
select set_config('request.jwt.claim.sub',(select id::text from iq where k='patient'),true);
select pg_temp.iq_assert(public.inquiry_context((select id from iq where k='case'))->'case'->>'status'='waiting_patient','patient sees the actual information request');
select pg_temp.iq_assert(position('INTERNAL_QA_NEVER_EXPOSE' in public.inquiry_context((select id from iq where k='case'))::text)=0,'patient context excludes internal notes');
insert into iq(k,v) values('message_input',pg_temp.iq_input('{"body":"My local preferred timing is next month.","visibility":"patient"}'));
select public.inquiry_command('message',(select v from iq where k='message_input'));
select public.inquiry_command('message',(select v from iq where k='message_input'));
select pg_temp.iq_assert((select count(*)=1 from public.support_case_messages where body='My local preferred timing is next month.'),'message retry persists one message');
reset role;
select pg_temp.iq_assert((select count(*)=1 from public.portal_notifications where user_id=(select id from iq where k='agent') and title='New inquiry message.' and resource_id=(select id from iq where k='case')),'message retry emits one assigned-staff notification');
set local role authenticated;
select pg_temp.iq_assert(public.inquiry_context((select id from iq where k='case'))->'case'->>'status'='in_progress','patient reply updates waiting status');
insert into iq(k,v) values('upload_input',pg_temp.iq_input(jsonb_build_object('filename','private.pdf','mimeType','application/pdf','sizeBytes',20,'checksum',repeat('a',64),'requestId',(select id from iq where k='document_request'))));
insert into iq(k,id) select 'file',(public.inquiry_command('reserve_upload',(select v from iq where k='upload_input'))->>'id')::uuid;
select pg_temp.iq_assert(public.inquiry_command('reserve_upload',(select v from iq where k='upload_input'))->>'id'=(select id::text from iq where k='file'),'upload reservation is retry safe');
reset role;
select pg_temp.iq_denied(format('select public.inquiry_commit_upload(%L,%L)',(select id from iq where k='patient'),(select id from iq where k='file')),'INQUIRY_FILE_NOT_STORED');
insert into storage.objects(bucket_id,name) select 'care-documents',(select id::text from iq where k='patient')||'/'||(select id::text from iq where k='case')||'/'||(select id::text from iq where k='file')||'.pdf';
select public.inquiry_commit_upload((select id from iq where k='patient'),(select id from iq where k='file'));
select public.inquiry_commit_upload((select id from iq where k='patient'),(select id from iq where k='file'));
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from iq where k='agent'),true);
select pg_temp.iq_assert((select count(*)=0 from public.support_case_documents),'private upload is invisible to assigned staff');
select pg_temp.iq_assert(not exists(select 1 from public.audit_events where entity_id=(select id from iq where k='case') and event_name like 'inquiry.support_case_documents.%'),'private upload audit cannot leak metadata to assigned Support');
select pg_temp.iq_denied(format('select public.inquiry_document_delivery(%L)',(select id from iq where k='file')),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from iq where k='patient'),true);
select public.inquiry_command('share_document',pg_temp.iq_input(jsonb_build_object('documentId',(select id from iq where k='file'),'recipient','support','purpose','Answer the coordination question.','confirmed',true)));
select public.inquiry_command('share_provider',pg_temp.iq_input(jsonb_build_object('organizationId',(select id from iq where k='org'),'purpose','Coordinate my reviewed inquiry.','confirmed',true)));
select set_config('request.jwt.claim.sub',(select id::text from iq where k='provider'),true);
select pg_temp.iq_assert((select count(*)=1 from public.support_cases where id=(select id from iq where k='case')),'provider sees only legitimately authorized request');
select pg_temp.iq_assert((select count(*)=0 from public.support_case_documents),'case consent does not share any document');
select pg_temp.iq_assert(position('INTERNAL_QA_NEVER_EXPOSE' in public.inquiry_context((select id from iq where k='case'))::text)=0,'provider context excludes internal notes');
select pg_temp.iq_assert(not(public.portal_case_context((select id from iq where k='case'))->'patient' ? 'email'),'legacy context RPC cannot expose patient email for a new inquiry');
select pg_temp.iq_denied(format('select public.inquiry_command(''provider_response'',%L)',pg_temp.iq_input('{"status":"accepted_for_coordination","body":"Unconfirmed acceptance must fail."}')::text),'PORTAL_CONFIRMATION_REQUIRED');
insert into iq(k,v) values('provider_reply',pg_temp.iq_input('{"status":"responded","body":"A real persisted local QA provider response.","confirmed":true}'));
select public.inquiry_command('provider_response',(select v from iq where k='provider_reply'));
select public.inquiry_command('provider_response',(select v from iq where k='provider_reply'));
select pg_temp.iq_assert((select count(*)=1 from public.support_case_messages where body='A real persisted local QA provider response.'),'provider response retry creates one message');
reset role;
insert into public.staff_roles(user_id,role) select id,'support_agent' from iq where k='provider';
set local role authenticated;
select pg_temp.iq_assert(public.inquiry_context((select id from iq where k='case'))->>'role'='provider','dual-role organization member does not gain unassigned Support permissions');
select pg_temp.iq_assert(position('INTERNAL_QA_NEVER_EXPOSE' in public.inquiry_context((select id from iq where k='case'))::text)=0,'dual-role provider cannot bypass internal-note assignment scope');
select pg_temp.iq_denied(format('select public.inquiry_command(''update'',%L)',pg_temp.iq_input(jsonb_build_object('status','resolved','expectedRevision',(select revision from public.support_cases where id=(select id from iq where k='case')),'resolution','Unauthorized dual-role closure.'))::text),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from iq where k='patient'),true);
select pg_temp.iq_assert(public.inquiry_context((select id from iq where k='case'))->'case'->>'provider_response_status'='responded','patient sees persisted provider response and timestamp');
select pg_temp.iq_assert(public.inquiry_context((select id from iq where k='case'))->'providerCoordination'->'latestResponse'->>'body'='A real persisted local QA provider response.','patient receives the exact persisted latest provider response');
select pg_temp.iq_assert(exists(select 1 from jsonb_array_elements(public.inquiry_context((select id from iq where k='case'))->'messages') m where m->>'body'='A real persisted local QA provider response.' and m->>'sender'='Provider'),'later Support role does not relabel a recorded provider response');
select public.inquiry_command('share_document',pg_temp.iq_input(jsonb_build_object('documentId',(select id from iq where k='file'),'recipient','provider','organizationId',(select id from iq where k='org'),'purpose','Coordinate this exact request.','confirmed',true)));
select set_config('request.jwt.claim.sub',(select id::text from iq where k='provider'),true);
select pg_temp.iq_assert((select count(*)=1 from public.support_case_documents),'provider sees only the explicitly shared file');
select public.inquiry_document_delivery((select id from iq where k='file'));
select public.inquiry_command('review_document',pg_temp.iq_input(jsonb_build_object('documentId',(select id from iq where k='file'),'status','replacement_requested','note','Please send a clearer coordination summary.')));
select set_config('request.jwt.claim.sub',(select id::text from iq where k='other_provider'),true);
insert into iq(k,id) select 'other_org',(public.portal_command('create_organization','{"name":"LOCAL other inquiry organization","providerType":"hospital","sourceKind":"first_party"}')->>'id')::uuid;
select pg_temp.iq_denied(format('select public.inquiry_context(%L)',(select id from iq where k='case')),'PORTAL_DENIED');
select pg_temp.iq_denied(format('select public.inquiry_document_delivery(%L)',(select id from iq where k='file')),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from iq where k='patient'),true);
insert into iq(k,id) select 'journey',(public.experience_command('create_journey','{"title":"LOCAL coordination journey"}')->>'id')::uuid;
insert into iq(k,id) select 'event',id from public.support_case_events where case_id=(select id from iq where k='case') and action='inquiry.provider_response';
insert into iq(k,v) values('recover_input',pg_temp.iq_input(jsonb_build_object('journeyId',(select id from iq where k='journey'),'eventId',(select id from iq where k='event'),'title','Review provider response','confirmed',true)));
select public.inquiry_command('link_recovery',(select v from iq where k='recover_input'));
select public.inquiry_command('link_recovery',(select v from iq where k='recover_input'));
select pg_temp.iq_assert((select count(*)=1 from public.recovery_tasks where support_case_id=(select id from iq where k='case') and support_event_id=(select id from iq where k='event')),'confirmed Recover task links to exact real event without duplication');
select public.inquiry_command('revoke_document',pg_temp.iq_input(jsonb_build_object('documentId',(select id from iq where k='file'),'recipient','provider')));
select set_config('request.jwt.claim.sub',(select id::text from iq where k='provider'),true);
select pg_temp.iq_denied(format('select public.inquiry_document_delivery(%L)',(select id from iq where k='file')),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from iq where k='agent'),true);
select pg_temp.iq_assert((public.inquiry_document_delivery((select id from iq where k='file'))->>'filename')='private.pdf','revoking provider file access preserves explicitly granted Support access');
select pg_temp.iq_denied(format('select public.inquiry_command(''update'',%L)',pg_temp.iq_input('{"status":"resolved","expectedRevision":1}')::text),'PORTAL_CONFLICT');
select pg_temp.iq_denied(format('select public.inquiry_command(''update'',%L)',pg_temp.iq_input(jsonb_build_object('status','resolved','expectedRevision',(select revision from public.support_cases where id=(select id from iq where k='case'))))::text),'INQUIRY_RESOLUTION_REQUIRED');
select set_config('request.jwt.claim.sub',(select id::text from iq where k='patient'),true);
select public.inquiry_command('revoke_provider',pg_temp.iq_input());
select set_config('request.jwt.claim.sub',(select id::text from iq where k='provider'),true);
select pg_temp.iq_denied(format('select public.inquiry_context(%L)',(select id from iq where k='case')),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from iq where k='patient'),true);
select public.inquiry_command('revoke_support',pg_temp.iq_input());
select set_config('request.jwt.claim.sub',(select id::text from iq where k='agent'),true);
select pg_temp.iq_denied(format('select public.inquiry_context(%L)',(select id from iq where k='case')),'PORTAL_DENIED');
select pg_temp.iq_denied(format('select public.inquiry_document_delivery(%L)',(select id from iq where k='file')),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from iq where k='patient'),true);
select pg_temp.iq_assert(jsonb_array_length(public.inquiry_context((select id from iq where k='case'))->'events')>=10,'owner retains immutable status and consent history after revocation');
select pg_temp.iq_denied(format('select public.support_legacy_command(''message'',%L)',pg_temp.iq_input('{"body":"bypass","visibility":"patient"}')::text),'permission denied');
select public.inquiry_command('cancel',jsonb_build_object('operationId',gen_random_uuid(),'caseId',(select id from iq where k='package_case')));
select pg_temp.iq_assert((select status='cancelled' from public.support_cases where id=(select id from iq where k='package_case')),'patient cancellation persists terminal state');
reset role;
select pg_temp.iq_denied('update public.support_case_events set summary=''rewritten''','append-only');
select pg_temp.iq_assert(exists(select 1 from public.audit_events where entity_id=(select id from iq where k='case') and event_name='inquiry.support_cases.update' and new_value->>'assignedTo'=(select id::text from iq where k='agent')),'assignment audit retains the actual new assignee');
select pg_temp.iq_assert(exists(select 1 from public.audit_events where entity_id=(select id from iq where k='case') and event_name='inquiry.support_document_grants.insert' and new_value->>'documentId'=(select id::text from iq where k='file')),'file sharing audit identifies the exact document without contents');
select pg_temp.iq_assert(exists(select 1 from public.audit_events where entity_id=(select id from iq where k='case') and event_name='inquiry.provider_response' and actor_role in ('provider_admin','provider_editor')),'provider response audit records the actual acting provider role');
select pg_temp.iq_assert(not exists(select 1 from public.audit_events where entity_id=(select id from iq where k='case') and (new_value::text like '%INTERNAL_QA_NEVER_EXPOSE%' or new_value::text like '%private.pdf%')),'field audit excludes patient prose and filenames');
select pg_temp.iq_assert((select count(*)=1 from public.support_case_events where case_id=(select id from iq where k='case') and action='inquiry.document_uploaded'),'upload commit retry emits one immutable upload event');
rollback;
\echo Patient inquiry lifecycle, permissions, documents, retries, notifications and Recover checks passed; all inquiry fixtures rolled back.
