\set ON_ERROR_STOP on
begin;
create temporary table qg(k text primary key,id uuid default gen_random_uuid());
insert into qg(k) values('provider'),('admin'),('patient');
insert into auth.users(id,email) select id,'governance-'||k||'@qa.invalid' from qg;
insert into public.staff_roles(user_id,role) select id,'super_admin' from qg where k='admin';
grant all on qg to authenticated;grant select on qg to anon;
create function pg_temp.qg_assert(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',msg;end if;end;$$;
create function pg_temp.qg_denied(stmt text,expected text) returns void language plpgsql as $$begin begin execute stmt;exception when others then if position(expected in sqlerrm)>0 then return;end if;raise;end;raise exception 'FAIL: unexpected permission: %',stmt;end;$$;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from qg where k='provider'),true);
insert into qg(k,id) select 'org',(public.portal_command('create_organization','{"name":"LOCAL QA Identity Hospital","providerType":"hospital","sourceKind":"first_party"}')->>'id')::uuid;
insert into qg(k,id) select 'record',(public.portal_command('save_record',jsonb_build_object('organizationId',(select id from qg where k='org'),'kind','organization','name','LOCAL QA Identity Hospital','data',jsonb_build_object('cityId',(select id from public.cities where slug='mumbai' limit 1),'description','Local QA only, rolled back without publishing real-world claims.','email','qa@qa.invalid','phone','0000','website','https://qa.invalid')))->>'id')::uuid;
insert into qg(k,id) select 'submission',(public.portal_command('submit',jsonb_build_object('organizationId',(select id from qg where k='org')))->>'id')::uuid;
select public.portal_touch_activity();
select pg_temp.qg_assert((select public.portal_team((select id from qg where k='org'))->0->>'last_active_at' is not null),'last active records actual use');
select set_config('request.jwt.claim.sub',(select id::text from qg where k='admin'),true);
select public.portal_review_command('review_section',jsonb_build_object('submissionId',submission_id,'recordId',record_id,'expectedRevision',revision,'status','approved')) from public.provider_submission_items where submission_id=(select id from qg where k='submission');
select public.portal_command('review_submission',jsonb_build_object('submissionId',(select id from qg where k='submission'),'status','approved'));
select pg_temp.qg_denied(format('select public.portal_publication_command(''publish_submission'',%L)',jsonb_build_object('submissionId',(select id from qg where k='submission'))::text),'PORTAL_EVIDENCE_REQUIRED');
select public.portal_command('review_field',jsonb_build_object('submissionId',(select id from qg where k='submission'),'recordId',(select id from qg where k='record'),'field','name','status','verified','evidence','Local fixture attestation only, not a real provider claim.','sourceUrl','https://qa.invalid'));
select public.portal_command('review_field',jsonb_build_object('submissionId',(select id from qg where k='submission'),'recordId',(select id from qg where k='record'),'field','name','status','conflicting','evidence','Latest local fixture conflict must supersede the earlier attestation.'));
select pg_temp.qg_denied(format('select public.portal_publication_command(''publish_submission'',%L)',jsonb_build_object('submissionId',(select id from qg where k='submission'))::text),'PORTAL_EVIDENCE_REQUIRED');
select public.portal_command('review_field',jsonb_build_object('submissionId',(select id from qg where k='submission'),'recordId',(select id from qg where k='record'),'field','name','status','verified','evidence','Local fixture conflict explicitly resolved after evidence review.','sourceUrl','https://qa.invalid'));
select public.portal_publication_command('publish_submission',jsonb_build_object('submissionId',(select id from qg where k='submission')));
insert into qg(k,id) select 'hospital',hospital_id from public.organizations where id=(select id from qg where k='org');
select pg_temp.qg_denied(format('select public.portal_publication_command(''unpublish_record'',%L)',jsonb_build_object('recordId',(select id from qg where k='record'),'expectedRevision',1)::text),'PORTAL_CONFIRM_REQUIRED');
select pg_temp.qg_denied(format('select public.portal_command(''set_staff_role'',%L)',jsonb_build_object('userId',(select id from qg where k='admin'),'role','support_agent','active',true)::text),'PORTAL_LAST_ADMIN');
reset role;
set local role anon;
select pg_temp.qg_assert((public.public_provider_profile((select id from qg where k='hospital'))->'fieldReviews'->0->>'status')='verified','latest approved field evidence exposed without private actor IDs');
select pg_temp.qg_assert(position('reviewed_by' in public.public_provider_profile((select id from qg where k='hospital'))::text)=0,'public evidence excludes reviewer identity and private storage paths');
select pg_temp.qg_assert(position('Local fixture conflict' in public.public_provider_profile((select id from qg where k='hospital'))::text)=0,'private reviewer evidence text is never published');
select pg_temp.qg_assert(public.public_provider_profile(gen_random_uuid())='{}','unknown provider does not expose private staging');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from qg where k='admin'),true);
select public.portal_command('set_account_status',jsonb_build_object('userId',(select id from qg where k='provider'),'active',false));
select set_config('request.jwt.claim.sub',(select id::text from qg where k='provider'),true);
select pg_temp.qg_assert(not public.portal_account_active(),'disabled account denied');
select pg_temp.qg_assert((select count(*)=0 from public.profiles),'disabled account cannot read existing patient profile');
select pg_temp.qg_denied('select public.portal_context()','PORTAL_DENIED');
reset role;
rollback;
\echo Evidence precedence, first-party publication, confirmation, last admin, activity and account suspension checks passed.
