\set ON_ERROR_STOP on
begin;
do $$begin if current_database() not like 'production_catalog_%' then raise exception 'Disposable database required';end if;end;$$;
create temporary table qr(k text primary key,id uuid default gen_random_uuid());
insert into qr(k) values('admin'),('provider'),('support');
insert into auth.users(id,email) select id,'reference-'||k||'@qa.invalid' from qr;
insert into public.staff_roles(user_id,role) select id,case k when 'admin' then 'super_admin' else 'support_agent' end from qr where k<>'provider';
grant all on qr to authenticated;grant select on qr to anon;
create function pg_temp.assert_reference(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',msg;end if;raise notice 'PASS: %',msg;end;$$;
create function pg_temp.denied_reference(stmt text,msg text) returns void language plpgsql as $$begin begin execute stmt;exception when others then if position(msg in sqlerrm)>0 then raise notice 'PASS: denied %',msg;return;end if;raise;end;raise exception 'FAIL: permitted %',stmt;end;$$;
\ir pg-catalog-reference-fixtures.sql
select pg_temp.qa_publish_references((select id from qr where k='admin'));
insert into public.cities(slug,name,country_id,source_kind,source_record_id) select 'pune','Pune',id,'external',source_record_id from public.countries where slug='india';
insert into public.catalog_drafts(entity,target_id,name,data,status,created_by,approved_by) select 'cities',id,name,jsonb_build_object('source_kind','external','source_record_id',source_record_id),'published',(select id from qr where k='admin'),(select id from qr where k='admin') from public.cities where slug='pune';
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from qr where k='provider'),true);
select pg_temp.denied_reference('select public.portal_reference_command(''create_reference_organization'',''{"name":"Forbidden","providerType":"hospital"}'')','PORTAL_DENIED');
select pg_temp.denied_reference('select public.portal_command(''create_organization'',''{"name":"Forbidden","providerType":"hospital","sourceKind":"external"}'')','PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from qr where k='support'),true);
select pg_temp.denied_reference('select public.portal_reference_command(''create_reference_organization'',''{"name":"Forbidden","providerType":"hospital"}'')','PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from qr where k='admin'),true);
insert into qr(k,id) select 'org',(public.portal_reference_command('create_reference_organization','{"name":"LOCAL REFERENCE TEST hospital","providerType":"hospital"}')->>'id')::uuid;
select pg_temp.assert_reference((select source_kind='external' and onboarding_origin='admin_reference' from public.organizations where id=(select id from qr where k='org')),'reference classification distinct from provider submissions');
select pg_temp.assert_reference(not exists(select 1 from public.organization_members where organization_id=(select id from qr where k='org')),'reference creation does not invent a provider membership');
select pg_temp.denied_reference('select public.portal_reference_command(''create_reference_source'',''{"name":"No URL","sourceType":"provider_website","collectedAt":"2026-10-04"}'')','PORTAL_REFERENCE_SOURCE_REQUIRED');
insert into qr(k,id) select 'source',(public.portal_reference_command('create_reference_source',jsonb_build_object('name','LOCAL official source fixture','url','https://qa.invalid/reference','sourceType','provider_website','collectedAt',now(),'reviewAfter',current_date+90,'notes','PRIVATE REVIEW NOTES'))->>'id')::uuid;
insert into qr(k,id) select 'profile',(public.portal_command('save_record',jsonb_build_object('organizationId',(select id from qr where k='org'),'kind','organization','name','LOCAL REFERENCE TEST hospital','data',jsonb_build_object('cityId',(select id from public.cities where slug='mumbai'),'description','Disposable reference profile. No real-world claims.','website','https://qa.invalid/reference')))->>'id')::uuid;
insert into qr(k,id) select 'location',(public.portal_command('save_record',jsonb_build_object('organizationId',(select id from qr where k='org'),'kind','location','name','Local Mumbai branch','data',jsonb_build_object('cityId',(select id from public.cities where slug='mumbai'),'address','Local Mumbai test address')))->>'id')::uuid;
insert into qr(k,id) select 'pune',(public.portal_command('save_record',jsonb_build_object('organizationId',(select id from qr where k='org'),'kind','location','name','Local Pune branch','data',jsonb_build_object('cityId',(select id from public.cities where slug='pune'),'address','Local Pune test address')))->>'id')::uuid;
insert into qr(k,id) select 'treatment',(public.portal_command('save_record',jsonb_build_object('organizationId',(select id from qr where k='org'),'kind','treatment','name','Local knee replacement','data',jsonb_build_object('treatmentId',(select id from public.treatments where slug='knee-replacement'),'locationId',(select id from qr where k='location'),'description','Local procedure offering in Mumbai only.')))->>'id')::uuid;
insert into qr(k,id) select 'doctor',(public.portal_command('save_record',jsonb_build_object('organizationId',(select id from qr where k='org'),'kind','doctor','name','LOCAL TEST reference clinician','data',jsonb_build_object('specialtyId',(select id from public.specialties where slug='orthopedics'),'locationId',(select id from qr where k='pune'),'biography','Local sourced biography without a consultation mode.')))->>'id')::uuid;
insert into qr(k,id) select 'package',(public.portal_command('save_record',jsonb_build_object('organizationId',(select id from qr where k='org'),'kind','package','name','LOCAL TEST reference package','data',jsonb_build_object('treatmentId',(select id from public.treatments where slug='knee-replacement'),'locationId',(select id from qr where k='location'),'description','Local explicit package without documented accommodation.','price',50000,'currency','INR','durationDays',4)))->>'id')::uuid;
select pg_temp.denied_reference(format('select public.portal_command(''submit'',%L)',jsonb_build_object('organizationId',(select id from qr where k='org'))::text),'PORTAL_REFERENCE_CLAIMS_REQUIRED');
select public.portal_reference_command('attach_reference_claim',jsonb_build_object('recordId',r.id,'expectedRevision',r.revision,'field',f.key,'sourceId',(select id from qr where k='source'),'evidence','PRIVATE disposable evidence supports only this exact test value.')) from public.provider_records r cross join lateral jsonb_each(r.data||jsonb_build_object('name',r.name)) f where r.organization_id=(select id from qr where k='org');
select pg_temp.denied_reference(format('select public.portal_command(''invite_member'',%L)',jsonb_build_object('organizationId',(select id from qr where k='org'),'email','reference-provider@qa.invalid','role','provider_admin')::text),'PORTAL_DENIED');
insert into qr(k,id) select 'submission',(public.portal_command('submit',jsonb_build_object('organizationId',(select id from qr where k='org')))->>'id')::uuid;
select public.portal_review_command('review_section',jsonb_build_object('submissionId',submission_id,'recordId',record_id,'expectedRevision',revision,'status','approved')) from public.provider_submission_items where submission_id=(select id from qr where k='submission');
select pg_temp.denied_reference(format('select public.portal_command(''review_submission'',%L)',jsonb_build_object('submissionId',(select id from qr where k='submission'),'status','approved')::text),'PORTAL_REFERENCE_REVIEW_REQUIRED');
select public.portal_command('review_field',jsonb_build_object('submissionId',(select id from qr where k='submission'),'recordId',c.record_id,'field',c.field,'status',case when c.field='name' and r.kind='organization' then 'verified' else 'approved' end,'sourceUrl','https://qa.invalid/reference','evidence','PRIVATE checked disposable evidence, not clinical verification.')) from public.provider_reference_claims c join public.provider_records r on r.id=c.record_id where c.organization_id=(select id from qr where k='org');
select public.portal_command('review_submission',jsonb_build_object('submissionId',(select id from qr where k='submission'),'status','approved'));
reset role;set local role anon;
select pg_temp.assert_reference((select count(*)=0 from public.hospitals),'approved reference remains private before explicit publication');
reset role;set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from qr where k='support'),true);
select pg_temp.assert_reference((select count(*)=0 from public.provider_reference_claims),'Support cannot read private reference provenance');
select pg_temp.denied_reference(format('select public.portal_command(''review_field'',%L)',jsonb_build_object('submissionId',(select id from qr where k='submission'),'recordId',(select id from qr where k='profile'),'field','name','status','verified','sourceUrl','https://qa.invalid/reference','evidence','Forged reference review')::text),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from qr where k='provider'),true);
select pg_temp.assert_reference((select count(*)=0 from public.provider_records),'Provider cannot read private reference drafts');
select pg_temp.denied_reference(format('select public.portal_command(''save_record'',%L)',jsonb_build_object('organizationId',(select id from qr where k='org'),'kind','facility','name','Forged facility','data','{}'::jsonb)::text),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from qr where k='admin'),true);
select public.portal_publication_command('publish_submission',jsonb_build_object('submissionId',(select id from qr where k='submission')));
insert into qr(k,id) select 'hospital',hospital_id from public.organizations where id=(select id from qr where k='org');
insert into qr(k,id) select 'public_doctor',canonical_id from public.provider_records where id=(select id from qr where k='doctor');
insert into qr(k,id) select 'public_package',canonical_id from public.provider_records where id=(select id from qr where k='package');
reset role;set local role anon;
select pg_temp.assert_reference((select count(*)=1 from public.hospitals),'published reference enters canonical catalog; QA excluded');
select pg_temp.assert_reference((select consultation_mode is null from public.doctors where id=(select id from qr where k='public_doctor')),'unknown consultation mode stays unknown');
select pg_temp.assert_reference((select c.slug='pune' from public.doctors d join public.cities c on c.id=d.home_city_id where d.id=(select id from qr where k='public_doctor')),'doctor location uses explicit branch association');
select pg_temp.assert_reference(exists(select 1 from public.search_catalog_candidates('knee replacement','knee-replacement') where kind='hospitals'),'canonical Discovery returns reference');
select pg_temp.assert_reference(exists(select 1 from public.search_catalog_candidates('knee replacement','knee-replacement') where kind='packages'),'canonical package search returns reference');
select pg_temp.assert_reference((public.public_provider_record('package',(select id from qr where k='public_package'))->'serviceDetails'->'accommodation'->>'status')='not_confirmed','missing package accommodation stays unknown');
select pg_temp.assert_reference(exists(select 1 from jsonb_array_elements(public.public_catalog_provenance()) x where x->>'origin'='admin_reference' and x->>'sourceUrl'='https://qa.invalid/reference'),'public reference origin and source retained');
select pg_temp.assert_reference(jsonb_array_length(public.public_reference_claims('hospital',(select id from qr where k='hospital')))>15,'public field-level provenance coverage');
select pg_temp.assert_reference(position('PRIVATE' in public.public_reference_claims('hospital',(select id from qr where k='hospital'))::text)=0 and position('reviewed_by' in public.public_reference_claims('hospital',(select id from qr where k='hospital'))::text)=0,'public projection excludes notes, private evidence and reviewer IDs');
select pg_temp.assert_reference(exists(select 1 from jsonb_array_elements(public.public_reference_locations()) x where x->>'kind'='treatment' and x->>'city'='Mumbai') and not exists(select 1 from jsonb_array_elements(public.public_reference_locations()) x where x->>'kind'='treatment' and x->>'city'='Pune'),'treatment branch provenance is exact');
reset role;set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from qr where k='admin'),true);
select public.portal_command('save_record',jsonb_build_object('organizationId',organization_id,'recordId',id,'expectedRevision',revision,'kind',kind,'name',name,'data',data||'{"description":"Private V2 draft must not replace published V1."}')) from public.provider_records where id=(select id from qr where k='profile');
reset role;set local role anon;
select pg_temp.assert_reference((select description='Disposable reference profile. No real-world claims.' from public.hospitals where id=(select id from qr where k='hospital')),'draft V2 preserves V1 canonical profile and provenance');
reset role;set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from qr where k='admin'),true);
select public.portal_publication_command('archive_record',jsonb_build_object('recordId',(select id from qr where k='profile'),'expectedRevision',2,'confirmed',true));
reset role;set local role anon;
select pg_temp.assert_reference((select count(*)=0 from public.hospitals),'archive hides reference hospital');
select pg_temp.assert_reference((select count(*)=0 from public.doctors) and (select count(*)=0 from public.packages),'archive hides dependent doctors and packages');
reset role;
select pg_temp.assert_reference((select count(*)=2 from public.provider_revisions where record_id=(select id from qr where k='profile')),'immutable history retained after archive');
rollback;
