-- Isolated contract fixtures, never production. No real scan claim is made here.
\set ON_ERROR_STOP on
begin;
do $$begin if current_database() not like 'production_catalog_%' then raise exception 'Disposable catalog QA required';end if;end;$$;
create function pg_temp.d_assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL %',label;end if;raise notice 'PASS %',label;end;$$;
create function pg_temp.d_denied(q text,e text) returns void language plpgsql as $$begin execute q;raise exception 'Unexpected success';exception when others then if sqlerrm not like '%'||e||'%' then raise;end if;end;$$;
create temp table fixture(k text primary key,id uuid default gen_random_uuid(),v jsonb);
insert into fixture(k) values('owner'),('other'),('admin'),('conversation'),('workspace'),('document');
insert into auth.users(id,email) select id,'deletion-'||id||'@qa.invalid' from fixture where k in ('owner','other','admin');
insert into public.staff_roles(user_id,role) select id,'super_admin' from fixture where k='admin';
insert into public.conversations(id,owner_id) select c.id,o.id from fixture c,fixture o where c.k='conversation' and o.k='owner';
update fixture set v=jsonb_build_object('id',id,'ownerId',(select id from fixture where k='owner'),'conversationId',(select id from fixture where k='conversation'),
 'hospitalId',(select id from public.hospitals limit 1),'serviceLabel','QA service','requirements','[]'::jsonb,'revision',0,'documents',jsonb_build_array(jsonb_build_object('id',(select id from fixture where k='document'),
 'uploadStatus','uploaded','mimeType','application/pdf','size',20,'checksum',repeat('1',64)))) where k='workspace';
select public.save_document_workspace(v,-1,'qa_start') from fixture where k='workspace';
insert into fixture(k,v) select 'path',to_jsonb(o.id||'/'||w.id||'/'||d.id||'.pdf') from fixture o,fixture w,fixture d where o.k='owner' and w.k='workspace' and d.k='document';
insert into fixture(k,v) select 'scan',public.document_security_register('care-documents',v#>>'{}',repeat('1',64),20,'application/pdf') from fixture where k='path';
update fixture set id=(v->>'id')::uuid where k='scan';
insert into storage.objects(bucket_id,name) select 'care-documents',v#>>'{}' from fixture where k='path';
select pg_temp.d_denied(format('select public.document_deletion_request(%L,%L,%L)',(select id from fixture where k='workspace'),(select id from fixture where k='document'),(select id from fixture where k='other')),'DOCUMENT_DELETION_SCOPE');
select pg_temp.d_denied(format('select public.document_deletion_request(%L,%L,%L)',(select id from fixture where k='workspace'),(select id from fixture where k='document'),(select id from fixture where k='owner')),'DOCUMENT_DELETION_NOT_REMOVED');
grant select on fixture to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from fixture where k='other'),true);
select pg_temp.d_denied('select public.document_security_review()','PORTAL_DENIED');
select pg_temp.d_denied('select public.document_deletion_queue()','PORTAL_DENIED');
select pg_temp.d_denied(format('select public.document_retention_hold(%L,true,%L,true)',(select id from fixture where k='scan'),'legal_review'),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from fixture where k='admin'),true);
select pg_temp.d_denied(format('select public.document_retention_hold(%L,true,%L,false)',(select id from fixture where k='scan'),'legal_review'),'PORTAL_DENIED');
select public.document_retention_hold((select id from fixture where k='scan'),true,'legal_review',true);
reset role;
update fixture set v=jsonb_set(jsonb_set(v,'{documents,0,uploadStatus}','"removed"'),'{revision}','1') where k='workspace';
select pg_temp.d_denied(format('select public.save_document_workspace(%L,0,%L)',(select v from fixture where k='workspace'),'remove_document'),'DOCUMENT_RETENTION_HOLD');
select pg_temp.d_assert((select revision=0 from public.document_workspaces where id=(select id from fixture where k='workspace')),'hold rolls back workspace removal');
select pg_temp.d_assert(not exists(select 1 from public.document_deletion_jobs where workspace_id=(select id from fixture where k='workspace')),'hold creates no deletion intent');
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from fixture where k='admin'),true);
select public.document_retention_hold((select id from fixture where k='scan'),false,'legal_review',true);
reset role;
select public.save_document_workspace(v,0,'remove_document') from fixture where k='workspace';
insert into fixture(k,v) select 'deletion',public.document_deletion_request(w.id,d.id,o.id) from fixture w,fixture d,fixture o where w.k='workspace' and d.k='document' and o.k='owner';
update fixture set id=(v->>'id')::uuid where k='deletion';
select pg_temp.d_assert((select count(*)=1 from public.document_deletion_jobs where workspace_id=(select id from fixture where k='workspace')),'one atomic cleanup intent');
select pg_temp.d_assert((select state='quarantined' and failure_category='removed' and not ready from public.document_security_jobs where id=(select id from fixture where k='scan')),'removal invalidates scan and download');
select pg_temp.d_assert(public.document_deletion_request((select id from fixture where k='workspace'),(select id from fixture where k='document'),(select id from fixture where k='owner'))->>'id'=(select id::text from fixture where k='deletion'),'request retry is idempotent');
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from fixture where k='admin'),true);
select public.document_retention_hold((select id from fixture where k='scan'),true,'operational_review',true);
reset role;
select pg_temp.d_assert(public.document_deletion_claim((select id from fixture where k='deletion')) is null,'queued deletion respects newly applied hold');
select pg_temp.d_assert((select state='held' and attempts=0 from public.document_deletion_jobs where id=(select id from fixture where k='deletion')),'hold consumes no retry');
set local role authenticated;
select public.document_retention_hold((select id from fixture where k='scan'),false,'operational_review',true);
reset role;
insert into fixture(k,v) values('claim',public.document_deletion_claim((select id from fixture where k='deletion')));
select pg_temp.d_assert(public.document_deletion_claim((select id from fixture where k='deletion')) is null,'duplicate worker cannot claim lease');
set local role authenticated;
select pg_temp.d_denied(format('select public.document_retention_hold(%L,true,%L,true)',(select id from fixture where k='scan'),'legal_review'),'DOCUMENT_HOLD_TOO_LATE');
reset role;
select pg_temp.d_denied(format('select public.document_deletion_result(%L,%L,true)',(select id from fixture where k='deletion'),(select v->>'lease' from fixture where k='claim')),'DOCUMENT_DELETION_OBJECT_REMAINS');
select pg_temp.d_denied(format('select public.document_deletion_result(%L,%L,true)',(select id from fixture where k='deletion'),gen_random_uuid()),'DOCUMENT_DELETION_LEASE');
select public.document_deletion_result((select id from fixture where k='deletion'),(select (v->>'lease')::uuid from fixture where k='claim'),false,'storage_unavailable');
select public.document_deletion_result((select id from fixture where k='deletion'),(select (v->>'lease')::uuid from fixture where k='claim'),false,'storage_unavailable');
select pg_temp.d_assert((select count(*)=1 from public.audit_events where entity_id=(select id from fixture where k='deletion') and metadata->>'state'='cleanup_failed'),'failure ACK retry does not duplicate audit');
select pg_temp.d_assert(public.document_deletion_claim((select id from fixture where k='deletion')) is null,'bounded backoff enforced');
update public.document_deletion_jobs set next_attempt_at=now() where id=(select id from fixture where k='deletion');
update fixture set v=public.document_deletion_claim((select id from fixture where k='deletion')) where k='claim';
delete from storage.objects where name=(select v#>>'{}' from fixture where k='path');
select public.document_deletion_result((select id from fixture where k='deletion'),(select (v->>'lease')::uuid from fixture where k='claim'),true);
select public.document_deletion_result((select id from fixture where k='deletion'),(select (v->>'lease')::uuid from fixture where k='claim'),true);
select pg_temp.d_assert((select state='deleted' and completed_at is not null from public.document_deletion_jobs where id=(select id from fixture where k='deletion')),'confirmed database absence completes cleanup');
select pg_temp.d_assert(not private.document_security_clean('care-documents',(select v#>>'{}' from fixture where k='path')),'tombstone blocks alternate clean route');
select pg_temp.d_assert(not exists(select 1 from public.audit_events where entity_id=(select id from fixture where k='deletion') and metadata::text~'checksum|filename|path|token'),'lifecycle audit categorical only');
select pg_temp.d_assert(not has_function_privilege('authenticated','public.document_deletion_claim(uuid)','execute') and not has_table_privilege('authenticated','public.document_deletion_jobs','update'),'browser cannot delete or forge completion');
set local role authenticated;
select pg_temp.d_assert((select count(*)=0 from storage.objects where bucket_id='care-documents'),'direct Storage SELECT/signing blocked');
reset role;
select pg_temp.d_denied('select public.document_deletion_reconcile()','DOCUMENT_RECOVERY_ISOLATION_REQUIRED');
update private.document_recovery_gate set blocked=true;
insert into storage.objects(bucket_id,name) select 'care-documents',v#>>'{}' from fixture where k='path';
select pg_temp.d_assert(public.document_deletion_reconcile()=1,'restored deleted object requeued while isolated');
select pg_temp.d_assert((select state='queued' and completed_at is null from public.document_deletion_jobs where id=(select id from fixture where k='deletion')),'restore cannot pretend stored object remains deleted');
update public.document_deletion_jobs set state='deleting',attempts=3,lease_until=now()-interval '1 second' where id=(select id from fixture where k='deletion');
select pg_temp.d_assert(public.document_deletion_claim((select id from fixture where k='deletion')) is null,'third expired lease exhausts retries');
select pg_temp.d_assert((select state='cleanup_failed' and failure_category='lease_expired' from public.document_deletion_jobs where id=(select id from fixture where k='deletion')),'exhaustion remains visible and blocked');
-- Missing recovery configuration must deny even the service-side clean assertion.
select public.document_security_register('care-documents','QA-missing-gate/fixture.pdf',repeat('2',64),20,'application/pdf');
update public.document_security_jobs set state='clean',scanned_at=now(),engine_version='1.4.6',signature_at=now() where object_path='QA-missing-gate/fixture.pdf';
delete from private.document_recovery_gate;
select pg_temp.d_denied($s$select public.document_security_assert_clean('care-documents','QA-missing-gate/fixture.pdf')$s$,'DOCUMENT_SECURITY_BLOCKED');
select pg_temp.d_assert(private.document_security_clean('care-documents','QA-missing-gate/fixture.pdf') is false,'missing gate gives explicit false, not null');
rollback;
