\set ON_ERROR_STOP on
begin;
do $$begin if current_database() not like 'production_catalog_personal_%' then raise exception 'Disposable personal QA database required';end if;end $$;
create temporary table personal_ids(k text primary key,id uuid default gen_random_uuid());
insert into personal_ids(k) values('owner'),('other'),('staff');
insert into auth.users(id,email) select id,'personal-'||k||'@qa.invalid' from personal_ids;
insert into public.staff_roles(user_id,role) select id,'super_admin' from personal_ids where k='staff';
insert into personal_ids(k,id) select 'hospital',id from public.hospitals where source_kind='first_party' limit 1;
insert into personal_ids(k,id) select 'doctor',id from public.doctors where source_kind='first_party' limit 1;
insert into personal_ids(k,id) select 'package',id from public.packages where source_kind='first_party' limit 1;
grant all on personal_ids to authenticated;grant select on personal_ids to anon;
create function pg_temp.personal_assert(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',msg;end if;raise notice 'PASS: %',msg;end $$;
create function pg_temp.personal_denied(stmt text,msg text) returns void language plpgsql as $$begin begin execute stmt;exception when others then raise notice 'PASS: denied %',msg;return;end;raise exception 'FAIL: permitted %',msg;end $$;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from personal_ids where k='owner'),true);
select public.experience_command('save_profile','{"display_name":"QA Owner","phone":"","country":"India","city":"Mumbai","locale":"hi","currency":"INR","inApp":true}');
select pg_temp.personal_assert((select currency='INR' and locale='hi' and display_name='QA Owner' and preferences_updated_at is not null from public.profiles where id=auth.uid()),'profile and preferences persist');
select pg_temp.personal_assert((select count(*)=1 from public.profiles),'only own profile visible');
select public.experience_command('save_preferences','{"locale":"mr","currency":"AED"}');
select pg_temp.personal_assert((select currency='AED' and locale='mr' from public.profiles where id=auth.uid()),'supported currency and language persist');
select pg_temp.personal_denied($s$select public.experience_command('save_preferences','{"locale":"de","currency":"BAD"}')$s$,'unsupported preferences');
select public.experience_command('save_item',jsonb_build_object('kind',k,'recordId',id,'saved',true)) from personal_ids where k in ('hospital','doctor','package');
select pg_temp.personal_assert((select count(*)=3 from public.saved_items),'hospital doctor and package saves persist');
select public.experience_command('save_item',jsonb_build_object('kind','hospital','recordId',(select id from personal_ids where k='hospital'),'saved',true));
select pg_temp.personal_assert((select count(*)=3 from public.saved_items),'save is idempotent');
select pg_temp.personal_denied($s$select public.experience_command('save_item',jsonb_build_object('kind','hospital','recordId',gen_random_uuid(),'saved',true))$s$,'unpublished provider cannot be saved');
select public.experience_command('save_item',jsonb_build_object('kind','package','recordId',(select id from personal_ids where k='package'),'saved',false));
select pg_temp.personal_assert((select count(*)=2 from public.saved_items),'remove save persists');
select public.experience_command('save_search','{"query":"Knee replacement in Mumbai"}');
select pg_temp.personal_assert((select count(*)=1 from public.recent_searches),'recent search persists');
insert into personal_ids(k,id) select 'journey',(public.experience_command('create_journey',jsonb_build_object('title','QA follow-up coordination','hospitalId',(select id from personal_ids where k='hospital')))->>'id')::uuid;
select pg_temp.personal_assert((select count(*)=1 from public.recovery_journeys),'journey persists');
select pg_temp.personal_assert((select hospital_id=(select id from personal_ids where k='hospital') from public.recovery_journeys),'published provider connection persists');
select pg_temp.personal_assert((select count(*)=1 from public.recovery_events),'creation timeline is recorded');
insert into personal_ids(k,id) select 'task',(public.experience_command('add_task',jsonb_build_object('journeyId',(select id from personal_ids where k='journey'),'title','Confirm follow-up with provider','dueAt',now()+interval '1 day'))->>'id')::uuid;
select pg_temp.personal_assert((select status='open' and source='user_created' and completed_at is null and due_at is not null from public.recovery_tasks),'task owner source status due date persist');
select pg_temp.personal_assert(exists(select 1 from public.portal_notifications where user_id=auth.uid() and resource_type='recovery_journey'),'real saved reminder notification uses existing infrastructure');
select public.experience_command('complete_task',jsonb_build_object('journeyId',(select id from personal_ids where k='journey'),'taskId',(select id from personal_ids where k='task'),'completed',true));
select pg_temp.personal_assert((select status='completed' and completed_at is not null from public.recovery_tasks),'task completion persists');
select public.experience_command('add_event',jsonb_build_object('journeyId',(select id from personal_ids where k='journey'),'title','Organized follow-up questions','occurredAt',now()));
select pg_temp.personal_assert((select count(*)=4 from public.recovery_events),'timeline records actual changes and user milestones');
select public.experience_command('update_journey',jsonb_build_object('journeyId',(select id from personal_ids where k='journey'),'stage','ongoing'));
select pg_temp.personal_assert((select stage='ongoing' from public.recovery_journeys),'coordination stage persists');
select pg_temp.personal_denied($s$select public.experience_command('create_support',jsonb_build_object('journeyId',(select id from personal_ids where k='journey'),'title','Help with contact','description','Help contact my provider.'))$s$,'support requires explicit consent');
insert into personal_ids(k,id) select 'support',(public.experience_command('create_support',jsonb_build_object('journeyId',(select id from personal_ids where k='journey'),'title','Help with contact','description','Help contact my provider.','consent',true))->>'id')::uuid;
select pg_temp.personal_assert(exists(select 1 from public.support_cases where id=(select id from personal_ids where k='support') and patient_id=auth.uid() and not share_documents and not share_conversation and not share_with_provider),'real support case without blanket private sharing');
select pg_temp.personal_assert(exists(select 1 from public.recovery_support_links where journey_id=(select id from personal_ids where k='journey')),'support association persists');
select pg_temp.personal_denied($s$insert into public.recovery_events(journey_id,owner_id,title,event_type) values((select id from personal_ids where k='journey'),auth.uid(),'Forged action','support_created')$s$,'direct timeline forging denied');
select pg_temp.personal_denied($s$select public.experience_rate_cache(null)$s$,'rates cache is server only');
select pg_temp.personal_denied($s$select public.experience_guest_session('read',repeat('a',64))$s$,'visitor state is server only');
select set_config('request.jwt.claim.sub',(select id::text from personal_ids where k='other'),true);
select pg_temp.personal_assert((select count(*)=0 from public.saved_items),'other user cannot read saved items');
select pg_temp.personal_assert((select count(*)=0 from public.recovery_journeys),'other user cannot read recovery journeys');
select pg_temp.personal_assert((select count(*)=0 from public.recovery_tasks),'other user cannot read recovery tasks');
select pg_temp.personal_assert((select count(*)=0 from public.recovery_events),'other user cannot read timeline');
select pg_temp.personal_denied($s$select public.experience_command('complete_task',jsonb_build_object('journeyId',(select id from personal_ids where k='journey'),'taskId',(select id from personal_ids where k='task'),'completed',false))$s$,'other user cannot complete owner task');
select pg_temp.personal_denied($s$update public.saved_items set owner_id=auth.uid()$s$,'other user cannot modify saves');
select pg_temp.personal_denied($s$select public.experience_command('link_document',jsonb_build_object('journeyId',(select id from personal_ids where k='journey'),'documentId',gen_random_uuid()))$s$,'cross-owner document link denied');
select set_config('request.jwt.claim.sub',(select id::text from personal_ids where k='staff'),true);
select pg_temp.personal_assert((select count(*)=0 from public.recovery_journeys),'admin does not receive blanket recovery access');
select pg_temp.personal_assert((select count(*)=0 from public.saved_items),'admin does not receive blanket save access');
reset role;
select pg_temp.personal_assert(exists(select 1 from public.portal_notifications where user_id=(select id from personal_ids where k='staff') and resource_type='support_case' and resource_id=(select id from personal_ids where k='support')),'actual support queue notification exists');
set local role anon;
select pg_temp.personal_denied($s$select * from public.recovery_journeys$s$,'anonymous recovery access denied');
select pg_temp.personal_denied($s$select public.experience_command('save_profile','{}')$s$,'anonymous profile writes denied');
reset role;
select pg_temp.personal_assert((select count(*)=1 from private.exchange_rate_cache)=false,'no fake exchange rate fixtures inserted by migration');
rollback;
