\set ON_ERROR_STOP on
begin;
create temporary table qa_ids(k text primary key,id uuid default gen_random_uuid());
insert into qa_ids(k) values('provider'),('patient'),('support'),('other_support'),('admin');
insert into auth.users(id,email) select id,'workflow-'||k||'@qa.invalid' from qa_ids;
insert into public.staff_roles(user_id,role) select id,case when k='admin' then 'super_admin' else 'support_agent' end from qa_ids where k in ('admin','support','other_support');
grant all on qa_ids to authenticated;
create function pg_temp.check_qa(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;end;$$;
create function pg_temp.denied_qa(stmt text,expected text) returns void language plpgsql as $$begin begin execute stmt;exception when others then if position(expected in sqlerrm)>0 then return;end if;raise;end;raise exception 'FAIL: unexpectedly allowed: %',stmt;end;$$;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from qa_ids where k='provider'),true);
insert into qa_ids(k,id) select 'org',(public.portal_command('create_organization','{"name":"QA ONLY Workflow Hospital","providerType":"hospital","sourceKind":"synthetic"}')->>'id')::uuid;
insert into qa_ids(k,id) select 'profile',(public.portal_command('save_record',jsonb_build_object('organizationId',(select id from qa_ids where k='org'),'kind','organization','name','QA ONLY Workflow Hospital','data',jsonb_build_object('cityId',(select id from public.cities where slug='mumbai' limit 1),'description','Synthetic workflow validation hospital.','email','workflow@qa.invalid','phone','00000000')))->>'id')::uuid;
insert into qa_ids(k,id) select 'specialty',(public.portal_command('save_record',jsonb_build_object('organizationId',(select id from qa_ids where k='org'),'kind','specialty','name','QA specialty','data',jsonb_build_object('specialtyId',(select id from public.specialties limit 1))))->>'id')::uuid;
insert into qa_ids(k,id) select 'treatment',(public.portal_command('save_record',jsonb_build_object('organizationId',(select id from qa_ids where k='org'),'kind','treatment','name','QA treatment','data',jsonb_build_object('treatmentId',(select id from public.treatments limit 1))))->>'id')::uuid;
insert into qa_ids(k,id) select 'doctor',(public.portal_command('save_record',jsonb_build_object('organizationId',(select id from qa_ids where k='org'),'kind','doctor','name','QA ONLY Doctor','data',jsonb_build_object('specialtyId',(select id from public.specialties limit 1),'biography','Synthetic doctor used for validation only.','consultationMode','both','experienceYears',3,'languages',jsonb_build_array('English'))))->>'id')::uuid;
insert into qa_ids(k,id) select 'facility',(public.portal_command('save_record',jsonb_build_object('organizationId',(select id from qa_ids where k='org'),'kind','facility','name','QA beds','data','{"facilityType":"beds","quantity":12}'::jsonb))->>'id')::uuid;
insert into qa_ids(k,id) select 'package',(public.portal_command('save_record',jsonb_build_object('organizationId',(select id from qa_ids where k='org'),'kind','package','name','QA ONLY Package','data',jsonb_build_object('treatmentId',(select id from public.treatments limit 1),'description','Synthetic QA package, no real medical offer.','currency','INR','price',25000,'durationDays',3,'inclusions',jsonb_build_array('Synthetic inclusion'),'exclusions',jsonb_build_array('Flights'))))->>'id')::uuid;
insert into qa_ids(k,id) select 'submission',(public.portal_command('submit',jsonb_build_object('organizationId',(select id from qa_ids where k='org')))->>'id')::uuid;
select pg_temp.denied_qa(format('select public.portal_command(''save_record'',%L)',jsonb_build_object('organizationId',(select id from qa_ids where k='org'),'recordId',(select id from qa_ids where k='profile'),'kind','organization','name','Locked','data','{}'::jsonb,'expectedRevision',1)::text),'PORTAL_RECORD_LOCKED');
select set_config('request.jwt.claim.sub',(select id::text from qa_ids where k='admin'),true);
select public.portal_command('review_submission',jsonb_build_object('submissionId',(select id from qa_ids where k='submission'),'status','changes_requested','message','Please clarify the profile description.'));
select public.portal_command('assign_reviewer',jsonb_build_object('submissionId',(select id from qa_ids where k='submission'),'userId',(select id from qa_ids where k='support')));
select set_config('request.jwt.claim.sub',(select id::text from qa_ids where k='provider'),true);
select pg_temp.check_qa(exists(select 1 from public.portal_notifications where title='changes requested'),'provider receives changes request');
select public.portal_command('save_record',jsonb_build_object('organizationId',(select id from qa_ids where k='org'),'recordId',id,'kind',kind,'name',name,'data',data||'{"description":"Revised synthetic QA description."}'::jsonb,'expectedRevision',revision)) from public.provider_records where id=(select id from qa_ids where k='profile');
insert into qa_ids(k,id) select 'resubmission',(public.portal_command('submit',jsonb_build_object('organizationId',(select id from qa_ids where k='org'),'message','Description clarified.'))->>'id')::uuid;
select set_config('request.jwt.claim.sub',(select id::text from qa_ids where k='admin'),true);
select public.portal_command('review_submission',jsonb_build_object('submissionId',(select id from qa_ids where k='resubmission'),'status','approved'));
select public.portal_publication_command('publish_submission',jsonb_build_object('submissionId',(select id from qa_ids where k='resubmission')));
insert into qa_ids(k,id) select 'hospital',hospital_id from public.organizations where id=(select id from qa_ids where k='org');
select pg_temp.check_qa((select count(*)=6 from public.provider_records where published_revision is not null),'all approved snapshots published');
select set_config('request.jwt.claim.sub',(select id::text from qa_ids where k='provider'),true);
select public.portal_command('save_record',jsonb_build_object('organizationId',(select id from qa_ids where k='org'),'recordId',id,'kind',kind,'name','SECRET DRAFT NAME','data',data,'expectedRevision',revision)) from public.provider_records where id=(select id from qa_ids where k='profile');
reset role;
select public.record_portal_verification((select id from qa_ids where k='support'),(select id from qa_ids where k='org'),(select id from qa_ids where k='hospital'),'{"status":"incomplete","testOnly":true}'::jsonb);
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from qa_ids where k='support'),true);
select pg_temp.check_qa((select count(*)=1 from public.portal_verification_checks),'assigned reviewer sees scoped verification history');
select set_config('request.jwt.claim.sub',(select id::text from qa_ids where k='other_support'),true);
select pg_temp.check_qa((select count(*)=0 from public.portal_verification_checks),'unassigned reviewer cannot see verification history');
reset role;
grant select on qa_ids to anon;
set local role anon;
select pg_temp.check_qa(exists(select 1 from public.hospitals where id=(select id from qa_ids where k='hospital') and name='QA ONLY Workflow Hospital'),'published hospital visible, draft does not leak');
select pg_temp.check_qa(exists(select 1 from public.packages where name='QA ONLY Package' and currency='INR' and estimated_min=25000),'package currency preserved');
select pg_temp.check_qa(exists(select 1 from public.search_catalog_candidates('QA ONLY Workflow Hospital') where kind='hospitals'),'existing AI search consumes publication');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from qa_ids where k='patient'),true);
select pg_temp.denied_qa('select public.support_command(''create_case'',''{"title":"Missing consent must be denied"}''::jsonb)','PORTAL_CONSENT_REQUIRED');
insert into qa_ids(k,id) select 'case',(public.support_command('create_case',jsonb_build_object('title','QA coordination request','consent',true,'hospitalId',(select id from qa_ids where k='hospital'),'shareWithProvider',true))->>'id')::uuid;
select set_config('request.jwt.claim.sub',(select id::text from qa_ids where k='support'),true);
select public.support_command('update_case',jsonb_build_object('caseId',(select id from qa_ids where k='case'),'expectedRevision',1,'assignedTo',(select id from qa_ids where k='support'),'status','in_progress'));
select public.support_command('message',jsonb_build_object('caseId',(select id from qa_ids where k='case'),'visibility','internal','body','INTERNAL SECRET QA NOTE'));
select public.support_command('message',jsonb_build_object('caseId',(select id from qa_ids where k='case'),'visibility','shared','body','Shared coordination reply'));
select public.support_command('save_task',jsonb_build_object('caseId',(select id from qa_ids where k='case'),'title','Follow up QA request','assignedTo',(select id from qa_ids where k='support')));
select set_config('request.jwt.claim.sub',(select id::text from qa_ids where k='other_support'),true);
select pg_temp.check_qa((select count(*)=0 from public.support_cases),'other agent cannot read assigned cases');
select pg_temp.denied_qa(format('select public.portal_case_context(%L)',(select id from qa_ids where k='case')),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from qa_ids where k='provider'),true);
select pg_temp.check_qa(position('INTERNAL SECRET' in public.portal_case_context((select id from qa_ids where k='case'))::text)=0,'internal notes hidden from provider');
select set_config('request.jwt.claim.sub',(select id::text from qa_ids where k='patient'),true);
select pg_temp.check_qa(position('INTERNAL SECRET' in public.portal_case_context((select id from qa_ids where k='case'))::text)=0,'internal notes hidden from patient');
select pg_temp.check_qa((public.portal_case_context((select id from qa_ids where k='case'))->'tasks')='[]'::jsonb,'internal tasks hidden from patient');
select public.support_command('revoke_consent',jsonb_build_object('caseId',(select id from qa_ids where k='case')));
select set_config('request.jwt.claim.sub',(select id::text from qa_ids where k='support'),true);
select pg_temp.denied_qa(format('select public.portal_case_context(%L)',(select id from qa_ids where k='case')),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from qa_ids where k='admin'),true);
insert into qa_ids(k,id) select 'catalog',(public.portal_catalog_command('save_catalog_draft','{"entity":"specialties","name":"QA ONLY Specialty","data":{"slug":"qa-only-specialty","source_kind":"synthetic"}}')->>'id')::uuid;
select public.portal_catalog_command('approve_catalog',jsonb_build_object('draftId',(select id from qa_ids where k='catalog'),'expectedRevision',1));
select public.portal_catalog_command('publish_catalog',jsonb_build_object('draftId',(select id from qa_ids where k='catalog'),'expectedRevision',1,'confirmed',true));
select pg_temp.check_qa(exists(select 1 from public.specialties where slug='qa-only-specialty'),'canonical CRUD publication works');
select pg_temp.check_qa((select count(*)>20 from public.audit_events where actor_id in(select id from qa_ids)),'workflow mutations audited');
reset role;
rollback;
\echo Provider review, publication, public AI search, support consent, notes, assignment, tasks, catalog and audit checks passed.
