-- Disposable local metadata fixtures only. Always roll back.
\set ON_ERROR_STOP on
begin;
do $$begin if current_database() not like 'production_catalog_%' then raise exception 'Disposable QA database required';end if;end;$$;
create temporary table ops(k text primary key,id uuid default gen_random_uuid(),v jsonb);
insert into ops(k) values('admin'),('support'),('other'),('patient'),('provider'),('operation');
insert into auth.users(id,email) select id,'operations-'||k||'@qa.invalid' from ops where k<>'operation';
insert into public.staff_roles(user_id,role) select id,case k when 'admin' then 'super_admin' else 'support_agent' end from ops where k in ('admin','support','other');
grant all on ops to authenticated;
create function pg_temp.o_assert(ok boolean,msg text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',msg;end if;raise notice 'PASS: %',msg;end;$$;
create function pg_temp.o_denied(stmt text,code text) returns void language plpgsql as $$begin begin execute stmt;exception when others then if position(code in sqlerrm)>0 then raise notice 'PASS: denied %',code;return;end if;raise;end;raise exception 'FAIL: permitted operation';end;$$;
create function pg_temp.o_input(extra jsonb default '{}') returns jsonb language sql as $$select jsonb_build_object('operationId',gen_random_uuid(),'confirmed',true)||extra;$$;
insert into public.support_cases(patient_id,title,description,consent_granted_at,inquiry_source,created_at,assigned_to,status)
 select (select id from ops where k='patient'),'LOCAL OPERATIONS QA','Private patient prose must never enter operational data.',now(),'help',now()-interval '80 hours',case when s='in_progress' then (select id from ops where k='other') end,s from unnest(array['open','in_progress','waiting_provider','waiting_patient'])s;
insert into ops(k,id) select 'case',id from public.support_cases where title='LOCAL OPERATIONS QA' and status='open';
insert into public.support_case_events(case_id,actor_id,action,summary,visibility) values((select id from ops where k='case'),(select id from ops where k='patient'),'inquiry.task_saved','Non-coordination activity does not reset waiting time.','internal');
select pg_temp.o_assert((select overdue from private.operations_cases() where id=(select id from ops where k='case')),'only meaningful activity resets waiting time');
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from ops where k='patient'),true);
select pg_temp.o_denied('select public.operations_overview()','PORTAL_DENIED');
select pg_temp.o_denied('select public.operations_probe()','PORTAL_DENIED');
select pg_temp.o_denied('select public.operations_inquiries()','PORTAL_DENIED');
select pg_temp.o_denied('select public.operations_record_request(null,''{}'')','permission denied');
select pg_temp.o_denied('select public.operations_record_health(null,null,''{}'')','permission denied');
select pg_temp.o_assert((select count(*)=0 from public.operational_incidents),'patient RLS cannot read incidents');
select set_config('request.jwt.claim.sub',(select id::text from ops where k='provider'),true);
select pg_temp.o_denied('select public.operations_overview()','PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from ops where k='support'),true);
select pg_temp.o_assert(not exists(select 1 from jsonb_array_elements(public.operations_inquiries('all')->'rows')r where r->>'status'='in_progress'),'Support cannot inspect another agent assigned inquiry');
select pg_temp.o_denied('select public.operations_overview()','PORTAL_DENIED');
select pg_temp.o_denied(format('select public.operations_command(''operations_incident_create'',%L)',pg_temp.o_input('{"category":"ai","severity":"high"}')::text),'PORTAL_DENIED');
select set_config('request.jwt.claim.sub',(select id::text from ops where k='admin'),true);
select pg_temp.o_assert((select count(*)=3 from jsonb_array_elements(public.operations_inquiries('unassigned')->'rows')r join public.support_cases c on c.id=(r->>'id')::uuid where c.title='LOCAL OPERATIONS QA'),'unassigned filter includes provider and patient waiting states without an assignee');
select pg_temp.o_assert(public.operations_probe()->>'database'='true','Admin probe performs actual bounded database query');
select pg_temp.o_assert(public.operations_overview()->'notifications'->>'externalDelivery'='not_configured','no fabricated external deliveries');
select pg_temp.o_assert(public.operations_overview()::text not like '%Private patient prose%','aggregates do not expose inquiry descriptions');
select pg_temp.o_denied('select public.portal_command(''save_setting'',''{"key":"operations.health","value":{"status":"ready"}}'')','PORTAL_DENIED');
select pg_temp.o_denied(format('select public.operations_command(''operations_policy'',%L)',pg_temp.o_input('{"unassignedHours":0,"supportHours":1,"providerHours":1,"patientHours":1}')::text),'PORTAL_INVALID');
select pg_temp.o_denied(format('select public.operations_command(''operations_policy'',%L)',pg_temp.o_input('{"unassignedHours":1,"supportHours":1,"providerHours":1,"patientHours":1,"confirmed":false}')::text),'PORTAL_CONFIRMATION_REQUIRED');
insert into ops(k,v) values('incidentInput',pg_temp.o_input(jsonb_build_object('category','database','severity','high','ownerId',(select id from ops where k='admin'))));
insert into ops(k,id) select 'incident',(public.operations_command('operations_incident_create',(select v from ops where k='incidentInput'))->>'id')::uuid;
select pg_temp.o_assert(public.operations_command('operations_incident_create',(select v from ops where k='incidentInput'))->>'id'=(select id::text from ops where k='incident'),'retry cannot duplicate incident or notification');
select pg_temp.o_denied(format('select public.operations_command(''operations_incident_create'',%L)',((select v from ops where k='incidentInput')||'{"severity":"critical"}')::text),'INQUIRY_RETRY_CONFLICT');
select pg_temp.o_denied(format('select public.operations_command(''operations_incident_update'',%L)',pg_temp.o_input(jsonb_build_object('incidentId',(select id from ops where k='incident'),'expectedRevision',1,'status','resolved'))::text),'PORTAL_TRANSITION_INVALID');
select public.operations_command('operations_incident_update',pg_temp.o_input(jsonb_build_object('incidentId',(select id from ops where k='incident'),'expectedRevision',1,'status','acknowledged')));
select public.operations_command('operations_incident_update',pg_temp.o_input(jsonb_build_object('incidentId',(select id from ops where k='incident'),'expectedRevision',2,'status','investigating')));
select pg_temp.o_denied(format('select public.operations_command(''operations_incident_update'',%L)',pg_temp.o_input(jsonb_build_object('incidentId',(select id from ops where k='incident'),'expectedRevision',3,'status','resolved'))::text),'PORTAL_REVIEW_REASON_REQUIRED');
select public.operations_command('operations_incident_update',pg_temp.o_input(jsonb_build_object('incidentId',(select id from ops where k='incident'),'expectedRevision',3,'status','resolved','resolution','service_restored')));
select public.operations_command('operations_incident_update',pg_temp.o_input(jsonb_build_object('incidentId',(select id from ops where k='incident'),'expectedRevision',4,'status','closed','resolution','service_restored')));
select pg_temp.o_assert((select revision=5 and resolved_at is not null from public.operational_incidents where id=(select id from ops where k='incident')),'incident lifecycle records revision and resolution');
insert into ops(k,v) values('escalate',pg_temp.o_input(jsonb_build_object('caseId',(select id from ops where k='case'),'expectedRevision',1)));
select public.operations_command('operations_escalate',(select v from ops where k='escalate'));
select public.operations_command('operations_escalate',(select v from ops where k='escalate'));
select pg_temp.o_assert((select status='escalated' from public.support_cases where id=(select id from ops where k='case')),'explicit escalation reuses real inquiry command');
reset role;
insert into ops(k,v) values('eventInput',jsonb_build_object('correlationId',gen_random_uuid(),'operationId',(select id from ops where k='operation'),'kind','inquiry','action','message','outcome','failed','category','timeout','durationMs',10,'retryCount',0,'modelFailures','[]'::jsonb,'recovered',false));
select public.operations_record_request((select id from ops where k='patient'),(select v from ops where k='eventInput'));
select public.operations_record_request((select id from ops where k='patient'),(select v from ops where k='eventInput'));
select pg_temp.o_assert((select count(*)=1 from public.audit_events where event_name='operations.request' and metadata->>'correlationId'=(select v->>'correlationId' from ops where k='eventInput')),'correlation prevents duplicate operational events');
select pg_temp.o_denied(format('select public.operations_record_request(%L,%L)',(select id from ops where k='patient'),((select v from ops where k='eventInput')||'{"prompt":"Patient private"}')::text),'PORTAL_INVALID');
select pg_temp.o_denied(format('select public.operations_record_request(%L,%L)',(select id from ops where k='patient'),((select v from ops where k='eventInput')||'{"modelFailures":["patient private"]}')::text),'PORTAL_INVALID');
select pg_temp.o_denied(format('select public.operations_record_request(%L,%L)',(select id from ops where k='patient'),((select v from ops where k='eventInput')||'{"retryCount":33}')::text),'PORTAL_INVALID');
insert into ops(k,id) select 'event',id from public.audit_events where event_name='operations.request' and metadata->>'correlationId'=(select v->>'correlationId' from ops where k='eventInput');
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from ops where k='admin'),true);
insert into ops(k,v) values('reconcile',pg_temp.o_input(jsonb_build_object('eventId',(select id from ops where k='event'))));
select pg_temp.o_assert(public.operations_command('operations_reconcile',(select v from ops where k='reconcile'))->>'status'='unknown','uncertain commit stays unknown without replay');
select pg_temp.o_assert(public.operations_command('operations_reconcile',(select v from ops where k='reconcile'))->>'attemptCount'='1','same-operation retry does not consume another attempt');
select pg_temp.o_denied(format('select public.operations_command(''operations_reconcile'',%L)',pg_temp.o_input(jsonb_build_object('eventId',(select id from ops where k='event')))::text),'OPERATIONS_RETRY_WAIT');
reset role;
update public.operational_recovery_attempts set next_attempt_at=now()-interval '1 second';
insert into public.support_operation_receipts(actor_id,operation_id,action,input_hash,case_id,result) values((select id from ops where k='patient'),(select id from ops where k='operation'),'message','original',(select id from ops where k='case'),'{"private":"Never copied to monitoring"}');
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from ops where k='admin'),true);
select pg_temp.o_assert(public.operations_command('operations_reconcile',pg_temp.o_input(jsonb_build_object('eventId',(select id from ops where k='event'))))->>'resultCode'='commit_confirmed','receipt confirms commit without reissuing it');
select pg_temp.o_assert(public.operations_overview()::text not like '%Never copied%','receipt payload remains private');
select pg_temp.o_denied(format('select public.operations_command(''operations_reconcile'',%L)',pg_temp.o_input(jsonb_build_object('eventId',(select id from ops where k='event')))::text),'PORTAL_TRANSITION_INVALID');
select pg_temp.o_assert((select count(*)=0 from public.support_case_messages where body like '%Private patient%'),'reconciliation never creates duplicate messages');
reset role;
-- Permanent and exhausted outcomes are terminal; only safe receipt reads are retried.
insert into ops(k,v) values('permanentInput',(select v from ops where k='eventInput')||jsonb_build_object('correlationId',gen_random_uuid(),'operationId',gen_random_uuid(),'category','consent')),
 ('unknownInput',(select v from ops where k='eventInput')||jsonb_build_object('correlationId',gen_random_uuid(),'operationId',gen_random_uuid()));
select public.operations_record_request((select id from ops where k='patient'),(select v from ops where k='permanentInput'));
select public.operations_record_request((select id from ops where k='patient'),(select v from ops where k='unknownInput'));
insert into ops(k,id) select 'permanentEvent',id from public.audit_events where metadata->>'correlationId'=(select v->>'correlationId' from ops where k='permanentInput');
insert into ops(k,id) select 'unknownEvent',id from public.audit_events where metadata->>'correlationId'=(select v->>'correlationId' from ops where k='unknownInput');
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from ops where k='admin'),true);
select pg_temp.o_assert(public.operations_command('operations_reconcile',pg_temp.o_input(jsonb_build_object('eventId',(select id from ops where k='permanentEvent'))))->>'resultCode'='not_retryable','permanent consent denial is not retried');
select public.operations_command('operations_reconcile',pg_temp.o_input(jsonb_build_object('eventId',(select id from ops where k='unknownEvent'))));
reset role;
update public.operational_recovery_attempts set next_attempt_at=now()-interval '1 second' where source_event_id=(select id from ops where k='unknownEvent');
set local role authenticated;
select public.operations_command('operations_reconcile',pg_temp.o_input(jsonb_build_object('eventId',(select id from ops where k='unknownEvent'))));
reset role;
update public.operational_recovery_attempts set next_attempt_at=now()-interval '1 second' where source_event_id=(select id from ops where k='unknownEvent');
set local role authenticated;
select pg_temp.o_assert(public.operations_command('operations_reconcile',pg_temp.o_input(jsonb_build_object('eventId',(select id from ops where k='unknownEvent'))))->>'resultCode'='attempt_limit','third unresolved check reaches terminal failure without replay');
select pg_temp.o_denied(format('select public.operations_command(''operations_reconcile'',%L)',pg_temp.o_input(jsonb_build_object('eventId',(select id from ops where k='unknownEvent')))::text),'PORTAL_TRANSITION_INVALID');
reset role;
select pg_temp.o_assert((public.operations_overview()->'notifications'->>'created')::integer=(select count(*) from public.portal_notifications where created_at>=now()-interval '24 hours'),'notification metric counts real created records');
reset role;

select public.operations_record_health((select id from ops where k='admin'),gen_random_uuid(),jsonb_build_object('checkedAt',now(),'status','ready','database','available','storage','private_bucket_present','ai','configured_not_probed','externalDelivery','not_configured','externalMonitoring','not_configured','durationMs',10,'attempts',1));
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from ops where k='admin'),true);
select pg_temp.o_assert(public.operations_overview()->'health'->>'status'='ready','verified server probe is visible to Admin');
select pg_temp.o_denied('update public.operational_incidents set severity=''low''','permission denied');
reset role;
update public.portal_accounts set active=false where user_id=(select id from ops where k='admin');
insert into public.portal_accounts(user_id,active) values((select id from ops where k='admin'),false) on conflict(user_id) do update set active=false;
set local role authenticated;
select pg_temp.o_denied('select public.operations_overview()','PORTAL_DENIED');
select pg_temp.o_assert((select count(*)=0 from public.operational_incidents),'disabled Admin loses operational RLS access');
rollback;
