-- Preserve actual partial execution failures and limits in the private projection.
create or replace function public.operations_overview() returns jsonb language plpgsql stable security definer set search_path='' as $$
 declare result jsonb;begin
 if not private.portal_active() or not private.portal_admin() then raise exception 'PORTAL_DENIED';end if;
 with current_cases as materialized(select * from private.operations_cases()), recent_runs as materialized(select id,status,created_at,started_at,finished_at,metadata from public.agent_runs where created_at>=now()-interval '24 hours'), events as materialized(select id,occurred_at,metadata from public.audit_events where event_name='operations.request' and occurred_at>=now()-interval '24 hours'), readiness as materialized(select v from jsonb_array_elements(public.portal_network_readiness(null)->'rows') v where v->>'origin'='provider_submitted')
 select jsonb_build_object('asOf',now(),'windowStart',now()-interval '24 hours','policy',private.operations_policy(),'health',(select value from public.portal_settings where key='operations.health'),'lastSuccessfulCheck',(select max(occurred_at) from public.audit_events where event_name='operations.command.health_check' and metadata->'result'->>'status'='ready'),'healthHistory',coalesce((select jsonb_agg(metadata->'result') from(select metadata from public.audit_events where event_name='operations.command.health_check' order by occurred_at desc limit 10)h),'[]'),
  'inquiries',jsonb_build_object('new24h',(select count(*) from public.support_cases where inquiry_source<>'legacy' and consent_revoked_at is null and created_at>=now()-interval '24 hours'),'active',(select count(*) from current_cases),'unassigned',(select count(*) from current_cases where not assigned),'support',(select count(*) from current_cases where attention='support'),'provider',(select count(*) from current_cases where attention='provider'),'patient',(select count(*) from current_cases where attention='patient'),'overdue',(select count(*) from current_cases where overdue)),
  'notifications',jsonb_build_object('created',(select count(*) from public.portal_notifications where created_at>=now()-interval '24 hours'),'read',(select count(*) from public.portal_notifications where created_at>=now()-interval '24 hours' and read_at is not null),'unread',(select count(*) from public.portal_notifications where created_at>=now()-interval '24 hours' and read_at is null),'channel','in_app','externalDelivery','not_configured'),
  'providers',jsonb_build_object('registered',(select count(*) from readiness),'awaitingVerification',(select count(*) from readiness where v->>'verificationStatus' in ('submitted','changes_requested','not_submitted','rejected')),'awaitingOwnership',(select count(*) from readiness where (v->>'ownershipApproved')::boolean and (v->>'ownedListings')::integer=0),'withoutTeam',(select count(*) from readiness where (v->>'ownershipApproved')::boolean and (v->>'activeMembers')::integer=0),'withPublishedListings',(select count(*) from readiness where (v->>'publishedListings')::integer>0),'connected',(select count(*) from readiness where (v->>'canReceiveInquiries')::boolean),
   'responseObserved',(select count(distinct c.organization_id) from public.support_cases c where c.provider_responded_at is not null and c.consent_revoked_at is null and c.share_with_provider and private.provider_organization_approved(c.organization_id) and exists(select 1 from public.organization_members m where m.organization_id=c.organization_id and m.user_id=c.provider_responded_by and m.active))),
  'pilotRows',coalesce((select jsonb_agg(jsonb_build_object('organizationId',v->>'id','acceptanceRecorded',exists(select 1 from public.audit_events e where e.event_name='operations.command.operations_accept_pilot' and e.metadata->'result'->>'organizationId'=v->>'id' and private.operations_pilot_valid((e.metadata->'result'->>'caseId')::uuid,(v->>'id')::uuid) and (v->>'canReceiveInquiries')::boolean),'notificationCreated',exists(select 1 from public.portal_notifications n join public.organization_members m on m.user_id=n.user_id and m.organization_id=(v->>'id')::uuid and m.active where n.resource_type='support_case' and exists(select 1 from public.support_cases c where c.id=n.resource_id and c.organization_id=m.organization_id)),'responseObserved',exists(select 1 from public.support_cases c where c.organization_id=(v->>'id')::uuid and private.operations_pilot_valid(c.id,c.organization_id)))) from readiness),'[]'),
  'ai',jsonb_build_object('runs',(select count(*) from recent_runs),'finished',(select count(*) from recent_runs where finished_at is not null),'failed',(select count(*) from recent_runs where status='failed'),'stalled',(select count(*) from recent_runs where finished_at is null and created_at<now()-interval '5 minutes'),'requestEvents',(select count(*) from events where metadata->>'kind'='ai'),'requestFailures',(select count(*) from events where metadata->>'kind'='ai' and metadata->>'outcome' in ('failed','partially_completed') and metadata ? 'category'),'recovered',(select count(*) from events where metadata->>'kind'='ai' and metadata->>'recovered'='true')),
  'incidents',coalesce((select jsonb_object_agg(status,n) from(select status,count(*) n from public.operational_incidents group by status)i),'{}'),
  'events',coalesce((select jsonb_agg(metadata||jsonb_build_object('id',id,'occurredAt',occurred_at)) from(select * from events order by occurred_at desc limit 30)e),'[]'),
  'failures',coalesce((select jsonb_agg(metadata||jsonb_build_object('id',id,'occurredAt',occurred_at)) from(select * from events where metadata->>'outcome' in ('failed','partially_completed') and metadata ? 'category' order by occurred_at desc limit 30)e),'[]'),
  'runs',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'status',r.status,'createdAt',r.created_at,'finishedAt',r.finished_at,'durationMs',case when r.finished_at>=r.started_at then round(extract(epoch from (r.finished_at-r.started_at))*1000) end,'category',case when r.status='failed' then private.operations_failure_category(r.metadata->>'errorCode') end)) from(select * from recent_runs order by created_at desc limit 30)r),'[]'),
  'tools',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'runId',a.run_id,'tool',case when a.tool_name in ('get_inquiry_context','get_recovery_context','verify_provider_information','refresh_provider_verification','get_provider_verification_status','get_provider_verification_history','compare_provider_evidence','get_document_requirements','get_document_package','upload_document','match_document_to_requirement','remove_document','prepare_document_package','add_document_requirement','research_healthcare_information','search_treatments','search_hospitals','search_doctors','search_packages','search_countries','search_services','get_treatment','get_hospital','get_doctor','get_package','get_country','compare_treatment_options','get_hospital_details','get_doctor_details','get_treatment_details','get_package_details','search_locations','check_requirements','compare_providers','get_case_context','get_case_documents_metadata','create_case','update_case','create_agent_task','request_user_information','request_external_action') then a.tool_name else 'registered_tool' end,'status',a.status,'createdAt',a.created_at,'category',private.operations_failure_category(a.metadata->>'errorCode'))) from(select id,run_id,tool_name,status,created_at,metadata from public.agent_actions where status='failed' and created_at>=now()-interval '24 hours' order by created_at desc limit 30)a),'[]'),
  'incidentRows',coalesce((select jsonb_agg(to_jsonb(i)) from(select id,category,severity,status,revision,owner_id,created_at,resolution_note from public.operational_incidents order by (status in ('closed','resolved')),updated_at desc limit 30)i),'[]'),
  'recoveries',coalesce((select jsonb_agg(to_jsonb(j)) from(select id,kind,status,attempt_count,last_attempt_at,next_attempt_at,result_code,source_event_id from public.operational_recovery_attempts order by last_attempt_at desc limit 30)j),'[]')) into result;
 return result;end;$$;
